/* ── festivals.js — Bengali festivals data + quiz questions ──────────── */

const FESTIVALS = [
  // ─── 1. পহেলা বৈশাখ ─────────────────────────────────────
  {
    id: 'pohela-boishakh',
    bengaliName: 'পহেলা বৈশাখ',
    englishName: 'Pohela Boishakh (Bengali New Year)',
    icon: '🎉',
    tags: ['নববর্ষ', 'New Year'],
    descBn: 'পহেলা বৈশাখ বাংলা নববর্ষের প্রথম দিন। বৈশাখ মাসের প্রথম দিনে সারাদেশে আনন্দ-উৎসবের মাধ্যমে নতুন বছরকে বরণ করা হয়। ঢাকায় মঙ্গল শোভাযাত্রা ও গ্রামে বৈশাখী মেলা এই উৎসবের প্রধান আকর্ষণ।',
    descEn: 'Pohela Boishakh is the first day of the Bengali New Year, celebrated on the first day of the month of Boishakh. Across Bangladesh and West Bengal, people welcome the new year with joyous festivities. The Mangal Shobhajatra procession in Dhaka and village fairs are major highlights of this celebration.',
    traditionsBn: [
      'ঢাকা বিশ্ববিদ্যালয়ে মঙ্গল শোভাযাত্রা বের হয়।',
      'ব্যবসায়ীরা হালখাতা অনুষ্ঠান করেন — নতুন হিসাবের খাতা খোলেন।',
      'পান্তা ইলিশ খাওয়া পহেলা বৈশাখের একটি জনপ্রিয় রীতি।',
      'বৈশাখী মেলায় মাটির পুতুল, নাগরদোলা ও লোকসংগীতের আয়োজন থাকে।',
    ],
    traditionsEn: [
      'The Mangal Shobhajatra procession takes place at Dhaka University.',
      'Businesspeople hold Halkhata ceremonies — opening new account books.',
      'Eating panta ilish (fermented rice with hilsa fish) is a popular Pohela Boishakh tradition.',
      'Boishakhi fairs feature clay dolls, Ferris wheels, and folk music.',
    ],
    quiz: [
      {
        id: 'pohela-boishakh-1',
        prompt: 'What does নববর্ষ mean?',
        promptBn: 'নববর্ষ শব্দের ইংরেজি অর্থ কী?',
        options: ['New Year', 'New Moon', 'New Day', 'New Season'],
        correct: 0,
        explanation: 'নববর্ষ (noboborsho) = New Year. নব (new) + বর্ষ (year).',
      },
      {
        id: 'pohela-boishakh-2',
        prompt: 'What does হালখাতা mean?',
        promptBn: 'হালখাতা শব্দের অর্থ কী?',
        options: ['Opening new account books', 'Closing old shops', 'A type of food', 'A folk song'],
        correct: 0,
        explanation: 'হালখাতা (halkhata) = opening new account books. হাল (new/current) + খাতা (ledger).',
      },
      {
        id: 'pohela-boishakh-3',
        prompt: 'What does শোভাযাত্রা mean?',
        promptBn: 'শোভাযাত্রা শব্দের ইংরেজি অর্থ কী?',
        options: ['Procession/parade', 'Festival', 'Concert', 'Market'],
        correct: 0,
        explanation: 'শোভাযাত্রা (shobhajatra) = procession or parade. মঙ্গল শোভাযাত্রা is a UNESCO heritage.',
      },
    ],
  },

  // ─── 2. দুর্গা পূজা ────────────────────────────────────────
  {
    id: 'durga-puja',
    bengaliName: 'দুর্গা পূজা',
    englishName: 'Durga Puja',
    icon: '🪔',
    tags: ['পূজা', 'Hindu Festival'],
    descBn: 'দুর্গা পূজা বাঙালি হিন্দু সম্প্রদায়ের সবচেয়ে বড় ধর্মীয় ও সামাজিক উৎসব। শারদীয় নবরাত্রিতে দেবী দুর্গার আরাধনা করা হয়। কলকাতা ও ঢাকায় বিশাল প্রতিমা ও মণ্ডপ সাজিয়ে পাঁচ দিনব্যাপী এই উৎসব পালিত হয়।',
    descEn: 'Durga Puja is the largest religious and social festival of the Bengali Hindu community. Goddess Durga is worshipped during the autumnal Navaratri. Elaborate idols and pandals are created in Kolkata and Dhaka, and the five-day celebration brings communities together in devotion and festivity.',
    traditionsBn: [
      'ষষ্ঠী থেকে দশমী পর্যন্ত পাঁচ দিন ধরে পূজা চলে।',
      'দশমীতে প্রতিমা বিসর্জন দেওয়া হয় নদীতে বা জলাশয়ে।',
      'ঢাকেশ্বরী মন্দির ঢাকায় দুর্গা পূজার প্রধান কেন্দ্র।',
      'সিঁদুর খেলা ও ধুনুচি নাচ দুর্গা পূজার বিশেষ রীতি।',
    ],
    traditionsEn: [
      'The puja spans five days, from Shashthi to Dashami.',
      'On Dashami, the idol is immersed in a river or water body (bishorjon).',
      'Dhakeshwari Temple is a major center for Durga Puja in Dhaka.',
      'Sindoor khela (vermilion play) and dhunuchi naach (incense dance) are special rituals.',
    ],
    quiz: [
      {
        id: 'durga-puja-1',
        prompt: 'What does প্রতিমা mean?',
        promptBn: 'প্রতিমা শব্দের ইংরেজি অর্থ কী?',
        options: ['Idol/statue', 'Temple', 'Prayer', 'Offering'],
        correct: 0,
        explanation: 'প্রতিমা (protima) = idol or statue. দুর্গা প্রতিমা = idol of Goddess Durga.',
      },
      {
        id: 'durga-puja-2',
        prompt: 'What does বিসর্জন mean in the context of Durga Puja?',
        promptBn: 'দুর্গা পূজায় বিসর্জন শব্দের অর্থ কী?',
        options: ['Immersion (of the idol)', 'Decoration', 'Worship', 'Procession'],
        correct: 0,
        explanation: 'বিসর্জন (bishorjon) = immersion. The idol is immersed in water on দশমী (Dashami).',
      },
      {
        id: 'durga-puja-3',
        prompt: 'What does মণ্ডপ mean?',
        promptBn: 'মণ্ডপ শব্দের ইংরেজি অর্থ কী?',
        options: ['Pandal/pavilion', 'Temple', 'Market', 'Stage'],
        correct: 0,
        explanation: 'মণ্ডপ (mondop) = pandal or pavilion, the temporary structure housing the Durga idol.',
      },
    ],
  },

  // ─── 3. ঈদ উল ফিতর ─────────────────────────────────────
  {
    id: 'eid-ul-fitr',
    bengaliName: 'ঈদ উল ফিতর',
    englishName: 'Eid ul-Fitr',
    icon: '🌙',
    tags: ['ঈদ', 'Islamic Festival'],
    descBn: 'ঈদ উল ফিতর রমজান মাসের রোজা শেষে পালিত হয়। এটি বাংলাদেশের সবচেয়ে বড় ধর্মীয় উৎসব। ঈদের দিনে সকালে নামাজ পড়া হয়, আত্মীয়দের সাথে দেখা করা হয় এবং সেমাই ও বিভিন্ন মিষ্টি খাওয়া হয়।',
    descEn: 'Eid ul-Fitr is celebrated at the end of the holy month of Ramadan after a month of fasting. It is the biggest religious festival in Bangladesh. The day begins with congregational prayers, followed by visiting relatives and enjoying special sweets like semai (vermicelli) and various desserts.',
    traditionsBn: [
      'ঈদের সকালে ঈদগাহে বা মসজিদে নামাজ আদায় করা হয়।',
      'ফিতরা দান করা ঈদের একটি গুরুত্বপূর্ণ বিধান।',
      'সেমাই, পায়েস ও বিভিন্ন মিষ্টান্ন তৈরি করা হয়।',
      'নতুন জামাকাপড় পরে আত্মীয়স্বজনের বাড়িতে বেড়াতে যাওয়া হয়।',
    ],
    traditionsEn: [
      'Morning prayers are offered at the Eidgah or mosque.',
      'Giving Fitra (charity) is an important obligation of Eid.',
      'Semai (vermicelli), payesh (rice pudding), and various sweets are prepared.',
      'People wear new clothes and visit relatives\' homes.',
    ],
    quiz: [
      {
        id: 'eid-ul-fitr-1',
        prompt: 'What does রোজা mean?',
        promptBn: 'রোজা শব্দের ইংরেজি অর্থ কী?',
        options: ['Fasting', 'Praying', 'Feasting', 'Donating'],
        correct: 0,
        explanation: 'রোজা (roja) = fasting. রমজান মাসে মুসলমানরা রোজা রাখেন।',
      },
      {
        id: 'eid-ul-fitr-2',
        prompt: 'What does নামাজ mean?',
        promptBn: 'নামাজ শব্দের অর্থ কী?',
        options: ['Prayer (Islamic)', 'Fasting', 'Charity', 'Pilgrimage'],
        correct: 0,
        explanation: 'নামাজ (namaj) = Islamic prayer. ঈদের নামাজ = Eid prayer.',
      },
      {
        id: 'eid-ul-fitr-3',
        prompt: 'What does সেমাই mean?',
        promptBn: 'সেমাই শব্দের ইংরেজি অর্থ কী?',
        options: ['Vermicelli (sweet dish)', 'Rice pudding', 'Bread', 'Curry'],
        correct: 0,
        explanation: 'সেমাই (shemai) = vermicelli, a popular sweet dish made with milk and sugar on Eid.',
      },
    ],
  },

  // ─── 4. ঈদ উল আযহা ────────────────────────────────────────
  {
    id: 'eid-ul-adha',
    bengaliName: 'ঈদ উল আযহা',
    englishName: 'Eid ul-Adha',
    icon: '🕌',
    tags: ['ঈদ', 'Islamic Festival'],
    descBn: 'ঈদ উল আযহা ইসলামের দ্বিতীয় বৃহত্তম উৎসব, যা কোরবানির ঈদ নামেও পরিচিত। হযরত ইব্রাহিম (আ.)-এর ত্যাগের স্মরণে পশু কোরবানি করা হয়। কোরবানির মাংস তিন ভাগে ভাগ করে পরিবার, আত্মীয় ও গরিবদের মধ্যে বিতরণ করা হয়।',
    descEn: 'Eid ul-Adha is the second largest Islamic festival, also known as the Festival of Sacrifice. Animals are sacrificed in remembrance of Prophet Ibrahim\'s devotion. The meat is divided into three portions — for the family, relatives, and the poor — embodying the spirit of sharing and charity.',
    traditionsBn: [
      'কোরবানির পশু — গরু, ছাগল, ভেড়া বা উট — জবাই করা হয়।',
      'মাংস তিন ভাগ করা হয়: নিজের, আত্মীয়ের ও গরিবের জন্য।',
      'ঈদের সকালে জামাতে নামাজ আদায় করা হয়।',
      'হজ পালনকারীরা এই সময়ে মক্কায় অবস্থান করেন।',
    ],
    traditionsEn: [
      'Sacrificial animals — cow, goat, sheep, or camel — are slaughtered.',
      'The meat is divided into three parts: for family, relatives, and the poor.',
      'Congregational prayers are offered on the morning of Eid.',
      'Hajj pilgrims stay in Makkah during this time.',
    ],
    quiz: [
      {
        id: 'eid-ul-adha-1',
        prompt: 'What does কোরবানি mean?',
        promptBn: 'কোরবানি শব্দের ইংরেজি অর্থ কী?',
        options: ['Sacrifice', 'Donation', 'Prayer', 'Pilgrimage'],
        correct: 0,
        explanation: 'কোরবানি (korbani) = sacrifice. কোরবানির ঈদ = Festival of Sacrifice.',
      },
      {
        id: 'eid-ul-adha-2',
        prompt: 'What does ত্যাগ mean?',
        promptBn: 'ত্যাগ শব্দের অর্থ কী?',
        options: ['Sacrifice/renunciation', 'Gift', 'Celebration', 'Journey'],
        correct: 0,
        explanation: 'ত্যাগ (tyag) = sacrifice or renunciation. ইব্রাহিম (আ.)-এর ত্যাগের স্মরণে ঈদ পালিত হয়।',
      },
      {
        id: 'eid-ul-adha-3',
        prompt: 'What does মাংস mean?',
        promptBn: 'মাংস শব্দের ইংরেজি অর্থ কী?',
        options: ['Meat', 'Fish', 'Rice', 'Bread'],
        correct: 0,
        explanation: 'মাংস (mangsho) = meat. কোরবানির মাংস তিন ভাগে ভাগ করা হয়।',
      },
    ],
  },

  // ─── 5. সরস্বতী পূজা ──────────────────────────────────────
  {
    id: 'saraswati-puja',
    bengaliName: 'সরস্বতী পূজা',
    englishName: 'Saraswati Puja',
    icon: '📚',
    tags: ['পূজা', 'Hindu Festival'],
    descBn: 'সরস্বতী পূজা বিদ্যা ও সংগীতের দেবী সরস্বতীর আরাধনা। মাঘ মাসের শুক্লা পঞ্চমীতে এই পূজা অনুষ্ঠিত হয়, যা বসন্ত পঞ্চমী নামেও পরিচিত। শিক্ষার্থীরা বই ও খাতা দেবীর পায়ে রেখে আশীর্বাদ প্রার্থনা করেন।',
    descEn: 'Saraswati Puja is the worship of Goddess Saraswati, the deity of knowledge, music, and the arts. It is celebrated on Shukla Panchami in the month of Magh, also known as Basant Panchami. Students place their books and instruments at the feet of the goddess seeking blessings for learning.',
    traditionsBn: [
      'শিক্ষার্থীরা বই, খাতা ও কলম দেবীর সামনে রাখেন।',
      'হলুদ শাড়ি ও পোশাক পরা এই পূজার বিশেষ রীতি।',
      'ছোট শিশুদের হাতেখড়ি দেওয়া হয় এই দিনে।',
      'বিদ্যালয় ও বিশ্ববিদ্যালয়ে বিশেষ পূজার আয়োজন করা হয়।',
    ],
    traditionsEn: [
      'Students place books, notebooks, and pens before the goddess.',
      'Wearing yellow sarees and clothing is a special custom of this puja.',
      'Young children are initiated into learning (hatekhari) on this day.',
      'Schools and universities organize special puja ceremonies.',
    ],
    quiz: [
      {
        id: 'saraswati-puja-1',
        prompt: 'What does বিদ্যা mean?',
        promptBn: 'বিদ্যা শব্দের ইংরেজি অর্থ কী?',
        options: ['Knowledge/learning', 'Music', 'Dance', 'Art'],
        correct: 0,
        explanation: 'বিদ্যা (bidya) = knowledge or learning. সরস্বতী বিদ্যার দেবী।',
      },
      {
        id: 'saraswati-puja-2',
        prompt: 'What does হাতেখড়ি mean?',
        promptBn: 'হাতেখড়ি শব্দের অর্থ কী?',
        options: ['Initiation into learning', 'Writing exam', 'Graduation', 'School admission'],
        correct: 0,
        explanation: 'হাতেখড়ি (hatekhari) = initiation into learning, a child\'s first writing lesson. হাতে (in hand) + খড়ি (chalk).',
      },
      {
        id: 'saraswati-puja-3',
        prompt: 'What does আশীর্বাদ mean?',
        promptBn: 'আশীর্বাদ শব্দের ইংরেজি অর্থ কী?',
        options: ['Blessing', 'Curse', 'Wish', 'Gift'],
        correct: 0,
        explanation: 'আশীর্বাদ (ashirbad) = blessing. শিক্ষার্থীরা দেবীর আশীর্বাদ প্রার্থনা করেন।',
      },
    ],
  },

  // ─── 6. নবান্ন ─────────────────────────────────────────────
  {
    id: 'nabanna',
    bengaliName: 'নবান্ন',
    englishName: 'Nabanna (Harvest Festival)',
    icon: '🌾',
    tags: ['ফসল', 'Harvest'],
    descBn: 'নবান্ন বাংলার ঐতিহ্যবাহী ফসল কাটার উৎসব। অগ্রহায়ণ মাসে নতুন ধান ওঠার পর কৃষকরা আনন্দে নবান্ন উৎসব পালন করেন। নতুন চালের পিঠা, পায়েস ও নানা রকম খাবার তৈরি করে প্রতিবেশী ও আত্মীয়দের সাথে ভাগ করে খাওয়া হয়।',
    descEn: 'Nabanna is the traditional Bengali harvest festival celebrated in the month of Agrohayon when new rice is harvested. Farmers celebrate with joy, preparing pithas (rice cakes), payesh (rice pudding), and various dishes from freshly harvested rice, sharing them with neighbors and relatives.',
    traditionsBn: [
      'নতুন চালের পিঠা ও পায়েস তৈরি করা হয়।',
      'কৃষকরা নতুন ফসল ঘরে তোলার আনন্দে উৎসব করেন।',
      'প্রতিবেশী ও আত্মীয়দের মধ্যে খাবার বিতরণ করা হয়।',
      'লোকসংগীত, নৃত্য ও গ্রামীণ মেলার আয়োজন করা হয়।',
    ],
    traditionsEn: [
      'Pithas (rice cakes) and payesh (rice pudding) are made from new rice.',
      'Farmers celebrate the joy of bringing new crops home.',
      'Food is shared among neighbors and relatives.',
      'Folk music, dance, and village fairs are organized.',
    ],
    quiz: [
      {
        id: 'nabanna-1',
        prompt: 'What does নবান্ন mean?',
        promptBn: 'নবান্ন শব্দের ইংরেজি অর্থ কী?',
        options: ['New rice/harvest festival', 'New year', 'Full moon', 'Rainy season'],
        correct: 0,
        explanation: 'নবান্ন (nabanna) = new rice or harvest. নব (new) + অন্ন (rice/food).',
      },
      {
        id: 'nabanna-2',
        prompt: 'What does পিঠা mean?',
        promptBn: 'পিঠা শব্দের অর্থ কী?',
        options: ['Rice cake (traditional Bengali cake)', 'Bread', 'Curry', 'Sweet drink'],
        correct: 0,
        explanation: 'পিঠা (pitha) = traditional Bengali rice cake. নবান্নে নতুন চালের পিঠা তৈরি হয়।',
      },
      {
        id: 'nabanna-3',
        prompt: 'What does কৃষক mean?',
        promptBn: 'কৃষক শব্দের ইংরেজি অর্থ কী?',
        options: ['Farmer', 'Fisher', 'Weaver', 'Trader'],
        correct: 0,
        explanation: 'কৃষক (krishok) = farmer. কৃষি (agriculture) → কৃষক (one who farms).',
      },
    ],
  },

  // ─── 7. পৌষ মেলা ───────────────────────────────────────────
  {
    id: 'poush-mela',
    bengaliName: 'পৌষ মেলা',
    englishName: 'Poush Mela (Winter Fair)',
    icon: '🎪',
    tags: ['মেলা', 'Winter Fair'],
    descBn: 'পৌষ মেলা শীতকালে পৌষ মাসে অনুষ্ঠিত বাংলার ঐতিহ্যবাহী মেলা। শান্তিনিকেতনে রবীন্দ্রনাথ ঠাকুরের প্রবর্তিত পৌষ মেলা সবচেয়ে বিখ্যাত। এই মেলায় বাউল গান, হস্তশিল্প, লোকশিল্প ও গ্রামীণ সংস্কৃতির চমৎকার সমাবেশ ঘটে।',
    descEn: 'Poush Mela is a traditional Bengali winter fair held in the month of Poush. The most famous Poush Mela takes place at Shantiniketan, initiated by Rabindranath Tagore. The fair showcases Baul music, handicrafts, folk art, and a wonderful gathering of rural Bengali culture.',
    traditionsBn: [
      'শান্তিনিকেতনের পৌষ মেলা রবীন্দ্রনাথ ঠাকুর প্রবর্তন করেন।',
      'বাউল গান ও লোকসংগীত মেলার প্রধান আকর্ষণ।',
      'হস্তশিল্প, মাটির কাজ ও লোকশিল্পের পসরা সাজানো থাকে।',
      'খেজুরের রস, পাটালি গুড় ও পিঠা শীতের এই মেলার বিশেষ খাবার।',
    ],
    traditionsEn: [
      'The Shantiniketan Poush Mela was initiated by Rabindranath Tagore.',
      'Baul music and folk songs are the main attractions of the fair.',
      'Handicrafts, pottery, and folk art stalls are set up.',
      'Date palm juice, patali gur (jaggery), and pithas are special winter treats at the fair.',
    ],
    quiz: [
      {
        id: 'poush-mela-1',
        prompt: 'What does মেলা mean?',
        promptBn: 'মেলা শব্দের ইংরেজি অর্থ কী?',
        options: ['Fair/festival market', 'Market', 'Temple', 'Village'],
        correct: 0,
        explanation: 'মেলা (mela) = fair or festival market. পৌষ মেলা = Poush fair.',
      },
      {
        id: 'poush-mela-2',
        prompt: 'What does বাউল mean?',
        promptBn: 'বাউল শব্দের অর্থ কী?',
        options: ['Bengali mystic folk singer', 'Classical dancer', 'Priest', 'Poet'],
        correct: 0,
        explanation: 'বাউল (baul) = a Bengali mystic folk musician/singer tradition. বাউল গান is a UNESCO heritage.',
      },
      {
        id: 'poush-mela-3',
        prompt: 'What does হস্তশিল্প mean?',
        promptBn: 'হস্তশিল্প শব্দের ইংরেজি অর্থ কী?',
        options: ['Handicraft', 'Painting', 'Sculpture', 'Pottery'],
        correct: 0,
        explanation: 'হস্তশিল্প (hostoshilpo) = handicraft. হস্ত (hand) + শিল্প (craft/art).',
      },
    ],
  },

  // ─── 8. রথযাত্রা ──────────────────────────────────────────
  {
    id: 'rath-yatra',
    bengaliName: 'রথযাত্রা',
    englishName: 'Rath Yatra',
    icon: '🛕',
    tags: ['যাত্রা', 'Hindu Festival'],
    descBn: 'রথযাত্রা হিন্দু ধর্মের একটি প্রাচীন উৎসব যেখানে জগন্নাথ দেবের মূর্তি বিশাল রথে করে শোভাযাত্রায় বের করা হয়। বাংলায় এই উৎসব অত্যন্ত জনপ্রিয় এবং ইসকনের মাধ্যমে এটি সারা বিশ্বে পরিচিতি লাভ করেছে।',
    descEn: 'Rath Yatra is an ancient Hindu festival in which the deity Jagannath is carried in a grand chariot procession. The festival is immensely popular in Bengal, and through ISKCON it has gained worldwide recognition. Devotees pull the massive chariots through the streets with great devotion.',
    traditionsBn: [
      'জগন্নাথ দেবের বিশাল রথ রাস্তায় টেনে নিয়ে যাওয়া হয়।',
      'ভক্তরা রথের দড়ি ধরে টানেন — এটি পুণ্যের কাজ বলে বিশ্বাস।',
      'রথযাত্রায় কীর্তন ও ভজন গাওয়া হয়।',
      'ইসকনের মাধ্যমে রথযাত্রা আন্তর্জাতিক পরিচিতি পেয়েছে।',
    ],
    traditionsEn: [
      'The grand chariot of Lord Jagannath is pulled through the streets.',
      'Devotees pull the chariot ropes — believed to be a sacred act.',
      'Kirtan (devotional singing) and bhajan are performed during the procession.',
      'ISKCON has given Rath Yatra international recognition.',
    ],
    quiz: [
      {
        id: 'rath-yatra-1',
        prompt: 'What does রথ mean?',
        promptBn: 'রথ শব্দের ইংরেজি অর্থ কী?',
        options: ['Chariot', 'Temple', 'Boat', 'Cart'],
        correct: 0,
        explanation: 'রথ (roth) = chariot. রথযাত্রা = chariot procession/journey.',
      },
      {
        id: 'rath-yatra-2',
        prompt: 'What does ভক্ত mean?',
        promptBn: 'ভক্ত শব্দের অর্থ কী?',
        options: ['Devotee', 'Priest', 'Scholar', 'Traveler'],
        correct: 0,
        explanation: 'ভক্ত (bhokto) = devotee or worshipper. ভক্তি (bhokti) = devotion.',
      },
      {
        id: 'rath-yatra-3',
        prompt: 'What does যাত্রা mean?',
        promptBn: 'যাত্রা শব্দের ইংরেজি অর্থ কী?',
        options: ['Journey/procession', 'Festival', 'Dance', 'Song'],
        correct: 0,
        explanation: 'যাত্রা (jatra) = journey or procession. রথযাত্রা = chariot journey.',
      },
    ],
  },

  // ─── 9. শবে বরাত ───────────────────────────────────────────
  {
    id: 'shab-e-barat',
    bengaliName: 'শবে বরাত',
    englishName: 'Shab-e-Barat',
    icon: '✨',
    tags: ['ইসলামিক', 'Night of Fortune'],
    descBn: 'শবে বরাত শাবান মাসের ১৪ তারিখ রাতে পালিত হয়। মুসলমানরা এই রাতকে সৌভাগ্যের রাত বলে বিশ্বাস করেন এবং সারারাত ইবাদত ও দোয়া করেন। বাংলাদেশে এই রাতে হালুয়া-রুটি বিতরণ ও আতশবাজি ফোটানোর প্রচলন আছে।',
    descEn: 'Shab-e-Barat is observed on the night of the 14th of Shaban. Muslims believe it to be the Night of Fortune and spend the night in prayer and supplication. In Bangladesh, distributing halwa-ruti (sweets and bread) and lighting fireworks are popular customs on this night.',
    traditionsBn: [
      'সারারাত নফল নামাজ, কোরআন তেলাওয়াত ও জিকির করা হয়।',
      'হালুয়া-রুটি তৈরি করে প্রতিবেশীদের মধ্যে বিতরণ করা হয়।',
      'মসজিদগুলোতে বিশেষ মিলাদ ও দোয়ার আয়োজন করা হয়।',
      'আতশবাজি ও ফানুস ওড়ানো বাংলাদেশে এই রাতের জনপ্রিয় রীতি।',
    ],
    traditionsEn: [
      'Voluntary prayers, Quran recitation, and zikr are performed throughout the night.',
      'Halwa-ruti (sweets and bread) are prepared and distributed among neighbors.',
      'Mosques organize special milad (gatherings) and dua (supplication) sessions.',
      'Fireworks and flying lanterns are popular customs in Bangladesh on this night.',
    ],
    quiz: [
      {
        id: 'shab-e-barat-1',
        prompt: 'What does ইবাদত mean?',
        promptBn: 'ইবাদত শব্দের ইংরেজি অর্থ কী?',
        options: ['Worship/prayer', 'Fasting', 'Charity', 'Pilgrimage'],
        correct: 0,
        explanation: 'ইবাদত (ibadat) = worship or prayer. শবে বরাতে সারারাত ইবাদত করা হয়।',
      },
      {
        id: 'shab-e-barat-2',
        prompt: 'What does দোয়া mean?',
        promptBn: 'দোয়া শব্দের অর্থ কী?',
        options: ['Supplication/prayer', 'Song', 'Sermon', 'Lesson'],
        correct: 0,
        explanation: 'দোয়া (doa) = supplication or prayer request to God.',
      },
      {
        id: 'shab-e-barat-3',
        prompt: 'What does সৌভাগ্য mean?',
        promptBn: 'সৌভাগ্য শব্দের ইংরেজি অর্থ কী?',
        options: ['Fortune/good luck', 'Misfortune', 'Wealth', 'Health'],
        correct: 0,
        explanation: 'সৌভাগ্য (shoubhagyo) = fortune or good luck. শবে বরাত সৌভাগ্যের রাত।',
      },
    ],
  },

  // ─── 10. বসন্ত উৎসব ────────────────────────────────────────
  {
    id: 'basanta-utsav',
    bengaliName: 'বসন্ত উৎসব',
    englishName: 'Basanta Utsav (Spring Festival)',
    icon: '🌺',
    tags: ['ঋতু', 'Spring Festival'],
    descBn: 'বসন্ত উৎসব ফাল্গুন মাসে বসন্তের আগমন উপলক্ষে পালিত হয়। রবীন্দ্রনাথ ঠাকুর শান্তিনিকেতনে এই উৎসবের প্রচলন করেন। রঙিন আবিরে মাখামাখি, রবীন্দ্রসংগীত ও নৃত্যের মধ্য দিয়ে বসন্তকে বরণ করা হয়।',
    descEn: 'Basanta Utsav is the Spring Festival celebrated in the month of Falgun to welcome the arrival of spring. Rabindranath Tagore popularized this festival at Shantiniketan. People celebrate by playing with colored powder (abir), singing Rabindra Sangeet, and dancing to welcome the new season.',
    traditionsBn: [
      'শান্তিনিকেতনে রবীন্দ্রনাথ ঠাকুর বসন্ত উৎসবের প্রচলন করেন।',
      'রঙিন আবির দিয়ে সবাই একে অপরকে রাঙিয়ে দেয়।',
      'হলুদ ও কমলা রঙের পোশাক পরা এই উৎসবের বিশেষ রীতি।',
      'রবীন্দ্রসংগীত ও বসন্তের গান পরিবেশন করা হয়।',
    ],
    traditionsEn: [
      'Rabindranath Tagore initiated Basanta Utsav at Shantiniketan.',
      'People color each other with abir (colored powder).',
      'Wearing yellow and orange clothing is a special custom of this festival.',
      'Rabindra Sangeet and spring songs are performed.',
    ],
    quiz: [
      {
        id: 'basanta-utsav-1',
        prompt: 'What does বসন্ত mean?',
        promptBn: 'বসন্ত শব্দের ইংরেজি অর্থ কী?',
        options: ['Spring', 'Summer', 'Autumn', 'Winter'],
        correct: 0,
        explanation: 'বসন্ত (boshonto) = spring. বসন্ত উৎসব = spring festival.',
      },
      {
        id: 'basanta-utsav-2',
        prompt: 'What does উৎসব mean?',
        promptBn: 'উৎসব শব্দের অর্থ কী?',
        options: ['Festival/celebration', 'Ceremony', 'Ritual', 'Season'],
        correct: 0,
        explanation: 'উৎসব (utsob) = festival or celebration. বসন্ত উৎসব = spring festival.',
      },
      {
        id: 'basanta-utsav-3',
        prompt: 'What does আবির mean?',
        promptBn: 'আবির শব্দের ইংরেজি অর্থ কী?',
        options: ['Colored powder', 'Flower garland', 'Incense', 'Perfume'],
        correct: 0,
        explanation: 'আবির (abir) = colored powder used during বসন্ত উৎসব celebrations.',
      },
    ],
  },
];

export { FESTIVALS };
