/* ── folktales.js — Bengali folk tales data + quiz questions ──────────── */

const FOLKTALES = [
  // ─── 1. ঠাকুরমার ঝুলি ─────────────────────────────────
  {
    id: 'thakurmar-jhuli',
    bengaliName: 'ঠাকুরমার ঝুলি',
    englishName: 'Thakurmar Jhuli (Grandmother\'s Bag of Tales)',
    icon: '📖',
    tags: ['রূপকথা', 'Fairy Tales'],
    descBn: 'ঠাকুরমার ঝুলি বাংলা সাহিত্যের সবচেয়ে বিখ্যাত রূপকথার সংকলন। দক্ষিণারঞ্জন মিত্র মজুমদার এই গল্পগুলো সংগ্রহ করে ১৯০৭ সালে প্রকাশ করেন। ঠাকুরমা অর্থাৎ দিদিমা তাঁর নাতি-নাতনিদের এই গল্পগুলো শোনাতেন।',
    descEn: 'Thakurmar Jhuli is the most famous collection of Bengali fairy tales. Dakshinaranjan Mitra Majumdar compiled these oral folk tales and published them in 1907. The stories were traditionally told by grandmothers to their grandchildren at bedtime.',
    storyBn: [
      'ঠাকুরমা প্রতি সন্ধ্যায় নাতি-নাতনিদের গল্প শোনাতেন।',
      'তাঁর ঝুলিতে ছিল রাক্ষস, পরী, রাজকুমার আর জাদুর গল্প।',
      'দক্ষিণারঞ্জন গ্রামে গ্রামে ঘুরে এই গল্পগুলো সংগ্রহ করেন।',
      'এই বইটি বাংলা শিশুসাহিত্যের ভিত্তি হয়ে আছে।',
    ],
    storyEn: [
      'Every evening, grandmother would tell stories to her grandchildren.',
      'Her bag held tales of demons, fairies, princes, and magic.',
      'Dakshinaranjan traveled from village to village collecting these stories.',
      'This book remains the foundation of Bengali children\'s literature.',
    ],
    quiz: [
      {
        id: 'thakurmar-jhuli-1',
        prompt: 'What does ঠাকুরমা mean?',
        promptBn: 'ঠাকুরমা শব্দের ইংরেজি অর্থ কী?',
        options: ['Grandmother', 'Grandfather', 'Mother', 'Aunt'],
        correct: 0,
        explanation: 'ঠাকুরমা (thakurma) = grandmother (paternal). In Bengali families, ঠাকুরমা tells bedtime stories.',
      },
      {
        id: 'thakurmar-jhuli-2',
        prompt: 'What does ঝুলি mean?',
        promptBn: 'ঝুলি শব্দের অর্থ কী?',
        options: ['Bag/sack', 'Book', 'Box', 'Basket'],
        correct: 0,
        explanation: 'ঝুলি (jhuli) = bag or sack. ঠাকুরমার ঝুলি = grandmother\'s bag (of tales).',
      },
      {
        id: 'thakurmar-jhuli-3',
        prompt: 'What does রূপকথা mean?',
        promptBn: 'রূপকথা শব্দের ইংরেজি অর্থ কী?',
        options: ['Fairy tale', 'Novel', 'Poem', 'History'],
        correct: 0,
        explanation: 'রূপকথা (rupkotha) = fairy tale. রূপ (form/beauty) + কথা (story) = a tale of wonder.',
      },
    ],
  },

  // ─── 2. গোপাল ভাঁড় ────────────────────────────────────
  {
    id: 'gopal-bhar',
    bengaliName: 'গোপাল ভাঁড়',
    englishName: 'Gopal Bhar (Court Jester Tales)',
    icon: '🤡',
    tags: ['হাস্যরস', 'Humor'],
    descBn: 'গোপাল ভাঁড় ছিলেন রাজা কৃষ্ণচন্দ্রের রাজসভার বিখ্যাত বিদূষক। তাঁর চতুর বুদ্ধি ও হাস্যরসের গল্প বাংলায় অত্যন্ত জনপ্রিয়। তিনি রসিকতার মাধ্যমে সত্য ও ন্যায়ের কথা বলতেন।',
    descEn: 'Gopal Bhar was the legendary court jester of King Krishnachandra of Nadia. His tales of wit and humor are immensely popular in Bengal. Through clever jokes and satire, he spoke truth to power and championed justice.',
    storyBn: [
      'গোপাল ভাঁড় ছিলেন রাজা কৃষ্ণচন্দ্রের সভার প্রধান বিদূষক।',
      'তিনি চতুর বুদ্ধি দিয়ে জটিল সমস্যার সমাধান করতেন।',
      'রাজসভায় তাঁর রসিকতা সবাইকে মুগ্ধ করত।',
      'হাস্যরসের আড়ালে তিনি সামাজিক সত্য তুলে ধরতেন।',
    ],
    storyEn: [
      'Gopal Bhar was the chief jester in King Krishnachandra\'s court.',
      'He solved complex problems with his sharp wit.',
      'His humor in the royal court delighted everyone.',
      'Behind the laughter, he revealed social truths.',
    ],
    quiz: [
      {
        id: 'gopal-bhar-1',
        prompt: 'What does বিদূষক mean?',
        promptBn: 'বিদূষক শব্দের ইংরেজি অর্থ কী?',
        options: ['Jester/clown', 'King', 'Minister', 'Soldier'],
        correct: 0,
        explanation: 'বিদূষক (bidushok) = jester or clown. গোপাল ভাঁড় ছিলেন রাজসভার বিদূষক।',
      },
      {
        id: 'gopal-bhar-2',
        prompt: 'What does রাজসভা mean?',
        promptBn: 'রাজসভা শব্দের অর্থ কী?',
        options: ['Royal court', 'Marketplace', 'Temple', 'Battlefield'],
        correct: 0,
        explanation: 'রাজসভা (rajshobha) = royal court. রাজ (royal) + সভা (assembly/court).',
      },
      {
        id: 'gopal-bhar-3',
        prompt: 'What does হাস্যরস mean?',
        promptBn: 'হাস্যরস শব্দের ইংরেজি অর্থ কী?',
        options: ['Humor', 'Sadness', 'Anger', 'Mystery'],
        correct: 0,
        explanation: 'হাস্যরস (hashyoros) = humor. হাস্য (laughter) + রস (essence) = the essence of laughter.',
      },
    ],
  },

  // ─── 3. সাত ভাই চম্পা ──────────────────────────────────
  {
    id: 'sat-bhai-champa',
    bengaliName: 'সাত ভাই চম্পা',
    englishName: 'Sat Bhai Champa (Seven Brothers Champa)',
    icon: '🌸',
    tags: ['রূপকথা', 'Fairy Tales'],
    descBn: 'সাত ভাই চম্পা বাংলার একটি অতি পরিচিত রূপকথা। এক রানীর সাত ছেলে ও এক মেয়ে পারুলকে নিয়ে এই গল্প। ষড়যন্ত্রে সাত ভাই চম্পা ফুল আর বোন পারুল পাখি হয়ে যায়।',
    descEn: 'Sat Bhai Champa is one of the most beloved Bengali fairy tales. It tells the story of a queen\'s seven sons and one daughter, Parul. Through a conspiracy, the seven brothers are turned into champa flowers and the sister becomes a parul bird.',
    storyBn: [
      'এক রাজার সাত ছেলে ও এক মেয়ে পারুল ছিল।',
      'সৎ মায়ের ষড়যন্ত্রে সাত ভাই চম্পা ফুলে পরিণত হয়।',
      'বোন পারুল পাখি হয়ে ভাইদের খোঁজে বের হয়।',
      'শেষে সত্যের জয় হয় এবং সবাই মানুষের রূপ ফিরে পায়।',
    ],
    storyEn: [
      'A king had seven sons and one daughter named Parul.',
      'Through the stepmother\'s conspiracy, the seven brothers turned into champa flowers.',
      'Sister Parul became a bird and set out to find her brothers.',
      'In the end, truth prevailed and everyone regained their human form.',
    ],
    quiz: [
      {
        id: 'sat-bhai-champa-1',
        prompt: 'What does ভাই mean?',
        promptBn: 'ভাই শব্দের ইংরেজি অর্থ কী?',
        options: ['Brother', 'Sister', 'Friend', 'Son'],
        correct: 0,
        explanation: 'ভাই (bhai) = brother. সাত ভাই = seven brothers.',
      },
      {
        id: 'sat-bhai-champa-2',
        prompt: 'What does ষড়যন্ত্র mean?',
        promptBn: 'ষড়যন্ত্র শব্দের অর্থ কী?',
        options: ['Conspiracy', 'Blessing', 'Celebration', 'Journey'],
        correct: 0,
        explanation: 'ষড়যন্ত্র (shorojonro) = conspiracy or plot. The stepmother\'s ষড়যন্ত্র drives the story.',
      },
      {
        id: 'sat-bhai-champa-3',
        prompt: 'What does ফুল mean?',
        promptBn: 'ফুল শব্দের ইংরেজি অর্থ কী?',
        options: ['Flower', 'Fruit', 'Leaf', 'Tree'],
        correct: 0,
        explanation: 'ফুল (phul) = flower. চম্পা ফুল (champa flower) is a fragrant golden flower in Bengal.',
      },
    ],
  },

  // ─── 4. লালকমল নীলকমল ─────────────────────────────────
  {
    id: 'lalkamol-neelkamol',
    bengaliName: 'লালকমল নীলকমল',
    englishName: 'Lalkamol Neelkamol (Red Lotus Blue Lotus)',
    icon: '🪷',
    tags: ['রূপকথা', 'Adventure'],
    descBn: 'লালকমল ও নীলকমল দুই সৎ ভাই। সৎ মায়ের অত্যাচারে তারা বনে পালিয়ে যায়। রাক্ষসীর হাত থেকে বাঁচতে তাদের সাহস ও বুদ্ধি দিয়ে লড়াই করতে হয়। এটি ঠাকুরমার ঝুলির অন্যতম বিখ্যাত গল্প।',
    descEn: 'Lalkamol and Neelkamol are two stepbrothers. Persecuted by their stepmother, they flee into the forest. They must use courage and wit to survive against a demoness. This is one of the most famous stories from Thakurmar Jhuli.',
    storyBn: [
      'লালকমল ও নীলকমল দুই সৎ ভাই ছিল।',
      'সৎ মায়ের অত্যাচারে তারা গভীর বনে পালিয়ে যায়।',
      'বনে তারা ভয়ংকর রাক্ষসীর মুখোমুখি হয়।',
      'সাহস ও বুদ্ধি দিয়ে তারা রাক্ষসীকে পরাজিত করে ঘরে ফেরে।',
    ],
    storyEn: [
      'Lalkamol and Neelkamol were two stepbrothers.',
      'They fled deep into the forest to escape their stepmother\'s cruelty.',
      'In the forest, they encountered a terrifying demoness.',
      'With courage and wit, they defeated the demoness and returned home.',
    ],
    quiz: [
      {
        id: 'lalkamol-neelkamol-1',
        prompt: 'What does কমল mean?',
        promptBn: 'কমল শব্দের ইংরেজি অর্থ কী?',
        options: ['Lotus', 'Rose', 'Lily', 'Sunflower'],
        correct: 0,
        explanation: 'কমল (komol) = lotus. লালকমল = red lotus, নীলকমল = blue lotus.',
      },
      {
        id: 'lalkamol-neelkamol-2',
        prompt: 'What does রাক্ষসী mean?',
        promptBn: 'রাক্ষসী শব্দের অর্থ কী?',
        options: ['Demoness', 'Queen', 'Fairy', 'Witch'],
        correct: 0,
        explanation: 'রাক্ষসী (rakkhoshi) = demoness (female demon). রাক্ষস (rakkhosh) = male demon.',
      },
      {
        id: 'lalkamol-neelkamol-3',
        prompt: 'What does বন mean?',
        promptBn: 'বন শব্দের ইংরেজি অর্থ কী?',
        options: ['Forest', 'Garden', 'Field', 'Mountain'],
        correct: 0,
        explanation: 'বন (bon) = forest or jungle. গভীর বন = deep forest.',
      },
    ],
  },

  // ─── 5. কিরণমালা ───────────────────────────────────────
  {
    id: 'kiranmala',
    bengaliName: 'কিরণমালা',
    englishName: 'Kiranmala (Princess Kiranmala)',
    icon: '👸',
    tags: ['রূপকথা', 'Adventure'],
    descBn: 'কিরণমালা বাংলা রূপকথার সবচেয়ে সাহসী নায়িকা। তিনি তাঁর দুই ভাই অরুণ ও বরুণকে উদ্ধার করতে রাক্ষসের রাজ্যে যান। জাদু তলোয়ার ও অদম্য সাহস নিয়ে তিনি সমস্ত বিপদ জয় করেন।',
    descEn: 'Kiranmala is the bravest heroine in Bengali fairy tales. She ventures into the demon kingdom to rescue her two brothers, Arun and Barun. Armed with a magic sword and indomitable courage, she overcomes every danger.',
    storyBn: [
      'কিরণমালা ছিলেন এক সাহসী রাজকন্যা।',
      'তাঁর দুই ভাই অরুণ ও বরুণকে রাক্ষস অপহরণ করে।',
      'জাদু তলোয়ার নিয়ে তিনি রাক্ষসের রাজ্যে পাড়ি দেন।',
      'অসীম সাহসে তিনি ভাইদের উদ্ধার করে রাজ্যে ফেরেন।',
    ],
    storyEn: [
      'Kiranmala was a brave princess.',
      'A demon kidnapped her two brothers, Arun and Barun.',
      'She set out for the demon kingdom with a magic sword.',
      'With immense courage, she rescued her brothers and returned to the kingdom.',
    ],
    quiz: [
      {
        id: 'kiranmala-1',
        prompt: 'What does রাজকন্যা mean?',
        promptBn: 'রাজকন্যা শব্দের ইংরেজি অর্থ কী?',
        options: ['Princess', 'Queen', 'Goddess', 'Maiden'],
        correct: 0,
        explanation: 'রাজকন্যা (rajkonya) = princess. রাজ (royal) + কন্যা (daughter) = king\'s daughter.',
      },
      {
        id: 'kiranmala-2',
        prompt: 'What does তলোয়ার mean?',
        promptBn: 'তলোয়ার শব্দের অর্থ কী?',
        options: ['Sword', 'Shield', 'Arrow', 'Spear'],
        correct: 0,
        explanation: 'তলোয়ার (toloar) = sword. জাদু তলোয়ার = magic sword.',
      },
      {
        id: 'kiranmala-3',
        prompt: 'What does উদ্ধার mean?',
        promptBn: 'উদ্ধার শব্দের ইংরেজি অর্থ কী?',
        options: ['Rescue', 'Capture', 'Defeat', 'Escape'],
        correct: 0,
        explanation: 'উদ্ধার (uddhar) = rescue or salvation. কিরণমালা ভাইদের উদ্ধার করেন = Kiranmala rescued her brothers.',
      },
    ],
  },

  // ─── 6. পঞ্চতন্ত্র ────────────────────────────────────
  {
    id: 'panchatantra',
    bengaliName: 'পঞ্চতন্ত্র',
    englishName: 'Panchatantra (Animal Fables)',
    icon: '🦊',
    tags: ['নীতিকথা', 'Fables'],
    descBn: 'পঞ্চতন্ত্র প্রাচীন ভারতের বিখ্যাত পশু-নীতিকথার সংকলন। বিষ্ণুশর্মা এই গল্পগুলো তিন অজ্ঞ রাজপুত্রকে শিক্ষা দিতে রচনা করেন। পশুপাখির মাধ্যমে জীবনের গুরুত্বপূর্ণ শিক্ষা দেওয়া হয়েছে।',
    descEn: 'Panchatantra is a famous ancient Indian collection of animal fables. Vishnu Sharma composed these stories to educate three ignorant princes. Through animal characters, the tales teach essential life lessons about wisdom, friendship, and strategy.',
    storyBn: [
      'বিষ্ণুশর্মা তিন রাজপুত্রকে জীবনের শিক্ষা দিতে চেয়েছিলেন।',
      'তিনি পশুপাখির গল্পের মাধ্যমে নীতিকথা শেখালেন।',
      'শিয়াল, কাক, সিংহ, বানর — প্রতিটি প্রাণী একটি শিক্ষা বহন করে।',
      'পাঁচটি তন্ত্রে বিভক্ত এই বই বিশ্বসাহিত্যের অমূল্য সম্পদ।',
    ],
    storyEn: [
      'Vishnu Sharma wanted to educate three princes about life.',
      'He taught moral lessons through stories of animals and birds.',
      'Fox, crow, lion, monkey — each animal carries a lesson.',
      'Divided into five sections, this book is a priceless treasure of world literature.',
    ],
    quiz: [
      {
        id: 'panchatantra-1',
        prompt: 'What does নীতিকথা mean?',
        promptBn: 'নীতিকথা শব্দের ইংরেজি অর্থ কী?',
        options: ['Moral story/fable', 'Love story', 'Ghost story', 'Adventure story'],
        correct: 0,
        explanation: 'নীতিকথা (nitikotha) = moral story or fable. নীতি (moral) + কথা (story).',
      },
      {
        id: 'panchatantra-2',
        prompt: 'What does শিয়াল mean?',
        promptBn: 'শিয়াল শব্দের অর্থ কী?',
        options: ['Fox/jackal', 'Lion', 'Tiger', 'Wolf'],
        correct: 0,
        explanation: 'শিয়াল (shiyal) = fox or jackal. The শিয়াল is a clever trickster character in পঞ্চতন্ত্র.',
      },
      {
        id: 'panchatantra-3',
        prompt: 'What does পাঁচ mean in পঞ্চতন্ত্র?',
        promptBn: 'পঞ্চতন্ত্রে পঞ্চ শব্দের অর্থ কী?',
        options: ['Five', 'Three', 'Seven', 'Ten'],
        correct: 0,
        explanation: 'পঞ্চ (poncho) = five. পঞ্চতন্ত্র = five principles or five sections.',
      },
    ],
  },

  // ─── 7. হিতোপদেশ ───────────────────────────────────────
  {
    id: 'hitopadesha',
    bengaliName: 'হিতোপদেশ',
    englishName: 'Hitopadesha (Moral Stories)',
    icon: '📚',
    tags: ['নীতিকথা', 'Wisdom'],
    descBn: 'হিতোপদেশ প্রাচীন ভারতীয় নীতিশিক্ষামূলক গল্পের সংকলন। নারায়ণ পণ্ডিত এই গ্রন্থ রচনা করেন। পঞ্চতন্ত্রের অনুসরণে লেখা, এই গল্পগুলো বন্ধুত্ব, শত্রুতা এবং জীবনের ব্যবহারিক জ্ঞান শেখায়।',
    descEn: 'Hitopadesha is an ancient Indian collection of moral tales compiled by Narayana Pandit. Inspired by the Panchatantra, these stories teach about friendship, enmity, and practical life wisdom through engaging narratives of animals and humans.',
    storyBn: [
      'নারায়ণ পণ্ডিত রাজপুত্রদের শিক্ষিত করতে এই গল্প লেখেন।',
      'হিত মানে মঙ্গল, উপদেশ মানে পরামর্শ — মিলিয়ে হিতোপদেশ।',
      'বন্ধুলাভ, মিত্রভেদ, বিগ্রহ ও সন্ধি — চার ভাগে বিভক্ত।',
      'পশুপাখির গল্পে লুকিয়ে আছে গভীর জীবনদর্শন।',
    ],
    storyEn: [
      'Narayana Pandit wrote these stories to educate princes.',
      'Hita means welfare, upadesha means advice — together, Hitopadesha.',
      'It is divided into four parts: gaining friends, losing friends, war, and peace.',
      'Deep life philosophy is hidden within animal stories.',
    ],
    quiz: [
      {
        id: 'hitopadesha-1',
        prompt: 'What does উপদেশ mean?',
        promptBn: 'উপদেশ শব্দের ইংরেজি অর্থ কী?',
        options: ['Advice/moral teaching', 'Story', 'Song', 'Punishment'],
        correct: 0,
        explanation: 'উপদেশ (upodesh) = advice or moral teaching. হিত (welfare) + উপদেশ (advice) = beneficial advice.',
      },
      {
        id: 'hitopadesha-2',
        prompt: 'What does মিত্র mean?',
        promptBn: 'মিত্র শব্দের অর্থ কী?',
        options: ['Friend', 'Enemy', 'Teacher', 'Student'],
        correct: 0,
        explanation: 'মিত্র (mitro) = friend. মিত্রভেদ = separation or loss of friends.',
      },
      {
        id: 'hitopadesha-3',
        prompt: 'What does সন্ধি mean in the context of Hitopadesha?',
        promptBn: 'হিতোপদেশে সন্ধি শব্দের অর্থ কী?',
        options: ['Peace/treaty', 'War', 'Journey', 'Punishment'],
        correct: 0,
        explanation: 'সন্ধি (shondhi) = peace or treaty. বিগ্রহ (war) ও সন্ধি (peace) are two sections of হিতোপদেশ.',
      },
    ],
  },

  // ─── 8. বুদ্ধির খেলা ───────────────────────────────────
  {
    id: 'buddhir-khela',
    bengaliName: 'বুদ্ধির খেলা',
    englishName: 'Buddhir Khela (Wit Games)',
    icon: '🧠',
    tags: ['ধাঁধা', 'Riddles'],
    descBn: 'বুদ্ধির খেলা বাংলা লোককথার একটি জনপ্রিয় ধারা যেখানে চতুর চরিত্ররা বুদ্ধি দিয়ে সমস্যার সমাধান করে। ধাঁধা, ছড়া ও যুক্তির খেলা বাংলার গ্রামীণ সংস্কৃতির অবিচ্ছেদ্য অংশ।',
    descEn: 'Buddhir Khela is a popular tradition in Bengali folklore where clever characters solve problems through wit and intelligence. Riddles, rhymes, and logic games are an integral part of rural Bengali culture.',
    storyBn: [
      'বাংলায় বুদ্ধির খেলা মানে ধাঁধা ও চাতুর্যের গল্প।',
      'গ্রামের মানুষ সন্ধ্যায় একত্র হয়ে ধাঁধা জিজ্ঞেস করতেন।',
      'চতুর চাষী, বুদ্ধিমান বৌ — এসব চরিত্র গল্পে বারবার আসে।',
      'শক্তি নয়, বুদ্ধিই যে আসল অস্ত্র — এটাই এই গল্পের শিক্ষা।',
    ],
    storyEn: [
      'In Bengal, wit games mean stories of riddles and cleverness.',
      'Villagers would gather in the evening to ask each other riddles.',
      'Clever farmers and wise wives are recurring characters in these tales.',
      'The lesson is that intelligence, not strength, is the real weapon.',
    ],
    quiz: [
      {
        id: 'buddhir-khela-1',
        prompt: 'What does বুদ্ধি mean?',
        promptBn: 'বুদ্ধি শব্দের ইংরেজি অর্থ কী?',
        options: ['Intelligence/wit', 'Strength', 'Luck', 'Courage'],
        correct: 0,
        explanation: 'বুদ্ধি (buddhi) = intelligence or wit. বুদ্ধির খেলা = game of wits.',
      },
      {
        id: 'buddhir-khela-2',
        prompt: 'What does ধাঁধা mean?',
        promptBn: 'ধাঁধা শব্দের অর্থ কী?',
        options: ['Riddle/puzzle', 'Song', 'Poem', 'Story'],
        correct: 0,
        explanation: 'ধাঁধা (dhadha) = riddle or puzzle. Bengali folk culture is rich with ধাঁধা traditions.',
      },
      {
        id: 'buddhir-khela-3',
        prompt: 'What does চতুর mean?',
        promptBn: 'চতুর শব্দের ইংরেজি অর্থ কী?',
        options: ['Clever/shrewd', 'Foolish', 'Strong', 'Lazy'],
        correct: 0,
        explanation: 'চতুর (chotur) = clever or shrewd. চতুর চাষী = clever farmer.',
      },
    ],
  },

  // ─── 9. শকুন্তলা ───────────────────────────────────────
  {
    id: 'shakuntala',
    bengaliName: 'শকুন্তলা',
    englishName: 'Shakuntala (Classical Love Story)',
    icon: '💕',
    tags: ['প্রেমকাহিনি', 'Classical'],
    descBn: 'শকুন্তলা মহাকবি কালিদাসের অভিজ্ঞানশকুন্তলম নাটকের নায়িকা। বনে বেড়ে ওঠা শকুন্তলার সাথে রাজা দুষ্মন্তের প্রেমের এই কাহিনি বাংলা সাহিত্য ও সংস্কৃতিতে গভীর প্রভাব ফেলেছে।',
    descEn: 'Shakuntala is the heroine of Kalidasa\'s famous play Abhijnanashakuntalam. The love story between forest-raised Shakuntala and King Dushyanta has had a profound influence on Bengali literature and culture for centuries.',
    storyBn: [
      'শকুন্তলা ঋষি কণ্বের আশ্রমে বনের মধ্যে বড় হন।',
      'রাজা দুষ্মন্ত শিকারে এসে শকুন্তলার প্রেমে পড়েন।',
      'ঋষি দুর্বাসার অভিশাপে রাজা শকুন্তলাকে ভুলে যান।',
      'অবশেষে আংটি দেখে রাজার স্মৃতি ফিরে আসে এবং তাঁরা মিলিত হন।',
    ],
    storyEn: [
      'Shakuntala grew up in sage Kanva\'s ashram in the forest.',
      'King Dushyanta fell in love with Shakuntala while on a hunt.',
      'Due to sage Durvasa\'s curse, the king forgot Shakuntala.',
      'Finally, upon seeing the ring, the king\'s memory returned and they reunited.',
    ],
    quiz: [
      {
        id: 'shakuntala-1',
        prompt: 'What does প্রেম mean?',
        promptBn: 'প্রেম শব্দের ইংরেজি অর্থ কী?',
        options: ['Love', 'Hate', 'Friendship', 'Devotion'],
        correct: 0,
        explanation: 'প্রেম (prem) = love. প্রেমকাহিনি = love story.',
      },
      {
        id: 'shakuntala-2',
        prompt: 'What does অভিশাপ mean?',
        promptBn: 'অভিশাপ শব্দের অর্থ কী?',
        options: ['Curse', 'Blessing', 'Gift', 'Promise'],
        correct: 0,
        explanation: 'অভিশাপ (obhishap) = curse. ঋষি দুর্বাসার অভিশাপ = sage Durvasa\'s curse.',
      },
      {
        id: 'shakuntala-3',
        prompt: 'What does আশ্রম mean?',
        promptBn: 'আশ্রম শব্দের ইংরেজি অর্থ কী?',
        options: ['Hermitage/ashram', 'Palace', 'Temple', 'Village'],
        correct: 0,
        explanation: 'আশ্রম (ashrom) = hermitage or ashram, a secluded place for spiritual practice.',
      },
    ],
  },

  // ─── 10. ডালিমকুমার ────────────────────────────────────
  {
    id: 'dalimkumar',
    bengaliName: 'ডালিমকুমার',
    englishName: 'Dalimkumar (Prince Pomegranate)',
    icon: '🫐',
    tags: ['রূপকথা', 'Magic'],
    descBn: 'ডালিমকুমার বাংলার একটি জাদুময় রূপকথা। একটি ডালিম ফল থেকে জন্ম নেওয়া এই রাজকুমার অলৌকিক ক্ষমতার অধিকারী। রাক্ষস ও জাদুকরের বিরুদ্ধে লড়াই করে তিনি রাজকন্যাকে উদ্ধার করেন।',
    descEn: 'Dalimkumar is a magical Bengali fairy tale about a prince born from a pomegranate fruit who possesses supernatural powers. He battles demons and sorcerers to rescue a princess, making it one of the most enchanting tales from Thakurmar Jhuli.',
    storyBn: [
      'এক নিঃসন্তান রানীর কোলে ডালিম ফল থেকে জন্ম নেন ডালিমকুমার।',
      'তিনি অলৌকিক ক্ষমতা নিয়ে বড় হতে থাকেন।',
      'রাক্ষস এক রাজকন্যাকে বন্দি করলে ডালিমকুমার তাঁকে উদ্ধারে বের হন।',
      'জাদু ও সাহসের জোরে তিনি রাক্ষসকে পরাজিত করে রাজকন্যাকে মুক্ত করেন।',
    ],
    storyEn: [
      'Dalimkumar was born from a pomegranate fruit to a childless queen.',
      'He grew up possessing supernatural powers.',
      'When a demon imprisoned a princess, Dalimkumar set out to rescue her.',
      'With magic and courage, he defeated the demon and freed the princess.',
    ],
    quiz: [
      {
        id: 'dalimkumar-1',
        prompt: 'What does ডালিম mean?',
        promptBn: 'ডালিম শব্দের ইংরেজি অর্থ কী?',
        options: ['Pomegranate', 'Mango', 'Apple', 'Orange'],
        correct: 0,
        explanation: 'ডালিম (dalim) = pomegranate. ডালিমকুমার = Prince Pomegranate, born from a ডালিম ফল.',
      },
      {
        id: 'dalimkumar-2',
        prompt: 'What does রাজকুমার mean?',
        promptBn: 'রাজকুমার শব্দের অর্থ কী?',
        options: ['Prince', 'King', 'Warrior', 'Sage'],
        correct: 0,
        explanation: 'রাজকুমার (rajkumar) = prince. রাজ (royal) + কুমার (boy/son) = king\'s son.',
      },
      {
        id: 'dalimkumar-3',
        prompt: 'What does জাদু mean?',
        promptBn: 'জাদু শব্দের ইংরেজি অর্থ কী?',
        options: ['Magic', 'Strength', 'Luck', 'Skill'],
        correct: 0,
        explanation: 'জাদু (jadu) = magic. জাদুকর (jadukor) = magician or sorcerer.',
      },
    ],
  },
];

export { FOLKTALES };
