/* ── history.js — Bengali history data + quiz questions ──────────── */

const HISTORY = [
  // ─── 1. ভাষা আন্দোলন ──────────────────────────────────
  {
    id: 'language-movement',
    bengaliName: 'ভাষা আন্দোলন',
    englishName: 'Language Movement (1952)',
    icon: '🗣️',
    tags: ['আন্দোলন', 'Movement'],
    descBn: 'ভাষা আন্দোলন ছিল ১৯৫২ সালে পূর্ব পাকিস্তানে বাংলা ভাষাকে রাষ্ট্রভাষা হিসেবে স্বীকৃতি দেওয়ার দাবিতে একটি গণআন্দোলন। ২১শে ফেব্রুয়ারি পুলিশের গুলিতে সালাম, বরকত, রফিক, জব্বারসহ কয়েকজন শহিদ হন। এই দিনটি এখন আন্তর্জাতিক মাতৃভাষা দিবস হিসেবে পালিত হয়।',
    descEn: 'The Language Movement was a mass movement in 1952 in East Pakistan demanding recognition of Bengali as a state language. On February 21, police fired on protesters, and Salam, Barkat, Rafiq, Jabbar, and others were killed. This date is now observed globally as International Mother Language Day.',
    factsBn: [
      '২১শে ফেব্রুয়ারি ১৯৫২ সালে ভাষা শহিদরা প্রাণ দেন।',
      'ইউনেস্কো ১৯৯৯ সালে ২১শে ফেব্রুয়ারিকে আন্তর্জাতিক মাতৃভাষা দিবস ঘোষণা করে।',
      'ঢাকায় শহিদ মিনার ভাষা শহিদদের স্মরণে নির্মিত।',
      'ভাষা আন্দোলন পরবর্তীকালে বাংলাদেশের স্বাধীনতা আন্দোলনের অনুপ্রেরণা হয়ে ওঠে।',
    ],
    factsEn: [
      'Language martyrs sacrificed their lives on February 21, 1952.',
      'UNESCO declared February 21 as International Mother Language Day in 1999.',
      'The Shaheed Minar in Dhaka was built to honor the language martyrs.',
      'The Language Movement later inspired the independence movement of Bangladesh.',
    ],
    quiz: [
      {
        id: 'language-movement-1',
        prompt: 'What does ভাষা mean?',
        promptBn: 'ভাষা শব্দের ইংরেজি অর্থ কী?',
        options: ['Language', 'Country', 'People', 'History'],
        correct: 0,
        explanation: 'ভাষা (bhasha) = language. ভাষা আন্দোলন = Language Movement.',
      },
      {
        id: 'language-movement-2',
        prompt: 'What does শহিদ mean?',
        promptBn: 'শহিদ শব্দের অর্থ কী?',
        options: ['Martyr', 'Soldier', 'Leader', 'Hero'],
        correct: 0,
        explanation: 'শহিদ (shohid) = martyr. শহিদ মিনার = Martyr Monument.',
      },
      {
        id: 'language-movement-3',
        prompt: 'What does মাতৃভাষা mean?',
        promptBn: 'মাতৃভাষা শব্দের অর্থ কী?',
        options: ['Mother language', 'Foreign language', 'State language', 'Ancient language'],
        correct: 0,
        explanation: 'মাতৃভাষা (matribhasha) = mother language. মাতৃ (mother) + ভাষা (language).',
      },
    ],
  },

  // ─── 2. মুক্তিযুদ্ধ ────────────────────────────────────
  {
    id: 'liberation-war',
    bengaliName: 'মুক্তিযুদ্ধ',
    englishName: 'Liberation War (1971)',
    icon: '🇧🇩',
    tags: ['যুদ্ধ', 'War'],
    descBn: 'মুক্তিযুদ্ধ ছিল ১৯৭১ সালে বাংলাদেশের স্বাধীনতার জন্য পাকিস্তানের বিরুদ্ধে সশস্ত্র সংগ্রাম। নয় মাসের রক্তক্ষয়ী যুদ্ধে প্রায় ত্রিশ লক্ষ মানুষ শহিদ হন। ১৬ই ডিসেম্বর ১৯৭১ সালে পাকিস্তান সেনাবাহিনীর আত্মসমর্পণের মধ্য দিয়ে বাংলাদেশ স্বাধীনতা লাভ করে।',
    descEn: 'The Liberation War was the armed struggle in 1971 for the independence of Bangladesh from Pakistan. In nine months of conflict, approximately three million people lost their lives. On December 16, 1971, the Pakistani military surrendered, and Bangladesh achieved independence.',
    factsBn: [
      '১৯৭১ সালের ২৬শে মার্চ স্বাধীনতা ঘোষণা করা হয়।',
      'নয় মাসের যুদ্ধে প্রায় ত্রিশ লক্ষ মানুষ শহিদ হন।',
      '১৬ই ডিসেম্বর বিজয় দিবস হিসেবে পালিত হয়।',
      'মুক্তিবাহিনী ও মিত্রবাহিনী একসাথে যুদ্ধ করে।',
    ],
    factsEn: [
      'Independence was declared on March 26, 1971.',
      'Approximately three million people were killed in the nine-month war.',
      'December 16 is celebrated as Victory Day.',
      'The Mukti Bahini and allied forces fought together.',
    ],
    quiz: [
      {
        id: 'liberation-war-1',
        prompt: 'What does মুক্তি mean?',
        promptBn: 'মুক্তি শব্দের ইংরেজি অর্থ কী?',
        options: ['Liberation/freedom', 'War', 'Victory', 'Struggle'],
        correct: 0,
        explanation: 'মুক্তি (mukti) = liberation or freedom. মুক্তিযুদ্ধ = Liberation War.',
      },
      {
        id: 'liberation-war-2',
        prompt: 'What does স্বাধীনতা mean?',
        promptBn: 'স্বাধীনতা শব্দের অর্থ কী?',
        options: ['Independence', 'Democracy', 'Republic', 'Unity'],
        correct: 0,
        explanation: 'স্বাধীনতা (shadhinota) = independence. ২৬শে মার্চ স্বাধীনতা দিবস।',
      },
      {
        id: 'liberation-war-3',
        prompt: 'What does বিজয় mean?',
        promptBn: 'বিজয় শব্দের ইংরেজি অর্থ কী?',
        options: ['Victory', 'Defeat', 'Surrender', 'Battle'],
        correct: 0,
        explanation: 'বিজয় (bijoy) = victory. ১৬ই ডিসেম্বর বিজয় দিবস = Victory Day.',
      },
    ],
  },

  // ─── 3. রবীন্দ্রনাথ ঠাকুর ─────────────────────────────
  {
    id: 'rabindranath-tagore',
    bengaliName: 'রবীন্দ্রনাথ ঠাকুর',
    englishName: 'Rabindranath Tagore',
    icon: '✒️',
    tags: ['সাহিত্য', 'Literature'],
    descBn: 'রবীন্দ্রনাথ ঠাকুর বাংলা সাহিত্যের সর্বশ্রেষ্ঠ কবি এবং ১৯১৩ সালে সাহিত্যে নোবেল পুরস্কার বিজয়ী। তিনি "গীতাঞ্জলি" কাব্যগ্রন্থের জন্য এশিয়া থেকে প্রথম নোবেল পুরস্কার পান। তাঁর রচিত "আমার সোনার বাংলা" বাংলাদেশের জাতীয় সংগীত।',
    descEn: 'Rabindranath Tagore is the greatest poet of Bengali literature and the 1913 Nobel Prize laureate in Literature. He was the first Asian to receive the Nobel Prize, for his poetry collection "Gitanjali." His song "Amar Shonar Bangla" is the national anthem of Bangladesh.',
    factsBn: [
      '১৯১৩ সালে "গীতাঞ্জলি"-র জন্য তিনি নোবেল পুরস্কার পান।',
      'তিনি এশিয়া থেকে প্রথম নোবেল বিজয়ী।',
      '"আমার সোনার বাংলা" বাংলাদেশের জাতীয় সংগীত।',
      'তিনি শান্তিনিকেতনে বিশ্বভারতী বিশ্ববিদ্যালয় প্রতিষ্ঠা করেন।',
    ],
    factsEn: [
      'He received the Nobel Prize in 1913 for "Gitanjali."',
      'He was the first Nobel laureate from Asia.',
      '"Amar Shonar Bangla" is the national anthem of Bangladesh.',
      'He founded Visva-Bharati University at Santiniketan.',
    ],
    quiz: [
      {
        id: 'rabindranath-tagore-1',
        prompt: 'What does কবি mean?',
        promptBn: 'কবি শব্দের ইংরেজি অর্থ কী?',
        options: ['Poet', 'Writer', 'Singer', 'Painter'],
        correct: 0,
        explanation: 'কবি (kobi) = poet. রবীন্দ্রনাথকে "বিশ্বকবি" বলা হয় = world poet.',
      },
      {
        id: 'rabindranath-tagore-2',
        prompt: 'What does সাহিত্য mean?',
        promptBn: 'সাহিত্য শব্দের অর্থ কী?',
        options: ['Literature', 'Science', 'History', 'Philosophy'],
        correct: 0,
        explanation: 'সাহিত্য (shahitto) = literature. নোবেল পুরস্কার সাহিত্যে দেওয়া হয়।',
      },
      {
        id: 'rabindranath-tagore-3',
        prompt: 'What does জাতীয় সংগীত mean?',
        promptBn: 'জাতীয় সংগীত-এর অর্থ কী?',
        options: ['National anthem', 'Folk song', 'Patriotic poem', 'Classical music'],
        correct: 0,
        explanation: 'জাতীয় সংগীত (jatiyo shongit) = national anthem. জাতীয় (national) + সংগীত (song).',
      },
    ],
  },

  // ─── 4. কাজী নজরুল ইসলাম ──────────────────────────────
  {
    id: 'kazi-nazrul-islam',
    bengaliName: 'কাজী নজরুল ইসলাম',
    englishName: 'Kazi Nazrul Islam',
    icon: '✊',
    tags: ['কবিতা', 'Poetry'],
    descBn: 'কাজী নজরুল ইসলাম বাংলাদেশের জাতীয় কবি এবং "বিদ্রোহী কবি" হিসেবে পরিচিত। তাঁর "বিদ্রোহী" কবিতা ব্রিটিশ ঔপনিবেশিক শাসনের বিরুদ্ধে প্রতিবাদের প্রতীক হয়ে ওঠে। তিনি কবিতা, গান, নাটক ও প্রবন্ধ রচনা করেন।',
    descEn: 'Kazi Nazrul Islam is the national poet of Bangladesh, known as the "Rebel Poet." His poem "Bidrohi" (The Rebel) became a symbol of protest against British colonial rule. He was a prolific writer of poetry, songs, plays, and essays.',
    factsBn: [
      'তিনি বাংলাদেশের জাতীয় কবি।',
      '"বিদ্রোহী" কবিতা তাঁর সবচেয়ে বিখ্যাত রচনা।',
      'তিনি প্রায় চার হাজার গান রচনা করেন, যা "নজরুলগীতি" নামে পরিচিত।',
      'ব্রিটিশ শাসনের বিরুদ্ধে লেখার জন্য তাঁকে কারাবরণ করতে হয়।',
    ],
    factsEn: [
      'He is the national poet of Bangladesh.',
      '"Bidrohi" (The Rebel) is his most famous work.',
      'He composed about four thousand songs, known as "Nazrul Geeti."',
      'He was imprisoned for his writings against British rule.',
    ],
    quiz: [
      {
        id: 'kazi-nazrul-islam-1',
        prompt: 'What does বিদ্রোহী mean?',
        promptBn: 'বিদ্রোহী শব্দের ইংরেজি অর্থ কী?',
        options: ['Rebel', 'Patriot', 'Soldier', 'Scholar'],
        correct: 0,
        explanation: 'বিদ্রোহী (bidrohi) = rebel. নজরুলকে "বিদ্রোহী কবি" বলা হয়।',
      },
      {
        id: 'kazi-nazrul-islam-2',
        prompt: 'What does জাতীয় কবি mean?',
        promptBn: 'জাতীয় কবি-র অর্থ কী?',
        options: ['National poet', 'Famous poet', 'Classical poet', 'Romantic poet'],
        correct: 0,
        explanation: 'জাতীয় কবি (jatiyo kobi) = national poet. জাতীয় (national) + কবি (poet).',
      },
      {
        id: 'kazi-nazrul-islam-3',
        prompt: 'What does কারাবরণ mean?',
        promptBn: 'কারাবরণ শব্দের অর্থ কী?',
        options: ['Imprisonment', 'Exile', 'Punishment', 'Trial'],
        correct: 0,
        explanation: 'কারাবরণ (karaboron) = imprisonment. কারা (prison) + বরণ (accepting).',
      },
    ],
  },

  // ─── 5. বঙ্গভঙ্গ ───────────────────────────────────────
  {
    id: 'partition-of-bengal',
    bengaliName: 'বঙ্গভঙ্গ',
    englishName: 'Partition of Bengal (1905)',
    icon: '📜',
    tags: ['ঔপনিবেশিক', 'Colonial'],
    descBn: 'বঙ্গভঙ্গ ছিল ১৯০৫ সালে ব্রিটিশ ভারতের বাংলা প্রদেশকে দুই ভাগে বিভক্ত করার সিদ্ধান্ত। লর্ড কার্জন এই বিভাজন ঘোষণা করেন। ব্যাপক প্রতিবাদ ও স্বদেশি আন্দোলনের ফলে ১৯১১ সালে বঙ্গভঙ্গ রদ করা হয়।',
    descEn: 'The Partition of Bengal in 1905 was the British decision to divide the Bengal province into two parts. Lord Curzon announced this partition. Due to widespread protests and the Swadeshi Movement, the partition was annulled in 1911.',
    factsBn: [
      '১৯০৫ সালে লর্ড কার্জন বঙ্গভঙ্গ ঘোষণা করেন।',
      'বঙ্গভঙ্গ বিরোধী স্বদেশি আন্দোলন গড়ে ওঠে।',
      '১৯১১ সালে বঙ্গভঙ্গ রদ হয়।',
      'এই ঘটনা ভারতীয় জাতীয়তাবাদী আন্দোলনকে শক্তিশালী করে।',
    ],
    factsEn: [
      'Lord Curzon announced the Partition of Bengal in 1905.',
      'The Swadeshi Movement arose in opposition to the partition.',
      'The partition was annulled in 1911.',
      'This event strengthened the Indian nationalist movement.',
    ],
    quiz: [
      {
        id: 'partition-of-bengal-1',
        prompt: 'What does বঙ্গ mean?',
        promptBn: 'বঙ্গ শব্দের ইংরেজি অর্থ কী?',
        options: ['Bengal', 'India', 'Pakistan', 'Province'],
        correct: 0,
        explanation: 'বঙ্গ (bongo) = Bengal. বঙ্গভঙ্গ = Partition of Bengal.',
      },
      {
        id: 'partition-of-bengal-2',
        prompt: 'What does স্বদেশি mean?',
        promptBn: 'স্বদেশি শব্দের অর্থ কী?',
        options: ['Of one\'s own country', 'Foreign', 'Colonial', 'Modern'],
        correct: 0,
        explanation: 'স্বদেশি (swodeshi) = of one\'s own country. স্ব (own) + দেশ (country) + ই (suffix).',
      },
      {
        id: 'partition-of-bengal-3',
        prompt: 'What does ভঙ্গ mean?',
        promptBn: 'ভঙ্গ শব্দের অর্থ কী?',
        options: ['Division/partition', 'Union', 'Creation', 'Election'],
        correct: 0,
        explanation: 'ভঙ্গ (bhongo) = division or partition. বঙ্গভঙ্গ = division of Bengal.',
      },
    ],
  },

  // ─── 6. পলাশীর যুদ্ধ ───────────────────────────────────
  {
    id: 'battle-of-plassey',
    bengaliName: 'পলাশীর যুদ্ধ',
    englishName: 'Battle of Plassey (1757)',
    icon: '⚔️',
    tags: ['যুদ্ধ', 'Battle'],
    descBn: 'পলাশীর যুদ্ধ ১৭৫৭ সালের ২৩শে জুন পলাশীতে সংঘটিত হয়। এই যুদ্ধে ব্রিটিশ ইস্ট ইন্ডিয়া কোম্পানি নবাব সিরাজউদ্দৌলাকে পরাজিত করে। মীরজাফরের বিশ্বাসঘাতকতা এই পরাজয়ের অন্যতম কারণ ছিল। এই যুদ্ধের ফলে ভারতে ব্রিটিশ শাসনের সূচনা হয়।',
    descEn: 'The Battle of Plassey took place on June 23, 1757, at Plassey. The British East India Company defeated Nawab Sirajuddaula in this battle. The betrayal by Mir Jafar was a key factor in the defeat. This battle marked the beginning of British rule in India.',
    factsBn: [
      '১৭৫৭ সালের ২৩শে জুন পলাশীর যুদ্ধ হয়।',
      'নবাব সিরাজউদ্দৌলা ব্রিটিশদের কাছে পরাজিত হন।',
      'মীরজাফরের বিশ্বাসঘাতকতা পরাজয়ের মূল কারণ।',
      'এই যুদ্ধ ভারতে ব্রিটিশ ঔপনিবেশিক শাসনের সূত্রপাত ঘটায়।',
    ],
    factsEn: [
      'The Battle of Plassey was fought on June 23, 1757.',
      'Nawab Sirajuddaula was defeated by the British.',
      'Mir Jafar\'s betrayal was a key cause of the defeat.',
      'This battle initiated British colonial rule in India.',
    ],
    quiz: [
      {
        id: 'battle-of-plassey-1',
        prompt: 'What does যুদ্ধ mean?',
        promptBn: 'যুদ্ধ শব্দের ইংরেজি অর্থ কী?',
        options: ['War/battle', 'Peace', 'Treaty', 'Victory'],
        correct: 0,
        explanation: 'যুদ্ধ (juddho) = war or battle. পলাশীর যুদ্ধ = Battle of Plassey.',
      },
      {
        id: 'battle-of-plassey-2',
        prompt: 'What does নবাব mean?',
        promptBn: 'নবাব শব্দের অর্থ কী?',
        options: ['Ruler/nawab', 'Soldier', 'Merchant', 'Priest'],
        correct: 0,
        explanation: 'নবাব (nobab) = ruler or nawab. সিরাজউদ্দৌলা বাংলার শেষ স্বাধীন নবাব।',
      },
      {
        id: 'battle-of-plassey-3',
        prompt: 'What does বিশ্বাসঘাতকতা mean?',
        promptBn: 'বিশ্বাসঘাতকতা শব্দের অর্থ কী?',
        options: ['Betrayal', 'Bravery', 'Loyalty', 'Sacrifice'],
        correct: 0,
        explanation: 'বিশ্বাসঘাতকতা (bishwasghatakata) = betrayal. বিশ্বাস (trust) + ঘাতক (destroyer).',
      },
    ],
  },

  // ─── 7. সুভাষচন্দ্র বসু ───────────────────────────────
  {
    id: 'subhas-chandra-bose',
    bengaliName: 'সুভাষচন্দ্র বসু',
    englishName: 'Subhas Chandra Bose',
    icon: '🏴',
    tags: ['স্বাধীনতা', 'Independence'],
    descBn: 'সুভাষচন্দ্র বসু ছিলেন ভারতের স্বাধীনতা আন্দোলনের একজন প্রখ্যাত নেতা। তিনি "নেতাজি" নামে পরিচিত ছিলেন। তিনি আজাদ হিন্দ ফৌজ গঠন করে ব্রিটিশ শাসনের বিরুদ্ধে সশস্ত্র সংগ্রামের নেতৃত্ব দেন।',
    descEn: 'Subhas Chandra Bose was a prominent leader of the Indian independence movement. Known as "Netaji," he formed the Indian National Army (Azad Hind Fauj) and led an armed struggle against British rule. Born in Cuttack, he had deep connections to Bengali culture and politics.',
    factsBn: [
      'তিনি "নেতাজি" উপাধিতে সমধিক পরিচিত।',
      'তিনি আজাদ হিন্দ ফৌজ (ভারতীয় জাতীয় সেনাবাহিনী) গঠন করেন।',
      'তাঁর বিখ্যাত স্লোগান ছিল "তোমরা আমাকে রক্ত দাও, আমি তোমাদের স্বাধীনতা দেব।"',
      'তিনি ইন্ডিয়ান ন্যাশনাল কংগ্রেসের সভাপতি নির্বাচিত হয়েছিলেন।',
    ],
    factsEn: [
      'He was widely known by the title "Netaji."',
      'He formed the Azad Hind Fauj (Indian National Army).',
      'His famous slogan was "Give me blood, and I shall give you freedom."',
      'He was elected president of the Indian National Congress.',
    ],
    quiz: [
      {
        id: 'subhas-chandra-bose-1',
        prompt: 'What does নেতাজি mean?',
        promptBn: 'নেতাজি শব্দের অর্থ কী?',
        options: ['Respected leader', 'Great warrior', 'Freedom fighter', 'National hero'],
        correct: 0,
        explanation: 'নেতাজি (netaji) = respected leader. নেতা (leader) + জি (honorific suffix).',
      },
      {
        id: 'subhas-chandra-bose-2',
        prompt: 'What does রক্ত mean?',
        promptBn: 'রক্ত শব্দের ইংরেজি অর্থ কী?',
        options: ['Blood', 'Sweat', 'Tears', 'Strength'],
        correct: 0,
        explanation: 'রক্ত (rokto) = blood. "তোমরা আমাকে রক্ত দাও" = Give me blood.',
      },
      {
        id: 'subhas-chandra-bose-3',
        prompt: 'What does ফৌজ mean?',
        promptBn: 'ফৌজ শব্দের অর্থ কী?',
        options: ['Army', 'Navy', 'Government', 'Parliament'],
        correct: 0,
        explanation: 'ফৌজ (fouj) = army. আজাদ হিন্দ ফৌজ = Free India Army.',
      },
    ],
  },

  // ─── 8. বেগম রোকেয়া ───────────────────────────────────
  {
    id: 'begum-rokeya',
    bengaliName: 'বেগম রোকেয়া',
    englishName: 'Begum Rokeya',
    icon: '👩‍🏫',
    tags: ['নারী অধিকার', 'Women\'s Rights'],
    descBn: 'বেগম রোকেয়া সাখাওয়াত হোসেন ছিলেন বাংলার নারী জাগরণের অগ্রদূত। তিনি নারী শিক্ষার জন্য আজীবন লড়াই করেন এবং ১৯১১ সালে সাখাওয়াত মেমোরিয়াল স্কুল প্রতিষ্ঠা করেন। তাঁর রচিত "সুলতানার স্বপ্ন" নারীবাদী সাহিত্যের একটি অগ্রণী রচনা।',
    descEn: 'Begum Rokeya Sakhawat Hossain was a pioneer of women\'s awakening in Bengal. She fought for women\'s education throughout her life and founded the Sakhawat Memorial School in 1911. Her work "Sultana\'s Dream" is a pioneering piece of feminist literature.',
    factsBn: [
      'তিনি বাংলার নারী জাগরণের অগ্রদূত।',
      '১৯১১ সালে তিনি সাখাওয়াত মেমোরিয়াল স্কুল প্রতিষ্ঠা করেন।',
      '"সুলতানার স্বপ্ন" তাঁর বিখ্যাত ইংরেজি রচনা।',
      '৯ই ডিসেম্বর বাংলাদেশে "রোকেয়া দিবস" পালিত হয়।',
    ],
    factsEn: [
      'She was a pioneer of the women\'s awakening in Bengal.',
      'She founded the Sakhawat Memorial School in 1911.',
      '"Sultana\'s Dream" is her famous English-language work.',
      'December 9 is observed as "Rokeya Day" in Bangladesh.',
    ],
    quiz: [
      {
        id: 'begum-rokeya-1',
        prompt: 'What does নারী mean?',
        promptBn: 'নারী শব্দের ইংরেজি অর্থ কী?',
        options: ['Woman', 'Man', 'Child', 'Elder'],
        correct: 0,
        explanation: 'নারী (nari) = woman. নারী শিক্ষা = women\'s education.',
      },
      {
        id: 'begum-rokeya-2',
        prompt: 'What does শিক্ষা mean?',
        promptBn: 'শিক্ষা শব্দের অর্থ কী?',
        options: ['Education', 'Health', 'Wealth', 'Freedom'],
        correct: 0,
        explanation: 'শিক্ষা (shikkha) = education. বেগম রোকেয়া নারী শিক্ষার জন্য লড়াই করেন।',
      },
      {
        id: 'begum-rokeya-3',
        prompt: 'What does স্বপ্ন mean?',
        promptBn: 'স্বপ্ন শব্দের ইংরেজি অর্থ কী?',
        options: ['Dream', 'Story', 'Memory', 'Hope'],
        correct: 0,
        explanation: 'স্বপ্ন (shopno) = dream. "সুলতানার স্বপ্ন" = Sultana\'s Dream.',
      },
    ],
  },

  // ─── 9. শেখ মুজিবুর রহমান ─────────────────────────────
  {
    id: 'sheikh-mujibur-rahman',
    bengaliName: 'শেখ মুজিবুর রহমান',
    englishName: 'Sheikh Mujibur Rahman',
    icon: '🎤',
    tags: ['নেতৃত্ব', 'Leadership'],
    descBn: 'শেখ মুজিবুর রহমান বাংলাদেশের প্রতিষ্ঠাতা এবং প্রথম রাষ্ট্রপতি। তিনি "বঙ্গবন্ধু" উপাধিতে পরিচিত। ১৯৭১ সালে তাঁর নেতৃত্বে বাংলাদেশ স্বাধীনতা লাভ করে। তাঁর ৭ই মার্চের ভাষণ বিশ্বের অন্যতম প্রভাবশালী ভাষণ হিসেবে স্বীকৃত।',
    descEn: 'Sheikh Mujibur Rahman was the founding leader and first president of Bangladesh. Known as "Bangabandhu" (Friend of Bengal), he led the country to independence in 1971. His March 7 speech is recognized as one of the most influential speeches in world history.',
    factsBn: [
      'তিনি বাংলাদেশের প্রতিষ্ঠাতা ও প্রথম রাষ্ট্রপতি।',
      'তিনি "বঙ্গবন্ধু" উপাধিতে পরিচিত।',
      '৭ই মার্চের ভাষণ ইউনেস্কো কর্তৃক বিশ্ব প্রামাণ্য ঐতিহ্য হিসেবে স্বীকৃত।',
      '১৯৬৬ সালে তিনি ছয় দফা আন্দোলনের নেতৃত্ব দেন।',
    ],
    factsEn: [
      'He was the founding leader and first president of Bangladesh.',
      'He is known by the title "Bangabandhu" (Friend of Bengal).',
      'His March 7 speech is recognized by UNESCO as a documentary heritage.',
      'He led the Six-Point Movement in 1966.',
    ],
    quiz: [
      {
        id: 'sheikh-mujibur-rahman-1',
        prompt: 'What does বঙ্গবন্ধু mean?',
        promptBn: 'বঙ্গবন্ধু শব্দের অর্থ কী?',
        options: ['Friend of Bengal', 'King of Bengal', 'Hero of Bengal', 'Leader of Bengal'],
        correct: 0,
        explanation: 'বঙ্গবন্ধু (bongobondhu) = Friend of Bengal. বঙ্গ (Bengal) + বন্ধু (friend).',
      },
      {
        id: 'sheikh-mujibur-rahman-2',
        prompt: 'What does ভাষণ mean?',
        promptBn: 'ভাষণ শব্দের ইংরেজি অর্থ কী?',
        options: ['Speech', 'Letter', 'Article', 'Song'],
        correct: 0,
        explanation: 'ভাষণ (bhashon) = speech. ৭ই মার্চের ভাষণ = the March 7 speech.',
      },
      {
        id: 'sheikh-mujibur-rahman-3',
        prompt: 'What does রাষ্ট্রপতি mean?',
        promptBn: 'রাষ্ট্রপতি শব্দের অর্থ কী?',
        options: ['President', 'Prime minister', 'Governor', 'King'],
        correct: 0,
        explanation: 'রাষ্ট্রপতি (rashtropoti) = president. রাষ্ট্র (state) + পতি (head/lord).',
      },
    ],
  },

  // ─── 10. লালন ফকির ─────────────────────────────────────
  {
    id: 'lalon-fakir',
    bengaliName: 'লালন ফকির',
    englishName: 'Lalon Fakir',
    icon: '🎵',
    tags: ['সংগীত', 'Music'],
    descBn: 'লালন ফকির ছিলেন বাংলার সবচেয়ে প্রভাবশালী বাউল সাধক ও গীতিকার। তাঁর গানে মানবতা, সাম্প্রদায়িক সম্প্রীতি এবং আধ্যাত্মিকতার বাণী ফুটে ওঠে। তিনি জাতি, ধর্ম ও বর্ণের বিভেদের বিরুদ্ধে তাঁর গানের মাধ্যমে প্রতিবাদ করেন।',
    descEn: 'Lalon Fakir was the most influential Baul mystic and songwriter of Bengal. His songs convey messages of humanity, communal harmony, and spirituality. He protested against divisions of caste, religion, and creed through his songs.',
    factsBn: [
      'তিনি বাংলার সবচেয়ে পরিচিত বাউল সাধক।',
      'তাঁর গানে মানবতা ও সাম্প্রদায়িক সম্প্রীতির বাণী রয়েছে।',
      'তিনি কুষ্টিয়ার ছেঁউড়িয়ায় তাঁর আখড়া স্থাপন করেন।',
      'রবীন্দ্রনাথ ঠাকুর লালনের গান দ্বারা গভীরভাবে প্রভাবিত হয়েছিলেন।',
    ],
    factsEn: [
      'He is the most well-known Baul mystic of Bengal.',
      'His songs carry messages of humanity and communal harmony.',
      'He established his ashram at Cheuriya in Kushtia.',
      'Rabindranath Tagore was deeply influenced by Lalon\'s songs.',
    ],
    quiz: [
      {
        id: 'lalon-fakir-1',
        prompt: 'What does বাউল mean?',
        promptBn: 'বাউল শব্দের অর্থ কী?',
        options: ['Mystic minstrel', 'Classical singer', 'Folk dancer', 'Religious priest'],
        correct: 0,
        explanation: 'বাউল (baul) = mystic minstrel. বাউল সাধকরা গানের মাধ্যমে আধ্যাত্মিকতা প্রকাশ করেন।',
      },
      {
        id: 'lalon-fakir-2',
        prompt: 'What does মানবতা mean?',
        promptBn: 'মানবতা শব্দের ইংরেজি অর্থ কী?',
        options: ['Humanity', 'Religion', 'Tradition', 'Society'],
        correct: 0,
        explanation: 'মানবতা (manobota) = humanity. মানব (human) + তা (quality/suffix).',
      },
      {
        id: 'lalon-fakir-3',
        prompt: 'What does সম্প্রীতি mean?',
        promptBn: 'সম্প্রীতি শব্দের অর্থ কী?',
        options: ['Harmony', 'Conflict', 'Division', 'Debate'],
        correct: 0,
        explanation: 'সম্প্রীতি (shompriti) = harmony. সাম্প্রদায়িক সম্প্রীতি = communal harmony.',
      },
    ],
  },
];

export { HISTORY };
