/* ── movies.js — Bengali film data + quiz questions ──────────── */

const MOVIES = [
  // ─── 1. Pather Panchali ─────────────────────────────────────
  {
    id: 'pather-panchali',
    bengaliName: 'পথের পাঁচালী',
    englishName: 'Song of the Little Road',
    icon: '🎬',
    tags: ['ক্লাসিক', 'Drama'],
    director: 'Satyajit Ray',
    directorBn: 'সত্যজিৎ রায়',
    year: '1955',
    descBn: 'পথের পাঁচালী সত্যজিৎ রায়ের প্রথম চলচ্চিত্র এবং অপু ত্রয়ীর প্রথম পর্ব। গ্রামবাংলার দারিদ্র্যপীড়িত এক পরিবারের কাহিনি — ছোট্ট অপু ও তার দিদি দুর্গার চোখে দেখা জীবন। বিভূতিভূষণ বন্দ্যোপাধ্যায়ের উপন্যাস অবলম্বনে নির্মিত এই ছবি ১৯৫৬ সালে কান চলচ্চিত্র উৎসবে "Best Human Document" পুরস্কার পায়।',
    descEn: 'Pather Panchali is Satyajit Ray\'s debut film and the first installment of the famous Apu Trilogy. Set in rural Bengal, it follows the impoverished Roy family through the eyes of young Apu and his older sister Durga. Based on Bibhutibhushan Bandyopadhyay\'s novel, the film won the "Best Human Document" award at the 1956 Cannes Film Festival and launched Indian cinema onto the world stage.',
    dialogueBn: [
      'দুর্গা! ও দুর্গা! কোথায় গেলি?',
      'মা, আমি তো কিছু করিনি!',
      'অপু, তুই বাইরে যাবি না।',
      'দেখ, রেলগাড়ি যাচ্ছে!',
    ],
    dialogueEn: [
      'Durga! O Durga! Where have you gone?',
      'Ma, I didn\'t do anything!',
      'Apu, you won\'t go outside.',
      'Look, the train is going!',
    ],
    quiz: [
      {
        id: 'pather-panchali-1',
        prompt: 'What does পথ mean in "পথের পাঁচালী"?',
        promptBn: '"পথের পাঁচালী"-তে পথ শব্দের অর্থ কী?',
        options: ['Path/road', 'Song', 'Village', 'River'],
        correct: 0,
        explanation: 'পথ (poth) = path or road. পথের পাঁচালী literally means "Song of the Road."',
      },
      {
        id: 'pather-panchali-2',
        prompt: 'What does পরিচালক mean in Bengali film terminology?',
        promptBn: 'পরিচালক শব্দের অর্থ কী?',
        options: ['Director', 'Actor', 'Producer', 'Writer'],
        correct: 0,
        explanation: 'পরিচালক (porichalok) = director. সত্যজিৎ রায় ছিলেন এই ছবির পরিচালক।',
      },
      {
        id: 'pather-panchali-3',
        prompt: 'What historical achievement is Pather Panchali known for at Cannes?',
        promptBn: 'পথের পাঁচালী কান চলচ্চিত্র উৎসবে কী পুরস্কার পেয়েছিল?',
        options: ['Best Human Document award', 'Palme d\'Or', 'Best Actor award', 'Best Screenplay'],
        correct: 0,
        explanation: 'Pather Panchali won the "Best Human Document" award at the 1956 Cannes Film Festival, establishing Indian cinema internationally.',
      },
    ],
  },

  // ─── 2. Goopy Gyne Bagha Byne ──────────────────────────────
  {
    id: 'goopy-gyne-bagha-byne',
    bengaliName: 'গুপী গাইন বাঘা বাইন',
    englishName: 'The Adventures of Goopy and Bagha',
    icon: '🥁',
    tags: ['ফ্যান্টাসি', 'Comedy'],
    director: 'Satyajit Ray',
    directorBn: 'সত্যজিৎ রায়',
    year: '1969',
    descBn: 'গুপী গাইন বাঘা বাইন সত্যজিৎ রায়ের একটি কল্পনাশ্রয়ী চলচ্চিত্র। গায়ক গুপী ও ঢোলবাদক বাঘা ভূতের রাজার কাছ থেকে তিনটি বর পায় — যেকোনো খাবার পাওয়া, যেকোনো জায়গায় যাওয়া, এবং গান দিয়ে মানুষকে স্তব্ধ করার ক্ষমতা। এটি বাংলা সিনেমার সবচেয়ে জনপ্রিয় চলচ্চিত্রগুলোর একটি।',
    descEn: 'Goopy Gyne Bagha Byne is a beloved fantasy-comedy by Satyajit Ray, based on a story by his grandfather Upendrakishore Ray Chowdhury. Two hapless musicians — singer Goopy and drummer Bagha — receive three magical boons from the King of Ghosts. The film is one of the most popular Bengali films ever made, blending humor, music, and social commentary.',
    dialogueBn: [
      'মহারাজ, আমরা গান গাইতে চাই!',
      'ভূতের রাজা দিল বর — তিনটে!',
      'গুপী, তুই গা! বাঘা, তুই বাজা!',
      'খাবো, দাবো, মোজা করবো!',
    ],
    dialogueEn: [
      'Your Majesty, we want to sing!',
      'The King of Ghosts granted three boons!',
      'Goopy, you sing! Bagha, you play!',
      'We\'ll eat, we\'ll feast, we\'ll have fun!',
    ],
    quiz: [
      {
        id: 'goopy-gyne-bagha-byne-1',
        prompt: 'What does গান mean?',
        promptBn: 'গান শব্দের ইংরেজি অর্থ কী?',
        options: ['Song', 'Dance', 'Story', 'Play'],
        correct: 0,
        explanation: 'গান (gaan) = song. গুপী একজন গায়ক (singer) — সে গান গায়।',
      },
      {
        id: 'goopy-gyne-bagha-byne-2',
        prompt: 'What does ভূত mean in this film\'s context?',
        promptBn: 'এই ছবিতে ভূত শব্দের অর্থ কী?',
        options: ['Ghost', 'King', 'Musician', 'Magician'],
        correct: 0,
        explanation: 'ভূত (bhut) = ghost. ভূতের রাজা = the King of Ghosts, who grants the magical boons.',
      },
      {
        id: 'goopy-gyne-bagha-byne-3',
        prompt: 'What does চলচ্চিত্র mean?',
        promptBn: 'চলচ্চিত্র শব্দের অর্থ কী?',
        options: ['Film/movie', 'Theater', 'Painting', 'Photograph'],
        correct: 0,
        explanation: 'চলচ্চিত্র (cholochitro) = film/movie. চল (moving) + চিত্র (picture) = moving picture.',
      },
    ],
  },

  // ─── 3. Jibon Theke Neya ───────────────────────────────────
  {
    id: 'jibon-theke-neya',
    bengaliName: 'জীবন থেকে নেয়া',
    englishName: 'Taken from Life',
    icon: '✊',
    tags: ['রাজনৈতিক', 'Drama'],
    director: 'Zahir Raihan',
    directorBn: 'জহির রায়হান',
    year: '1970',
    descBn: 'জীবন থেকে নেয়া বাংলাদেশের চলচ্চিত্রের ইতিহাসে একটি যুগান্তকারী ছবি। পরিচালক জহির রায়হান একটি পরিবারের অন্দরমহলের গল্পের মধ্য দিয়ে পাকিস্তানি শাসনের বিরুদ্ধে বাঙালিদের প্রতিরোধের চিত্র তুলে ধরেছেন। ছবিতে "আমার সোনার বাংলা" গানটি প্রথম চলচ্চিত্রে ব্যবহৃত হয়।',
    descEn: 'Jibon Theke Neya is a landmark political film in Bangladeshi cinema. Director Zahir Raihan used the allegory of a dysfunctional family to depict the oppression of Bengalis under Pakistani rule. The film is historically significant as it featured "Amar Shonar Bangla" (later the national anthem) on screen for the first time, becoming a powerful symbol of the Bengali independence movement.',
    dialogueBn: [
      'আমরা বাঙালি, বাংলা আমাদের ভাষা!',
      'এই ঘরে আমার কোনো অধিকার নেই?',
      'চাবি দাও! চাবি আমার চাই!',
      'আমরা স্বাধীনতা চাই।',
    ],
    dialogueEn: [
      'We are Bengalis, Bengali is our language!',
      'Don\'t I have any rights in this house?',
      'Give the key! I want the key!',
      'We want freedom.',
    ],
    quiz: [
      {
        id: 'jibon-theke-neya-1',
        prompt: 'What does জীবন mean?',
        promptBn: 'জীবন শব্দের ইংরেজি অর্থ কী?',
        options: ['Life', 'Death', 'Love', 'Freedom'],
        correct: 0,
        explanation: 'জীবন (jibon) = life. জীবন থেকে নেয়া = taken from life.',
      },
      {
        id: 'jibon-theke-neya-2',
        prompt: 'What does স্বাধীনতা mean?',
        promptBn: 'স্বাধীনতা শব্দের অর্থ কী?',
        options: ['Freedom/independence', 'Peace', 'Justice', 'Strength'],
        correct: 0,
        explanation: 'স্বাধীনতা (shadhinota) = freedom or independence. The film is an allegory for Bengali independence.',
      },
      {
        id: 'jibon-theke-neya-3',
        prompt: 'Which song, later Bangladesh\'s national anthem, appeared in this film?',
        promptBn: 'কোন গানটি, যা পরে বাংলাদেশের জাতীয় সঙ্গীত হয়, এই ছবিতে ব্যবহৃত হয়েছিল?',
        options: ['Amar Shonar Bangla', 'Ekla Cholo Re', 'Joy Bangla', 'Notuner Gaan'],
        correct: 0,
        explanation: '"আমার সোনার বাংলা" was first used in a film in Jibon Theke Neya, and later became Bangladesh\'s national anthem.',
      },
    ],
  },

  // ─── 4. Matir Moina ────────────────────────────────────────
  {
    id: 'matir-moina',
    bengaliName: 'মাটির ময়না',
    englishName: 'The Clay Bird',
    icon: '🐦',
    tags: ['ঐতিহাসিক', 'Drama'],
    director: 'Tareque Masud',
    directorBn: 'তারেক মাসুদ',
    year: '2002',
    descBn: 'মাটির ময়না তারেক মাসুদ পরিচালিত বাংলাদেশের সবচেয়ে আন্তর্জাতিকভাবে প্রশংসিত চলচ্চিত্রগুলোর একটি। ১৯৬০-এর দশকের পূর্ব পাকিস্তানে একটি মাদ্রাসায় পড়া ছেলের গল্প। ছবিটি ২০০২ কান চলচ্চিত্র উৎসবে FIPRESCI পুরস্কার পায়।',
    descEn: 'Matir Moina (The Clay Bird) is one of the most internationally acclaimed Bangladeshi films, directed by Tareque Masud. Set in 1960s East Pakistan, it tells the semi-autobiographical story of a young boy sent to a madrasa, exploring themes of religious extremism, rural life, and the events leading to the 1971 Liberation War. The film won the FIPRESCI Prize at the 2002 Cannes Film Festival.',
    dialogueBn: [
      'আনু, তুই পড়ালেখা ঠিকমতো কর।',
      'আমি বাড়ি যেতে চাই, মা!',
      'এই মাটির পাখি তোর জন্য।',
      'দেশে কী হচ্ছে কেউ জানে না।',
    ],
    dialogueEn: [
      'Anu, study properly.',
      'I want to go home, Ma!',
      'This clay bird is for you.',
      'No one knows what is happening in the country.',
    ],
    quiz: [
      {
        id: 'matir-moina-1',
        prompt: 'What does মাটি mean?',
        promptBn: 'মাটি শব্দের ইংরেজি অর্থ কী?',
        options: ['Clay/earth/soil', 'Bird', 'Sky', 'Water'],
        correct: 0,
        explanation: 'মাটি (mati) = clay, earth, or soil. মাটির ময়না = the clay bird (a toy).',
      },
      {
        id: 'matir-moina-2',
        prompt: 'What international prize did Matir Moina win at Cannes?',
        promptBn: 'মাটির ময়না কান চলচ্চিত্র উৎসবে কোন পুরস্কার জিতেছিল?',
        options: ['FIPRESCI Prize', 'Palme d\'Or', 'Grand Prix', 'Best Director'],
        correct: 0,
        explanation: 'Matir Moina won the FIPRESCI (International Federation of Film Critics) Prize at the 2002 Cannes Film Festival.',
      },
      {
        id: 'matir-moina-3',
        prompt: 'What does ময়না mean?',
        promptBn: 'ময়না শব্দের অর্থ কী?',
        options: ['Mynah bird', 'Flower', 'Doll', 'Child'],
        correct: 0,
        explanation: 'ময়না (moyna) = mynah bird. মাটির ময়না = a clay mynah bird, a traditional Bengali toy.',
      },
    ],
  },

  // ─── 5. Shyamol Chhaya ─────────────────────────────────────
  {
    id: 'shyamol-chhaya',
    bengaliName: 'শ্যামল ছায়া',
    englishName: 'Shyamol Chhaya',
    icon: '🌿',
    tags: ['মুক্তিযুদ্ধ', 'Epic'],
    director: 'Humayun Ahmed',
    directorBn: 'হুমায়ূন আহমেদ',
    year: '2004',
    descBn: 'শ্যামল ছায়া হুমায়ূন আহমেদ পরিচালিত বাংলাদেশের মুক্তিযুদ্ধভিত্তিক একটি চলচ্চিত্র। ১৯৭১ সালের মুক্তিযুদ্ধের সময় একটি বাসে বিভিন্ন শ্রেণির মানুষের যাত্রার মধ্য দিয়ে যুদ্ধের ভয়াবহতা ও মানবতার গল্প বলা হয়েছে। ছবিটি বাংলাদেশ থেকে অস্কারের জন্য মনোনীত হয়েছিল।',
    descEn: 'Shyamol Chhaya is a Liberation War film directed by renowned author-filmmaker Humayun Ahmed. Set during the 1971 Bangladesh Liberation War, it follows diverse passengers on a bus journey through a war-torn landscape. The film explores humanity amidst conflict and was Bangladesh\'s official submission for the Academy Awards.',
    dialogueBn: [
      'আমরা কোথায় যাচ্ছি কেউ জানে?',
      'যুদ্ধ শেষ হবে একদিন।',
      'এই দেশটা আমাদের।',
      'সামনে মিলিটারি চেকপোস্ট!',
    ],
    dialogueEn: [
      'Does anyone know where we are going?',
      'The war will end someday.',
      'This country is ours.',
      'Military checkpoint ahead!',
    ],
    quiz: [
      {
        id: 'shyamol-chhaya-1',
        prompt: 'What historical event does শ্যামল ছায়া depict?',
        promptBn: 'শ্যামল ছায়া কোন ঐতিহাসিক ঘটনা চিত্রিত করে?',
        options: ['1971 Liberation War', '1952 Language Movement', 'British colonial era', '1947 Partition'],
        correct: 0,
        explanation: 'শ্যামল ছায়া depicts the 1971 Bangladesh Liberation War (মুক্তিযুদ্ধ), the war of independence from Pakistan.',
      },
      {
        id: 'shyamol-chhaya-2',
        prompt: 'What does যুদ্ধ mean?',
        promptBn: 'যুদ্ধ শব্দের ইংরেজি অর্থ কী?',
        options: ['War', 'Peace', 'Journey', 'Freedom'],
        correct: 0,
        explanation: 'যুদ্ধ (juddho) = war. মুক্তিযুদ্ধ (muktijuddho) = liberation war.',
      },
      {
        id: 'shyamol-chhaya-3',
        prompt: 'What does ছায়া mean?',
        promptBn: 'ছায়া শব্দের অর্থ কী?',
        options: ['Shadow/shade', 'Light', 'Green', 'Dream'],
        correct: 0,
        explanation: 'ছায়া (chhaya) = shadow or shade. শ্যামল ছায়া = green shade, evoking the lush Bengali landscape.',
      },
    ],
  },

  // ─── 6. Rani Kuthir Baki Itihash ───────────────────────────
  {
    id: 'rani-kuthir-baki-itihash',
    bengaliName: 'রানী কুঠির বাকি ইতিহাস',
    englishName: 'The Remaining History of Rani\'s Cottage',
    icon: '🏚️',
    tags: ['রহস্য', 'Drama'],
    director: 'Samia Zaman',
    directorBn: 'সামিয়া জামান',
    year: '2006',
    descBn: 'রানী কুঠির বাকি ইতিহাস একটি রহস্যধর্মী নাটকীয় চলচ্চিত্র। পুরনো এক জমিদার বাড়ির ইতিহাস ও তার সাথে জড়িত রহস্যের গল্প বলে এই ছবি। বাংলাদেশের সিনেমায় নারী পরিচালকদের মধ্যে উল্লেখযোগ্য কাজ।',
    descEn: 'Rani Kuthir Baki Itihash is a mystery-drama that unravels the hidden history of an old zamindar (landlord) mansion. The film weaves together past and present timelines as secrets from the colonial era come to light. It is a notable work by one of Bangladesh\'s prominent female directors, Samia Zaman.',
    dialogueBn: [
      'এই বাড়ির ইতিহাস কেউ জানে না।',
      'রানী কুঠিতে রাতে যাবেন না!',
      'পুরনো দিনের কথা মনে পড়ে।',
      'সত্য একদিন বেরিয়ে আসবে।',
    ],
    dialogueEn: [
      'Nobody knows the history of this house.',
      'Don\'t go to Rani\'s cottage at night!',
      'I remember the old days.',
      'The truth will come out someday.',
    ],
    quiz: [
      {
        id: 'rani-kuthir-baki-itihash-1',
        prompt: 'What does ইতিহাস mean?',
        promptBn: 'ইতিহাস শব্দের ইংরেজি অর্থ কী?',
        options: ['History', 'Story', 'Mystery', 'Future'],
        correct: 0,
        explanation: 'ইতিহাস (itihash) = history. বাকি ইতিহাস = remaining/untold history.',
      },
      {
        id: 'rani-kuthir-baki-itihash-2',
        prompt: 'What does কুঠি/কুঠির mean?',
        promptBn: 'কুঠি বা কুঠির শব্দের অর্থ কী?',
        options: ['Cottage/mansion', 'Garden', 'Temple', 'Village'],
        correct: 0,
        explanation: 'কুঠি or কুঠির (kuthi/kuthir) = cottage or small mansion. রানী কুঠির = Rani\'s cottage.',
      },
      {
        id: 'rani-kuthir-baki-itihash-3',
        prompt: 'What does সত্য mean?',
        promptBn: 'সত্য শব্দের অর্থ কী?',
        options: ['Truth', 'Lie', 'Secret', 'Fear'],
        correct: 0,
        explanation: 'সত্য (shotto) = truth. "সত্য একদিন বেরিয়ে আসবে" = the truth will come out someday.',
      },
    ],
  },

  // ─── 7. Daruchini Dwip ─────────────────────────────────────
  {
    id: 'daruchini-dwip',
    bengaliName: 'দারুচিনি দ্বীপ',
    englishName: 'Island of Cinnamon',
    icon: '🏝️',
    tags: ['কমেডি', 'Adventure'],
    director: 'Tauquir Ahmed',
    directorBn: 'তৌকীর আহমেদ',
    year: '2007',
    descBn: 'দারুচিনি দ্বীপ হুমায়ূন আহমেদের উপন্যাস অবলম্বনে তৌকীর আহমেদ পরিচালিত একটি রোমাঞ্চকর চলচ্চিত্র। একদল কিশোরের দ্বীপ অভিযানের গল্প। ছবিটি ৭টি জাতীয় চলচ্চিত্র পুরস্কার জিতেছে এবং বাংলাদেশী সিনেমার নতুন যুগের সূচনা করেছে।',
    descEn: 'Daruchini Dwip (Island of Cinnamon) is an adventure film directed by Tauquir Ahmed, based on Humayun Ahmed\'s novel. It follows a group of teenagers on an exciting island expedition. The film won 7 National Film Awards and is credited with revitalizing the Bangladeshi film industry, attracting young urban audiences back to cinemas.',
    dialogueBn: [
      'চলো, দ্বীপে যাই!',
      'এই দ্বীপে কী আছে কেউ জানে?',
      'ভয় পেও না, আমরা একসাথে আছি।',
      'কী সুন্দর জায়গা!',
    ],
    dialogueEn: [
      'Come, let\'s go to the island!',
      'Does anyone know what\'s on this island?',
      'Don\'t be afraid, we\'re together.',
      'What a beautiful place!',
    ],
    quiz: [
      {
        id: 'daruchini-dwip-1',
        prompt: 'What does দ্বীপ mean?',
        promptBn: 'দ্বীপ শব্দের ইংরেজি অর্থ কী?',
        options: ['Island', 'Mountain', 'Forest', 'Ocean'],
        correct: 0,
        explanation: 'দ্বীপ (dwip) = island. দারুচিনি দ্বীপ = cinnamon island.',
      },
      {
        id: 'daruchini-dwip-2',
        prompt: 'What does দারুচিনি mean?',
        promptBn: 'দারুচিনি শব্দের অর্থ কী?',
        options: ['Cinnamon', 'Sugar', 'Pepper', 'Salt'],
        correct: 0,
        explanation: 'দারুচিনি (daruchini) = cinnamon. It is a common spice in Bengali cooking.',
      },
      {
        id: 'daruchini-dwip-3',
        prompt: 'How many National Film Awards did Daruchini Dwip win?',
        promptBn: 'দারুচিনি দ্বীপ কতটি জাতীয় চলচ্চিত্র পুরস্কার জিতেছে?',
        options: ['7', '3', '5', '10'],
        correct: 0,
        explanation: 'দারুচিনি দ্বীপ won 7 (সাত) National Film Awards and helped revitalize Bangladeshi cinema.',
      },
    ],
  },

  // ─── 8. Monpura ────────────────────────────────────────────
  {
    id: 'monpura',
    bengaliName: 'মনপুরা',
    englishName: 'Monpura',
    icon: '💔',
    tags: ['রোমান্টিক', 'Tragedy'],
    director: 'Giasuddin Selim',
    directorBn: 'গিয়াসউদ্দিন সেলিম',
    year: '2009',
    descBn: 'মনপুরা গিয়াসউদ্দিন সেলিম পরিচালিত একটি রোমান্টিক ট্র্যাজেডি। মনপুরা দ্বীপের জেলে পরিবারের ছেলে সোনাই ও পানতরার প্রেমের বিয়োগান্ত কাহিনি। ছবিটি বক্স-অফিসে ব্যাপক সাফল্য অর্জন করে এবং বাংলাদেশি সিনেমার পুনর্জাগরণে গুরুত্বপূর্ণ ভূমিকা রাখে।',
    descEn: 'Monpura is a romantic tragedy directed by Giasuddin Selim, set on the island of Monpura in the Bay of Bengal. It tells the tragic love story of Sonai, a fisherman\'s son, and Panttara. The film became a massive box-office hit and played a crucial role in the revival of Bangladeshi commercial cinema.',
    dialogueBn: [
      'পানতরা, তুমি কোথায় যাচ্ছো?',
      'সোনাই, তুমি আমার জন্য অপেক্ষা করবে?',
      'এই নদী আমাদের সাক্ষী।',
      'ভালোবাসা কখনো শেষ হয় না।',
    ],
    dialogueEn: [
      'Panttara, where are you going?',
      'Sonai, will you wait for me?',
      'This river is our witness.',
      'Love never ends.',
    ],
    quiz: [
      {
        id: 'monpura-1',
        prompt: 'What does ভালোবাসা mean?',
        promptBn: 'ভালোবাসা শব্দের ইংরেজি অর্থ কী?',
        options: ['Love', 'Friendship', 'Hope', 'Sadness'],
        correct: 0,
        explanation: 'ভালোবাসা (bhalobasha) = love. "ভালোবাসা কখনো শেষ হয় না" = love never ends.',
      },
      {
        id: 'monpura-2',
        prompt: 'What does নদী mean?',
        promptBn: 'নদী শব্দের অর্থ কী?',
        options: ['River', 'Sea', 'Lake', 'Island'],
        correct: 0,
        explanation: 'নদী (nodi) = river. Rivers are central to Bengali life and culture.',
      },
      {
        id: 'monpura-3',
        prompt: 'What does অভিনেতা mean in Bengali film terminology?',
        promptBn: 'অভিনেতা শব্দের অর্থ কী?',
        options: ['Actor', 'Director', 'Writer', 'Singer'],
        correct: 0,
        explanation: 'অভিনেতা (obhineta) = actor (male). অভিনেত্রী (obhinetri) = actress (female).',
      },
    ],
  },

  // ─── 9. Aynabaji ───────────────────────────────────────────
  {
    id: 'aynabaji',
    bengaliName: 'আয়নাবাজি',
    englishName: 'Mirror Game',
    icon: '🪞',
    tags: ['থ্রিলার', 'Thriller'],
    director: 'Amitabh Reza Chowdhury',
    directorBn: 'অমিতাভ রেজা চৌধুরী',
    year: '2016',
    descBn: 'আয়নাবাজি অমিতাভ রেজা চৌধুরী পরিচালিত একটি থ্রিলার চলচ্চিত্র। এক প্রতিভাবান অভিনেতা যে বিভিন্ন মানুষের রূপ ধারণ করে বেঁচে থাকে — তার জীবনের জটিল গল্প। ছবিটি ২০১৬ সালে কান চলচ্চিত্র উৎসবে প্রদর্শিত হয় এবং বাংলাদেশ থেকে অস্কারে পাঠানো হয়।',
    descEn: 'Aynabaji (Mirror Game) is a psychological thriller directed by Amitabh Reza Chowdhury. It follows a gifted street actor who survives by impersonating different people, blurring the lines between identity and performance. The film was screened at the 2016 Cannes Film Festival and was Bangladesh\'s entry for the Academy Awards, garnering international acclaim.',
    dialogueBn: [
      'তুমি কে? আসল তুমি কে?',
      'আমি সবাই, আমি কেউ না।',
      'আয়না কখনো মিথ্যা বলে না।',
      'এই শহরে সবাই অভিনয় করে।',
    ],
    dialogueEn: [
      'Who are you? Who are you really?',
      'I am everyone, I am no one.',
      'A mirror never lies.',
      'In this city, everyone is acting.',
    ],
    quiz: [
      {
        id: 'aynabaji-1',
        prompt: 'What does আয়না mean?',
        promptBn: 'আয়না শব্দের ইংরেজি অর্থ কী?',
        options: ['Mirror', 'Window', 'Door', 'Glass'],
        correct: 0,
        explanation: 'আয়না (ayna) = mirror. আয়নাবাজি = mirror game / the art of mirroring identities.',
      },
      {
        id: 'aynabaji-2',
        prompt: 'What does অভিনয় mean?',
        promptBn: 'অভিনয় শব্দের অর্থ কী?',
        options: ['Acting/performance', 'Singing', 'Dancing', 'Writing'],
        correct: 0,
        explanation: 'অভিনয় (obhinoy) = acting or performance. "সবাই অভিনয় করে" = everyone is acting.',
      },
      {
        id: 'aynabaji-3',
        prompt: 'What does মিথ্যা mean?',
        promptBn: 'মিথ্যা শব্দের অর্থ কী?',
        options: ['Lie/false', 'Truth', 'Story', 'Dream'],
        correct: 0,
        explanation: 'মিথ্যা (mittha) = lie or false. "আয়না কখনো মিথ্যা বলে না" = a mirror never tells lies.',
      },
    ],
  },

  // ─── 10. Hawa ──────────────────────────────────────────────
  {
    id: 'hawa',
    bengaliName: 'হাওয়া',
    englishName: 'Hawa (Wind)',
    icon: '🌊',
    tags: ['লোকভীতি', 'Folk-Horror'],
    director: 'Mejbaur Rahman Sumon',
    directorBn: 'মেজবাউর রহমান সুমন',
    year: '2022',
    descBn: 'হাওয়া মেজবাউর রহমান সুমন পরিচালিত একটি আধুনিক লোকভীতিমূলক চলচ্চিত্র। বঙ্গোপসাগরে মাছ ধরতে যাওয়া জেলেদের নৌকায় রহস্যময় এক নারীর আবির্ভাব ঘিরে গল্প। বাংলাদেশি সিনেমায় নতুন ধারার সূচনা করে এই ছবি বক্স-অফিসে ব্যাপক সাফল্য পায়।',
    descEn: 'Hawa is a modern folk-horror film directed by Mejbaur Rahman Sumon. Set on a fishing boat in the Bay of Bengal, a mysterious woman appears among a crew of fishermen, leading to eerie and supernatural events. Blending Bengali folk mythology with horror, it became a massive commercial and critical success, pioneering a new genre in Bangladeshi cinema.',
    dialogueBn: [
      'এই মেয়ে কোথা থেকে এলো?',
      'সমুদ্রের মাঝে কেউ বাঁচতে পারে না!',
      'হাওয়া বদলে গেছে!',
      'এটা মানুষ না, জলপরী!',
    ],
    dialogueEn: [
      'Where did this girl come from?',
      'No one can survive in the middle of the sea!',
      'The wind has changed!',
      'This is not a human, it\'s a mermaid!',
    ],
    quiz: [
      {
        id: 'hawa-1',
        prompt: 'What does হাওয়া mean?',
        promptBn: 'হাওয়া শব্দের ইংরেজি অর্থ কী?',
        options: ['Wind/air', 'Water', 'Fire', 'Earth'],
        correct: 0,
        explanation: 'হাওয়া (hawa) = wind or air. "হাওয়া বদলে গেছে" = the wind has changed.',
      },
      {
        id: 'hawa-2',
        prompt: 'What does সমুদ্র mean?',
        promptBn: 'সমুদ্র শব্দের অর্থ কী?',
        options: ['Sea/ocean', 'River', 'Lake', 'Island'],
        correct: 0,
        explanation: 'সমুদ্র (shomudro) = sea or ocean. The film is set on the Bay of Bengal (বঙ্গোপসাগর).',
      },
      {
        id: 'hawa-3',
        prompt: 'What does জলপরী mean?',
        promptBn: 'জলপরী শব্দের অর্থ কী?',
        options: ['Mermaid', 'Witch', 'Ghost', 'Angel'],
        correct: 0,
        explanation: 'জলপরী (jolpori) = mermaid. জল (water) + পরী (fairy) = water fairy / mermaid.',
      },
    ],
  },
];

export { MOVIES };
