/* ── music.js — Bengali song data + quiz questions ──────────── */

const MUSIC = [
  // ─── 1. Amar Shonar Bangla ─────────────────────────────────
  {
    id: 'amar-shonar-bangla',
    bengaliName: 'আমার সোনার বাংলা',
    englishName: 'My Golden Bengal',
    icon: '🎵',
    tags: ['রবীন্দ্রসঙ্গীত', 'Patriotic'],
    artist: 'Rabindranath Tagore',
    year: '1905',
    descBn: 'আমার সোনার বাংলা বাংলাদেশের জাতীয় সঙ্গীত। রবীন্দ্রনাথ ঠাকুর ১৯০৫ সালে বঙ্গভঙ্গ আন্দোলনের সময় এই গানটি রচনা করেন। এটি বাংলার প্রকৃতি ও মাতৃভূমির প্রতি গভীর ভালোবাসার প্রকাশ।',
    descEn: 'Amar Shonar Bangla is the national anthem of Bangladesh. Written by Rabindranath Tagore in 1905 during the Swadeshi movement against the partition of Bengal, it expresses deep love for the motherland through vivid imagery of Bengal\'s natural beauty.',
    lyricsBn: [
      'আমার সোনার বাংলা, আমি তোমায় ভালোবাসি।',
      'চিরদিন তোমার আকাশ, তোমার বাতাস,',
      'আমার প্রাণে বাজায় বাঁশি।',
      'ও মা, ফাগুনে তোর আমের বনে',
      'ঘ্রাণে পাগল করে—',
      'মরি হায়, হায় রে—',
      'ও মা, অঘ্রাণে তোর ভরা ক্ষেতে',
      'আমি কী দেখেছি মধুর হাসি।',
    ],
    lyricsEn: [
      'My golden Bengal, I love you.',
      'Forever your skies, your breezes,',
      'play the flute in my heart.',
      'O mother, in spring your mango groves',
      'drive me wild with fragrance—',
      'Ah, what ecstasy—',
      'O mother, in late autumn your full fields',
      'I have seen your sweet smile.',
    ],
    quiz: [
      {
        id: 'amar-shonar-bangla-1',
        prompt: 'What does সোনার mean in "আমার সোনার বাংলা"?',
        promptBn: '"আমার সোনার বাংলা"-তে সোনার শব্দের অর্থ কী?',
        options: ['Golden', 'Beautiful', 'Ancient', 'Beloved'],
        correct: 0,
        explanation: 'সোনার (shonar) means golden — from সোনা (gold). The song calls Bengal "my golden Bengal."',
      },
      {
        id: 'amar-shonar-bangla-2',
        prompt: 'What does ভালোবাসি mean?',
        promptBn: 'ভালোবাসি শব্দের অর্থ কী?',
        options: ['I love', 'I miss', 'I remember', 'I see'],
        correct: 0,
        explanation: 'ভালোবাসি (bhalobasbi) = I love. আমি তোমায় ভালোবাসি = I love you.',
      },
      {
        id: 'amar-shonar-bangla-3',
        prompt: 'What does আকাশ mean?',
        promptBn: 'আকাশ শব্দের ইংরেজি অর্থ কী?',
        options: ['Sky', 'River', 'Mountain', 'Forest'],
        correct: 0,
        explanation: 'আকাশ (akash) = sky. "তোমার আকাশ, তোমার বাতাস" = your sky, your breeze.',
      },
    ],
  },

  // ─── 2. Ekla Cholo Re ──────────────────────────────────────
  {
    id: 'ekla-cholo-re',
    bengaliName: 'একলা চলো রে',
    englishName: 'Walk Alone',
    icon: '🚶',
    tags: ['রবীন্দ্রসঙ্গীত', 'Inspirational'],
    artist: 'Rabindranath Tagore',
    year: '1905',
    descBn: 'একলা চলো রে রবীন্দ্রনাথ ঠাকুরের একটি অনুপ্রেরণামূলক গান। এটি আত্মবিশ্বাস ও সাহসের বার্তা বহন করে — কেউ সাথে না এলেও একা এগিয়ে যাওয়ার প্রেরণা দেয়।',
    descEn: 'Ekla Cholo Re is an inspirational song by Rabindranath Tagore. It carries a powerful message of self-reliance: if no one responds to your call, walk alone with determination. It became an anthem during India\'s independence movement.',
    lyricsBn: [
      'যদি তোর ডাক শুনে কেউ না আসে,',
      'তবে একলা চলো রে।',
      'একলা চলো, একলা চলো, একলা চলো রে।',
      'যদি কেউ কথা না কয়, ওরে ওরে ও অভাগা,',
      'যদি সবাই থাকে মুখ ফিরায়ে,',
      'সবাই করে ভয়—',
      'তবে পরান খুলে',
      'ও তুই মুখ ফুটে তোর একলা গান গাও রে।',
    ],
    lyricsEn: [
      'If no one responds to your call,',
      'then walk alone.',
      'Walk alone, walk alone, walk alone.',
      'If no one speaks, O unfortunate one,',
      'If everyone turns their face away,',
      'if everyone is afraid—',
      'then open your heart',
      'and sing your song alone.',
    ],
    quiz: [
      {
        id: 'ekla-cholo-re-1',
        prompt: 'What does একলা mean?',
        promptBn: 'একলা শব্দের অর্থ কী?',
        options: ['Alone', 'Together', 'Quickly', 'Slowly'],
        correct: 0,
        explanation: 'একলা (ekla) = alone. একলা চলো রে = walk alone!',
      },
      {
        id: 'ekla-cholo-re-2',
        prompt: 'What does ডাক mean in this song?',
        promptBn: 'এই গানে ডাক শব্দের অর্থ কী?',
        options: ['Call', 'Song', 'Path', 'Dream'],
        correct: 0,
        explanation: 'ডাক (dak) = call. "যদি তোর ডাক শুনে কেউ না আসে" = if no one comes hearing your call.',
      },
      {
        id: 'ekla-cholo-re-3',
        prompt: 'What does গান গাও mean?',
        promptBn: 'গান গাও-এর অর্থ কী?',
        options: ['Sing a song', 'Write a song', 'Hear a song', 'Play a song'],
        correct: 0,
        explanation: 'গান (gaan) = song, গাও (gao) = sing. গান গাও = sing a song.',
      },
    ],
  },

  // ─── 3. Tumi Robe Nirobe ───────────────────────────────────
  {
    id: 'tumi-robe-nirobe',
    bengaliName: 'তুমি রবে নীরবে',
    englishName: 'You Will Stay Silently',
    icon: '💕',
    tags: ['রবীন্দ্রসঙ্গীত', 'Romantic'],
    artist: 'Rabindranath Tagore',
    year: '1895',
    descBn: 'তুমি রবে নীরবে রবীন্দ্রনাথ ঠাকুরের একটি রোমান্টিক গান। এটি প্রিয়জনের নীরব উপস্থিতি ও হৃদয়ের গভীর সংযোগের কথা বলে।',
    descEn: 'Tumi Robe Nirobe is a romantic Rabindra Sangeet that speaks of a beloved\'s silent, constant presence. It beautifully captures how love transcends words — the beloved remains quietly in the heart, in sleep and in waking.',
    lyricsBn: [
      'তুমি রবে নীরবে, হৃদয়ে মম,',
      'নিবিড় নিভৃত পুলকে।',
      'তুমি রবে নীরবে।',
      'রজনী যবে গভীর হবে,',
      'শান্ত নয়নে নয়ন রবে—',
      'কুসুম-গন্ধে অন্ধকারে',
      'মৌন হয়ে মম পরশে রবে।',
    ],
    lyricsEn: [
      'You will stay silently, in my heart,',
      'in deep, secret joy.',
      'You will stay silently.',
      'When the night grows deep,',
      'your calm eyes will gaze into mine—',
      'in the flower-scented darkness',
      'you will stay silently at my touch.',
    ],
    quiz: [
      {
        id: 'tumi-robe-nirobe-1',
        prompt: 'What does নীরবে mean?',
        promptBn: 'নীরবে শব্দের অর্থ কী?',
        options: ['Silently', 'Loudly', 'Happily', 'Sadly'],
        correct: 0,
        explanation: 'নীরবে (nirobe) = silently. নীরব (nirob) = silent.',
      },
      {
        id: 'tumi-robe-nirobe-2',
        prompt: 'What does হৃদয় mean?',
        promptBn: 'হৃদয় শব্দের ইংরেজি অর্থ কী?',
        options: ['Heart', 'Mind', 'Soul', 'Eyes'],
        correct: 0,
        explanation: 'হৃদয় (hridoy) = heart. "হৃদয়ে মম" = in my heart.',
      },
      {
        id: 'tumi-robe-nirobe-3',
        prompt: 'What does রজনী mean?',
        promptBn: 'রজনী শব্দের অর্থ কী?',
        options: ['Night', 'Morning', 'Evening', 'Dawn'],
        correct: 0,
        explanation: 'রজনী (rojoni) = night. "রজনী যবে গভীর হবে" = when the night grows deep.',
      },
    ],
  },

  // ─── 4. Karar Oi Louho Kopat ───────────────────────────────
  {
    id: 'karar-oi-louho-kopat',
    bengaliName: 'কারার ঐ লৌহ কপাট',
    englishName: 'Those Iron Gates of the Prison',
    icon: '⛓️',
    tags: ['নজরুলগীতি', 'Revolutionary'],
    artist: 'Kazi Nazrul Islam',
    year: '1922',
    descBn: 'কারার ঐ লৌহ কপাট কাজী নজরুল ইসলামের বিখ্যাত বিদ্রোহী গান। ব্রিটিশ শাসনের বিরুদ্ধে এই গান স্বাধীনতা সংগ্রামীদের অনুপ্রেরণা জুগিয়েছিল।',
    descEn: 'Karar Oi Louho Kopat is a famous revolutionary song by Kazi Nazrul Islam, the "Rebel Poet" of Bengal. Written during the British colonial period, it calls for breaking the iron gates of oppression and became a rallying cry for freedom fighters.',
    lyricsBn: [
      'কারার ঐ লৌহ কপাট,',
      'ভেঙে ফেল কর রে লোপাট,',
      'রক্ত জমাট শিকল পূজার পাষাণ বেদী।',
      'ওরে ও তরুণ ঈশান!',
      'বাজা তোর প্রলয় বিষাণ!',
      'ধ্বংস নিশান উড়ুক প্রাচীর প্রাচীর ভেদি।',
    ],
    lyricsEn: [
      'Those iron gates of the prison,',
      'break them down, destroy them!',
      'The blood-stained altar of chain-worship.',
      'O young storm!',
      'Blow your horn of doom!',
      'Let the flag of destruction fly, piercing wall after wall.',
    ],
    quiz: [
      {
        id: 'karar-oi-louho-kopat-1',
        prompt: 'What does লৌহ mean?',
        promptBn: 'লৌহ শব্দের অর্থ কী?',
        options: ['Iron', 'Gold', 'Wood', 'Stone'],
        correct: 0,
        explanation: 'লৌহ (louho) = iron. লৌহ কপাট = iron gates.',
      },
      {
        id: 'karar-oi-louho-kopat-2',
        prompt: 'What does ভেঙে ফেল mean?',
        promptBn: 'ভেঙে ফেল-এর অর্থ কী?',
        options: ['Break down', 'Build up', 'Lock away', 'Open slowly'],
        correct: 0,
        explanation: 'ভেঙে ফেল (bhenge phel) = break down / destroy. ভাঙা (bhanga) = to break.',
      },
      {
        id: 'karar-oi-louho-kopat-3',
        prompt: 'What does কারা mean in this context?',
        promptBn: 'এখানে কারা শব্দের অর্থ কী?',
        options: ['Prison', 'Who', 'Iron', 'Gate'],
        correct: 0,
        explanation: 'কারা (kara) = prison. কারার = of the prison. Note: কারা can also mean "who" in a different context.',
      },
    ],
  },

  // ─── 5. Khachar Bhitor Ochin Pakhi ─────────────────────────
  {
    id: 'khachar-bhitor-ochin-pakhi',
    bengaliName: 'খাঁচার ভিতর অচিন পাখি',
    englishName: 'The Unknown Bird in the Cage',
    icon: '🐦',
    tags: ['বাউলগান', 'Folk'],
    artist: 'Lalon Shah',
    year: '19th c.',
    descBn: 'খাঁচার ভিতর অচিন পাখি বাউল সাধক লালন শাহের সবচেয়ে বিখ্যাত গান। এতে দেহকে খাঁচা এবং আত্মাকে পাখির রূপকে তুলনা করা হয়েছে।',
    descEn: 'This is the most famous song by Lalon Shah, the great Baul mystic of Bengal. Using the metaphor of an unknown bird trapped in a cage, it explores the relationship between body and soul — the cage is the body, and the mysterious bird is the soul that will eventually fly away.',
    lyricsBn: [
      'খাঁচার ভিতর অচিন পাখি কেমনে আসে যায়।',
      'ধরতে পারলে মনো-বেড়ি',
      'দিতাম পাখির পায়।',
      'আট কুঠুরি নয় দরজা আঁটা,',
      'মধ্যে মধ্যে ঝরকা কাটা,',
      'তার উপরে সদর কোঠা,',
      'আয়নামহল তায়।',
    ],
    lyricsEn: [
      'How does the unknown bird come and go within the cage?',
      'If I could catch it, I would place',
      'the shackles of my mind on its feet.',
      'Eight rooms with nine doors shut tight,',
      'with latticed windows in between,',
      'above them the main chamber,',
      'a hall of mirrors.',
    ],
    quiz: [
      {
        id: 'khachar-bhitor-ochin-pakhi-1',
        prompt: 'What does খাঁচা mean?',
        promptBn: 'খাঁচা শব্দের অর্থ কী?',
        options: ['Cage', 'Nest', 'Tree', 'Sky'],
        correct: 0,
        explanation: 'খাঁচা (khacha) = cage. In Baul philosophy, it represents the human body.',
      },
      {
        id: 'khachar-bhitor-ochin-pakhi-2',
        prompt: 'What does পাখি mean?',
        promptBn: 'পাখি শব্দের ইংরেজি অর্থ কী?',
        options: ['Bird', 'Flower', 'Wind', 'Cloud'],
        correct: 0,
        explanation: 'পাখি (pakhi) = bird. অচিন পাখি = unknown/mysterious bird, symbolizing the soul.',
      },
      {
        id: 'khachar-bhitor-ochin-pakhi-3',
        prompt: 'What does অচিন mean?',
        promptBn: 'অচিন শব্দের অর্থ কী?',
        options: ['Unknown/unfamiliar', 'Beautiful', 'Small', 'Free'],
        correct: 0,
        explanation: 'অচিন (ochin) = unknown, unfamiliar. অচিন পাখি = the unknown bird (the soul).',
      },
    ],
  },

  // ─── 6. Amar Bhaiyer Rokte Rangano ─────────────────────────
  {
    id: 'amar-bhaiyer-rokte-rangano',
    bengaliName: 'আমার ভাইয়ের রক্তে রাঙানো',
    englishName: 'Stained With My Brother\'s Blood',
    icon: '🩸',
    tags: ['দেশাত্মবোধক', 'Language Movement'],
    artist: 'Abdul Gaffar Chowdhury / Altaf Mahmud',
    year: '1952',
    descBn: 'আমার ভাইয়ের রক্তে রাঙানো ১৯৫২ সালের ভাষা আন্দোলনের স্মরণে রচিত। প্রতি বছর ২১শে ফেব্রুয়ারি আন্তর্জাতিক মাতৃভাষা দিবসে এই গান গাওয়া হয়।',
    descEn: 'This song commemorates the Bengali Language Movement of 1952, when students were killed protesting for the right to speak Bengali. Sung every February 21st on International Mother Language Day, it is one of the most emotionally significant songs in Bangladeshi culture.',
    lyricsBn: [
      'আমার ভাইয়ের রক্তে রাঙানো একুশে ফেব্রুয়ারি,',
      'আমি কি ভুলিতে পারি।',
      'ছেলেহারা শত মায়ের অশ্রু গড়া',
      'এ ফেব্রুয়ারি, আমি কি ভুলিতে পারি।',
      'আমার সোনার দেশের রক্তে রাঙানো',
      'একুশে ফেব্রুয়ারি, আমি কি ভুলিতে পারি।',
    ],
    lyricsEn: [
      'The 21st of February, stained with my brother\'s blood,',
      'can I ever forget it?',
      'Built with the tears of hundreds of mothers who lost their sons,',
      'this February — can I ever forget?',
      'Stained with the blood of my golden land,',
      'the 21st of February — can I ever forget?',
    ],
    quiz: [
      {
        id: 'amar-bhaiyer-rokte-rangano-1',
        prompt: 'What does রক্ত mean?',
        promptBn: 'রক্ত শব্দের ইংরেজি অর্থ কী?',
        options: ['Blood', 'Tears', 'Sweat', 'Rain'],
        correct: 0,
        explanation: 'রক্ত (rokto) = blood. রক্তে রাঙানো = stained/colored with blood.',
      },
      {
        id: 'amar-bhaiyer-rokte-rangano-2',
        prompt: 'What does ভাই mean?',
        promptBn: 'ভাই শব্দের অর্থ কী?',
        options: ['Brother', 'Friend', 'Father', 'Son'],
        correct: 0,
        explanation: 'ভাই (bhai) = brother. আমার ভাইয়ের = of my brother.',
      },
      {
        id: 'amar-bhaiyer-rokte-rangano-3',
        prompt: 'What does ভুলিতে পারি mean?',
        promptBn: 'ভুলিতে পারি-র অর্থ কী?',
        options: ['Can forget', 'Can remember', 'Can forgive', 'Can see'],
        correct: 0,
        explanation: 'ভুলিতে পারি = can forget. "আমি কি ভুলিতে পারি" = Can I ever forget?',
      },
    ],
  },

  // ─── 7. Coffee Houser Sei Addata ───────────────────────────
  {
    id: 'coffee-houser-sei-addata',
    bengaliName: 'কফি হাউসের সেই আড্ডাটা',
    englishName: 'That Coffee House Gathering',
    icon: '☕',
    tags: ['আধুনিক', 'Nostalgic'],
    artist: 'Manna Dey',
    year: '1983',
    descBn: 'কফি হাউসের সেই আড্ডাটা মান্না দে-র একটি জনপ্রিয় নস্টালজিক গান। কলকাতার কলেজ স্ট্রিট কফি হাউসে তরুণ বন্ধুদের আড্ডার স্মৃতিকে ফিরিয়ে আনে এই গান।',
    descEn: 'This beloved nostalgic song by Manna Dey recalls the coffee house gatherings of youth on College Street, Kolkata. It reminisces about friends, debates, dreams, and lost connections — a universal theme of growing up and growing apart.',
    lyricsBn: [
      'কফি হাউসের সেই আড্ডাটা আজ আর নেই,',
      'আজ আর নেই।',
      'কোথায় হারিয়ে গেল সোনালি বিকেলগুলো,',
      'সেই আড্ডা, সেই বন্ধুরা আজ আর নেই।',
      'কোনো এক বর্ষায় তুমি আমাকে বলেছিলে,',
      'সেই কথাটা মনে আছে কি তোমার।',
    ],
    lyricsEn: [
      'That coffee house gathering is no more,',
      'it is no more.',
      'Where have those golden afternoons gone,',
      'those gatherings, those friends — they are no more.',
      'In some monsoon season you had said to me,',
      'do you still remember those words?',
    ],
    quiz: [
      {
        id: 'coffee-houser-sei-addata-1',
        prompt: 'What does আড্ডা mean?',
        promptBn: 'আড্ডা শব্দের অর্থ কী?',
        options: ['A casual gathering/hangout', 'A meeting', 'A festival', 'A restaurant'],
        correct: 0,
        explanation: 'আড্ডা (adda) = a casual gathering or hangout for conversation. It is a distinctly Bengali social tradition.',
      },
      {
        id: 'coffee-houser-sei-addata-2',
        prompt: 'What does আজ আর নেই mean?',
        promptBn: 'আজ আর নেই-এর অর্থ কী?',
        options: ['Is no more / no longer exists', 'Is still here', 'Will come back', 'Is far away'],
        correct: 0,
        explanation: 'আজ আর নেই (aj ar nei) = is no more today. আর নেই = no longer exists.',
      },
      {
        id: 'coffee-houser-sei-addata-3',
        prompt: 'What does বন্ধু mean?',
        promptBn: 'বন্ধু শব্দের ইংরেজি অর্থ কী?',
        options: ['Friend', 'Brother', 'Teacher', 'Neighbor'],
        correct: 0,
        explanation: 'বন্ধু (bondhu) = friend. বন্ধুরা = friends (plural).',
      },
    ],
  },

  // ─── 8. Ei Raat Tomar Amar ─────────────────────────────────
  {
    id: 'ei-raat-tomar-amar',
    bengaliName: 'এই রাত তোমার আমার',
    englishName: 'This Night Is Yours and Mine',
    icon: '🌙',
    tags: ['চলচ্চিত্রসঙ্গীত', 'Romantic'],
    artist: 'Hemanta Mukherjee',
    year: '1959',
    descBn: 'এই রাত তোমার আমার হেমন্ত মুখোপাধ্যায়ের কণ্ঠে একটি চিরসবুজ রোমান্টিক গান। ১৯৫৯ সালের "দীপ জ্বেলে যাই" চলচ্চিত্রের জন্য রচিত।',
    descEn: 'This evergreen romantic song sung by Hemanta Mukherjee is from the 1959 Bengali film "Deep Jwele Jai." It is a tender duet celebrating a moonlit night shared between lovers, with poetic imagery of stars and dreams.',
    lyricsBn: [
      'এই রাত তোমার আমার,',
      'আর কতোবার হবে রাত এমন করে।',
      'এই চাঁদ তোমার আমার,',
      'আর কতোবার হবে চাঁদ এমন ঘিরে।',
      'তারাভরা আকাশ নীচে',
      'স্বপ্ন এলো ডানা মেলে।',
    ],
    lyricsEn: [
      'This night is yours and mine,',
      'how many more times will a night be like this?',
      'This moon is yours and mine,',
      'how many more times will the moon surround us so?',
      'Under the star-filled sky,',
      'dreams came spreading their wings.',
    ],
    quiz: [
      {
        id: 'ei-raat-tomar-amar-1',
        prompt: 'What does রাত mean?',
        promptBn: 'রাত শব্দের ইংরেজি অর্থ কী?',
        options: ['Night', 'Day', 'Morning', 'Evening'],
        correct: 0,
        explanation: 'রাত (raat) = night. "এই রাত তোমার আমার" = this night is yours and mine.',
      },
      {
        id: 'ei-raat-tomar-amar-2',
        prompt: 'What does চাঁদ mean?',
        promptBn: 'চাঁদ শব্দের অর্থ কী?',
        options: ['Moon', 'Sun', 'Star', 'Cloud'],
        correct: 0,
        explanation: 'চাঁদ (chaad) = moon. The song uses চাঁদ as romantic imagery.',
      },
      {
        id: 'ei-raat-tomar-amar-3',
        prompt: 'What does স্বপ্ন mean?',
        promptBn: 'স্বপ্ন শব্দের ইংরেজি অর্থ কী?',
        options: ['Dream', 'Memory', 'Hope', 'Love'],
        correct: 0,
        explanation: 'স্বপ্ন (shopno) = dream. "স্বপ্ন এলো ডানা মেলে" = dreams came spreading their wings.',
      },
    ],
  },

  // ─── 9. Amake Amar Moto Thakte Dao ─────────────────────────
  {
    id: 'amake-amar-moto-thakte-dao',
    bengaliName: 'আমাকে আমার মতো থাকতে দাও',
    englishName: 'Let Me Be Myself',
    icon: '🎸',
    tags: ['আধুনিক', 'Indie'],
    artist: 'Anupam Roy',
    year: '2010',
    descBn: 'আমাকে আমার মতো থাকতে দাও অনুপম রায়ের একটি জনপ্রিয় আধুনিক বাংলা গান। "অটোগ্রাফ" চলচ্চিত্র থেকে এই গানটি তরুণদের মধ্যে অত্যন্ত জনপ্রিয় হয়ে ওঠে।',
    descEn: 'This modern Bengali song by Anupam Roy from the film "Autograph" (2010) became hugely popular among young Bengalis. Its message of self-acceptance and freedom resonated with a generation — a plea to be allowed to live life on one\'s own terms.',
    lyricsBn: [
      'আমাকে আমার মতো থাকতে দাও,',
      'আমি আমার মতো থাকতে চাই।',
      'পথ আমার পথের মতো,',
      'গান আমার গানের মতো।',
      'ভুল হবে ঠিক হবে,',
      'শুধু আমার মতো হবে।',
    ],
    lyricsEn: [
      'Let me be myself,',
      'I want to be the way I am.',
      'My path is like my own path,',
      'my song is like my own song.',
      'There will be mistakes, there will be rights,',
      'it will just be like me.',
    ],
    quiz: [
      {
        id: 'amake-amar-moto-thakte-dao-1',
        prompt: 'What does থাকতে দাও mean?',
        promptBn: 'থাকতে দাও-এর অর্থ কী?',
        options: ['Let (me) stay/be', 'Come along', 'Go away', 'Stop talking'],
        correct: 0,
        explanation: 'থাকতে দাও (thakte dao) = let (me) stay/be. থাকা = to stay, দাও = give/let.',
      },
      {
        id: 'amake-amar-moto-thakte-dao-2',
        prompt: 'What does পথ mean?',
        promptBn: 'পথ শব্দের ইংরেজি অর্থ কী?',
        options: ['Path/road', 'House', 'Song', 'Dream'],
        correct: 0,
        explanation: 'পথ (poth) = path or road. "পথ আমার পথের মতো" = my path is like my own path.',
      },
      {
        id: 'amake-amar-moto-thakte-dao-3',
        prompt: 'What does ভুল mean?',
        promptBn: 'ভুল শব্দের অর্থ কী?',
        options: ['Mistake/wrong', 'Right/correct', 'Beautiful', 'Happy'],
        correct: 0,
        explanation: 'ভুল (bhul) = mistake or wrong. "ভুল হবে ঠিক হবে" = there will be mistakes, there will be rights.',
      },
    ],
  },

  // ─── 10. Bojhena Se Bojhena ─────────────────────────────────
  {
    id: 'bojhena-se-bojhena',
    bengaliName: 'বোঝেনা সে বোঝেনা',
    englishName: 'They Don\'t Understand',
    icon: '🎬',
    tags: ['চলচ্চিত্রসঙ্গীত', 'Modern'],
    artist: 'Arijit Singh',
    year: '2012',
    descBn: 'বোঝেনা সে বোঝেনা অরিজিৎ সিংয়ের কণ্ঠে একটি জনপ্রিয় আধুনিক বাংলা চলচ্চিত্রের গান। একই নামের ২০১২ সালের চলচ্চিত্র থেকে এই গানটি সারা বাংলায় ব্যাপক জনপ্রিয়তা পায়।',
    descEn: 'This popular modern Bengali film song sung by Arijit Singh is from the 2012 movie of the same name. It became a massive hit across Bengal, expressing the frustration and yearning of unrequited love — "they don\'t understand" the depth of one\'s feelings.',
    lyricsBn: [
      'বোঝেনা সে বোঝেনা,',
      'সে কিছুই বোঝেনা।',
      'যে কত চাওয়া ছিল,',
      'কত ভালোবাসা ছিল,',
      'কত স্বপ্ন ছিল আমার,',
      'সে কিছুই বোঝেনা।',
    ],
    lyricsEn: [
      'They don\'t understand, they don\'t understand,',
      'they don\'t understand anything.',
      'How much longing there was,',
      'how much love there was,',
      'how many dreams I had,',
      'they don\'t understand anything.',
    ],
    quiz: [
      {
        id: 'bojhena-se-bojhena-1',
        prompt: 'What does বোঝে mean?',
        promptBn: 'বোঝে শব্দের অর্থ কী?',
        options: ['Understands', 'Loves', 'Sees', 'Hears'],
        correct: 0,
        explanation: 'বোঝে (bojhe) = understands. বোঝেনা (bojhena) = does not understand. বোঝা = to understand.',
      },
      {
        id: 'bojhena-se-bojhena-2',
        prompt: 'What does চাওয়া mean?',
        promptBn: 'চাওয়া শব্দের ইংরেজি অর্থ কী?',
        options: ['Wanting/desire', 'Giving', 'Knowing', 'Forgetting'],
        correct: 0,
        explanation: 'চাওয়া (chaowa) = wanting, desire. "কত চাওয়া ছিল" = how much desire there was.',
      },
      {
        id: 'bojhena-se-bojhena-3',
        prompt: 'What does ছিল indicate in "ভালোবাসা ছিল"?',
        promptBn: '"ভালোবাসা ছিল"-এ ছিল কী নির্দেশ করে?',
        options: ['Past tense (was/were)', 'Present tense (is)', 'Future tense (will be)', 'A command'],
        correct: 0,
        explanation: 'ছিল (chhilo) = was/were (past tense of হওয়া). ভালোবাসা ছিল = there was love.',
      },
    ],
  },
];

export { MUSIC };
