/* ── poetry.js — Bengali poetry data + quiz questions ──────────── */

const POETRY = [
  // ─── 1. বাংলাদেশ ─────────────────────────────────────
  {
    id: 'bangladesh',
    bengaliName: 'বাংলাদেশ',
    englishName: 'Bangladesh',
    icon: '🇧🇩',
    tags: ['দেশাত্মবোধক', 'Modern'],
    poet: 'Shamsur Rahman',
    poetBn: 'শামসুর রাহমান',
    year: '1971',
    descBn: 'বাংলাদেশ শামসুর রাহমানের একটি অসাধারণ দেশাত্মবোধক কবিতা। ১৯৭১ সালের মুক্তিযুদ্ধের প্রেক্ষাপটে রচিত এই কবিতায় বাংলাদেশের স্বাধীনতার আকাঙ্ক্ষা ও জাতীয় চেতনার প্রকাশ ঘটেছে।',
    descEn: 'Bangladesh is an iconic patriotic poem by Shamsur Rahman, written during the 1971 Liberation War. It expresses the deep yearning for national independence and Bengali identity, becoming a rallying cry for the freedom movement.',
    versesBn: [
      'এ দেশ কি ভুলে যাবো?',
      'জন্মভূমির এই মাটি,',
      'এখানে জীবন, এখানে মৃত্যু,',
      'এখানেই আমার শেষ ঠিকানা।',
    ],
    versesEn: [
      'Can I ever forget this land?',
      'This soil of my birthplace,',
      'Here is life, here is death,',
      'Here is my final address.',
    ],
    quiz: [
      {
        id: 'bangladesh-1',
        prompt: 'What does জন্মভূমি mean?',
        promptBn: 'জন্মভূমি শব্দের অর্থ কী?',
        options: ['Birthplace/motherland', 'Graveyard', 'Battlefield', 'Capital city'],
        correct: 0,
        explanation: 'জন্মভূমি (jonmobhumi) = birthplace or motherland. জন্ম (birth) + ভূমি (land).',
      },
      {
        id: 'bangladesh-2',
        prompt: 'What does মাটি mean in the context of this poem?',
        promptBn: 'এই কবিতায় মাটি শব্দের অর্থ কী?',
        options: ['Soil/earth', 'Water', 'Sky', 'Blood'],
        correct: 0,
        explanation: 'মাটি (mati) = soil or earth. It symbolizes the homeland in Bengali poetry.',
      },
      {
        id: 'bangladesh-3',
        prompt: 'What does কবি mean in Bengali?',
        promptBn: 'কবি শব্দের ইংরেজি অর্থ কী?',
        options: ['Poet', 'Singer', 'Writer', 'Painter'],
        correct: 0,
        explanation: 'কবি (kobi) = poet. শামসুর রাহমান একজন বিখ্যাত বাংলা কবি।',
      },
    ],
  },

  // ─── 2. বিদ্রোহী ─────────────────────────────────────
  {
    id: 'bidrohi',
    bengaliName: 'বিদ্রোহী',
    englishName: 'The Rebel',
    icon: '✊',
    tags: ['বিদ্রোহী', 'Revolutionary'],
    poet: 'Kazi Nazrul Islam',
    poetBn: 'কাজী নজরুল ইসলাম',
    year: '1922',
    descBn: 'বিদ্রোহী কাজী নজরুল ইসলামের সবচেয়ে বিখ্যাত কবিতা। ১৯২২ সালে প্রকাশিত এই কবিতায় নজরুল অন্যায়ের বিরুদ্ধে বিদ্রোহের ঘোষণা দেন। এটি বাংলা সাহিত্যের সবচেয়ে প্রভাবশালী কবিতাগুলোর একটি।',
    descEn: 'Bidrohi (The Rebel) is the most famous poem by Kazi Nazrul Islam, Bangladesh\'s national poet. Published in 1922, it is a thunderous declaration of rebellion against all forms of oppression. The poem established Nazrul as the "Rebel Poet" of Bengal.',
    versesBn: [
      'বল বীর—',
      'বল উন্নত মম শির!',
      'শির নেহারি আমারি, নত-শির ওই শিখর হিমাদ্রির!',
      'বল বীর—',
      'বল মহাবিশ্বের মহাকাশ ফাড়ি,',
      'চন্দ্র সূর্য গ্রহ তারা ছাড়ি,',
      'ভূলোক দ্যুলোক গোলক ভেদিয়া,',
      'খোদার আসন আরশ ছেদিয়া,',
      'উঠিয়াছি চির-বিস্ময় আমি বিশ্ববিধাতৃর!',
    ],
    versesEn: [
      'Say, O hero—',
      'Say, high is my head!',
      'Behold my head — before it bows even the peak of the Himalayas!',
      'Say, O hero—',
      'Say, tearing through the great sky of the universe,',
      'leaving behind the moon, sun, planets, and stars,',
      'piercing through the earthly, heavenly, and celestial spheres,',
      'past the throne of God,',
      'I have risen — the eternal wonder of the Creator!',
    ],
    quiz: [
      {
        id: 'bidrohi-1',
        prompt: 'What does বিদ্রোহী mean?',
        promptBn: 'বিদ্রোহী শব্দের ইংরেজি অর্থ কী?',
        options: ['Rebel', 'Hero', 'Poet', 'Warrior'],
        correct: 0,
        explanation: 'বিদ্রোহী (bidrohi) = rebel. নজরুল ইসলাম "বিদ্রোহী কবি" নামে পরিচিত।',
      },
      {
        id: 'bidrohi-2',
        prompt: 'What does বীর mean?',
        promptBn: 'বীর শব্দের অর্থ কী?',
        options: ['Hero/brave one', 'Friend', 'Brother', 'Enemy'],
        correct: 0,
        explanation: 'বীর (bir) = hero or brave one. "বল বীর" = say, O hero.',
      },
      {
        id: 'bidrohi-3',
        prompt: 'What does শির mean in this poem?',
        promptBn: 'এই কবিতায় শির শব্দের অর্থ কী?',
        options: ['Head', 'Hand', 'Heart', 'Foot'],
        correct: 0,
        explanation: 'শির (shir) = head. "উন্নত মম শির" = high is my head — a symbol of pride.',
      },
    ],
  },

  // ─── 3. বনলতা সেন ────────────────────────────────────
  {
    id: 'bonolota-sen',
    bengaliName: 'বনলতা সেন',
    englishName: 'Bonolata Sen',
    icon: '🌿',
    tags: ['রোমান্টিক', 'Modern'],
    poet: 'Jibanananda Das',
    poetBn: 'জীবনানন্দ দাশ',
    year: '1942',
    descBn: 'বনলতা সেন জীবনানন্দ দাশের সবচেয়ে বিখ্যাত কবিতা এবং বাংলা সাহিত্যের সবচেয়ে সুন্দর কবিতাগুলোর একটি। হাজার বছরের পথ চলার ক্লান্তির পর বনলতা সেন নামের এক নারীর কাছে বিশ্রামের কল্পনা এই কবিতার মূল বিষয়।',
    descEn: 'Bonolata Sen is considered the most beautiful poem in Bengali literature, by Jibanananda Das. It tells of a weary traveler through thousands of years of history who finds rest in the eyes of a woman named Bonolata Sen from Natore. The poem is a masterpiece of imagery and rhythm.',
    versesBn: [
      'হাজার বছর ধরে আমি পথ হাঁটিতেছি পৃথিবীর পথে,',
      'সিংহল সমুদ্র থেকে নিশীথের অন্ধকারে মালয় সাগরে',
      'অনেক ঘুরেছি আমি; বিম্বিসার অশোকের ধূসর জগতে',
      'সেখানে ছিলাম আমি; আরো দূর অন্ধকারে বিদর্ভ নগরে;',
      'আমি ক্লান্ত প্রাণ এক, চারিদিকে জীবনের সমুদ্র সফেন,',
      'আমারে দুদণ্ড শান্তি দিয়েছিলো নাটোরের বনলতা সেন।',
    ],
    versesEn: [
      'For a thousand years I have walked the roads of this earth,',
      'From the seas of Ceylon through the darkness of night to the Malay Sea,',
      'I have wandered far; in the grey world of Bimbisara and Ashoka',
      'I was there; in the deeper darkness of Vidarbha city;',
      'I am a weary soul, all around the foaming sea of life,',
      'Bonolata Sen of Natore gave me two moments\' peace.',
    ],
    quiz: [
      {
        id: 'bonolota-sen-1',
        prompt: 'What does ক্লান্ত mean?',
        promptBn: 'ক্লান্ত শব্দের ইংরেজি অর্থ কী?',
        options: ['Tired/weary', 'Happy', 'Angry', 'Lost'],
        correct: 0,
        explanation: 'ক্লান্ত (klanto) = tired or weary. "আমি ক্লান্ত প্রাণ এক" = I am a weary soul.',
      },
      {
        id: 'bonolota-sen-2',
        prompt: 'What does পৃথিবী mean?',
        promptBn: 'পৃথিবী শব্দের অর্থ কী?',
        options: ['Earth/world', 'Sky', 'Sea', 'Mountain'],
        correct: 0,
        explanation: 'পৃথিবী (prithibi) = earth or world. "পৃথিবীর পথে" = on the roads of the earth.',
      },
      {
        id: 'bonolota-sen-3',
        prompt: 'What does শান্তি mean?',
        promptBn: 'শান্তি শব্দের ইংরেজি অর্থ কী?',
        options: ['Peace', 'Love', 'Sleep', 'Silence'],
        correct: 0,
        explanation: 'শান্তি (shanti) = peace. "দুদণ্ড শান্তি" = two moments\' peace.',
      },
    ],
  },

  // ─── 4. রূপসী বাংলা ──────────────────────────────────
  {
    id: 'ruposhi-bangla',
    bengaliName: 'রূপসী বাংলা',
    englishName: 'Beautiful Bengal',
    icon: '🌾',
    tags: ['প্রকৃতি', 'Romantic'],
    poet: 'Jibanananda Das',
    poetBn: 'জীবনানন্দ দাশ',
    year: '1957',
    descBn: 'রূপসী বাংলা জীবনানন্দ দাশের মৃত্যুর পর প্রকাশিত একটি কাব্যগ্রন্থ। বাংলার প্রকৃতির অপরূপ সৌন্দর্যের বর্ণনায় এই কবিতা বাংলা সাহিত্যে অমর হয়ে আছে। ধানক্ষেত, নদী, পাখি — বাংলার প্রতিটি উপাদান এখানে জীবন্ত।',
    descEn: 'Ruposhi Bangla (Beautiful Bengal) is a collection published posthumously, showcasing Jibanananda Das\'s deep love for Bengal\'s natural beauty. The poems paint vivid pictures of paddy fields, rivers, and birds — celebrating the lush landscape that defines rural Bengal.',
    versesBn: [
      'আবার আসিব ফিরে ধানসিঁড়ির তীরে — এই বাংলায়।',
      'হয়তো মানুষ নয় — হয়তো বা শঙ্খচিল শালিকের বেশে,',
      'হয়তো ভোরের কাক হয়ে এই কার্তিকের নবান্নের দেশে',
      'কুয়াশার বুক ভেসে একদিন আসিব এ কাঁঠালছায়ায়।',
    ],
    versesEn: [
      'I shall return again to the banks of Dhansiri — to this Bengal.',
      'Perhaps not as a human — perhaps as a brahminy kite or a mynah,',
      'perhaps as a morning crow to this land of autumn\'s new harvest,',
      'floating on the mist, one day I shall come to this jackfruit shade.',
    ],
    quiz: [
      {
        id: 'ruposhi-bangla-1',
        prompt: 'What does রূপসী mean?',
        promptBn: 'রূপসী শব্দের অর্থ কী?',
        options: ['Beautiful', 'Ancient', 'Mighty', 'Sacred'],
        correct: 0,
        explanation: 'রূপসী (ruposhi) = beautiful (feminine). রূপ (beauty) + সী = beautiful one.',
      },
      {
        id: 'ruposhi-bangla-2',
        prompt: 'What does ধান mean?',
        promptBn: 'ধান শব্দের ইংরেজি অর্থ কী?',
        options: ['Paddy/rice', 'Wheat', 'Corn', 'Lentil'],
        correct: 0,
        explanation: 'ধান (dhan) = paddy or rice (unhusked). ধানসিঁড়ি is a river in southern Bangladesh.',
      },
      {
        id: 'ruposhi-bangla-3',
        prompt: 'What does কুয়াশা mean?',
        promptBn: 'কুয়াশা শব্দের অর্থ কী?',
        options: ['Mist/fog', 'Rain', 'Snow', 'Wind'],
        correct: 0,
        explanation: 'কুয়াশা (kuyasha) = mist or fog. Bengali winter mornings are famous for কুয়াশা.',
      },
    ],
  },

  // ─── 5. সোনার তরী ────────────────────────────────────
  {
    id: 'sonar-tori',
    bengaliName: 'সোনার তরী',
    englishName: 'The Golden Boat',
    icon: '⛵',
    tags: ['রবীন্দ্রকবিতা', 'Philosophical'],
    poet: 'Rabindranath Tagore',
    poetBn: 'রবীন্দ্রনাথ ঠাকুর',
    year: '1894',
    descBn: 'সোনার তরী রবীন্দ্রনাথ ঠাকুরের সবচেয়ে আলোচিত কবিতাগুলোর একটি। একজন কৃষক তার ফসল সোনার তরীতে তুলে দেয়, কিন্তু নিজে যেতে পারে না — এই রূপকে জীবনের ক্ষণস্থায়িত্বের কথা বলা হয়েছে।',
    descEn: 'Sonar Tori (The Golden Boat) is one of Tagore\'s most discussed philosophical poems. A farmer loads his harvest onto a golden boat, but there is no room for him. The allegory explores themes of human mortality and the impermanence of life — our creations outlast us.',
    versesBn: [
      'গগনে গরজে মেঘ, ঘন বরষা।',
      'কূলে একা বসে আছি, নাহি ভরসা।',
      'রাশি রাশি ভারা ভারা',
      'ধান কাটা হলো সারা,',
      'ভরা নদী ক্ষুরধারা',
      'খরপরশা।',
      'ঠাঁই নাই, ঠাঁই নাই — ছোটো সে তরী',
      'আমারি সোনার ধান গেল কি তুলে নিল সকলি।',
    ],
    versesEn: [
      'In the sky the clouds thunder, heavy rain pours.',
      'I sit alone on the bank, with no assurance.',
      'Heap upon heap,',
      'all the rice has been cut,',
      'the river runs full, sharp as a razor,',
      'swift and harsh.',
      'No room, no room — the boat is too small,',
      'all my golden grain — has she taken it all?',
    ],
    quiz: [
      {
        id: 'sonar-tori-1',
        prompt: 'What does তরী mean?',
        promptBn: 'তরী শব্দের অর্থ কী?',
        options: ['Boat', 'River', 'Field', 'Gold'],
        correct: 0,
        explanation: 'তরী (tori) = boat. সোনার তরী = the golden boat.',
      },
      {
        id: 'sonar-tori-2',
        prompt: 'What does মেঘ mean?',
        promptBn: 'মেঘ শব্দের ইংরেজি অর্থ কী?',
        options: ['Cloud', 'Rain', 'Thunder', 'Sky'],
        correct: 0,
        explanation: 'মেঘ (megh) = cloud. "গগনে গরজে মেঘ" = in the sky the clouds thunder.',
      },
      {
        id: 'sonar-tori-3',
        prompt: 'What does ছন্দ mean in Bengali poetry?',
        promptBn: 'ছন্দ শব্দের অর্থ কী?',
        options: ['Meter/rhythm', 'Rhyme', 'Stanza', 'Title'],
        correct: 0,
        explanation: 'ছন্দ (chhondo) = meter or rhythm. Bengali poetry uses various ছন্দ patterns.',
      },
    ],
  },

  // ─── 6. যেতে নাহি দিব ────────────────────────────────
  {
    id: 'jete-nahi-dibo',
    bengaliName: 'যেতে নাহি দিব',
    englishName: 'I Won\'t Let You Go',
    icon: '💕',
    tags: ['রবীন্দ্রকবিতা', 'Love'],
    poet: 'Rabindranath Tagore',
    poetBn: 'রবীন্দ্রনাথ ঠাকুর',
    year: '1900',
    descBn: 'যেতে নাহি দিব রবীন্দ্রনাথ ঠাকুরের একটি আবেগময় প্রেমের কবিতা। প্রিয়জনকে ছেড়ে দিতে না চাওয়ার আকুল ইচ্ছা এই কবিতায় মর্মস্পর্শীভাবে প্রকাশিত হয়েছে।',
    descEn: 'Jete Nahi Dibo (I Won\'t Let You Go) is one of Tagore\'s most passionate love poems. It expresses the desperate longing to hold on to a beloved, capturing the universal human fear of separation and loss.',
    versesBn: [
      'যেতে নাহি দিব, তোমায় যেতে নাহি দিব।',
      'ধরি দুই হাতে, আমি ধরি দুই হাতে,',
      'রাখিব বসায়ে এইখানে, আমার গানে।',
      'বাহিরে ঝড়ের রাতে',
      'অন্ধকারে দাঁড়ায়ে তুমি আমার দ্বারে,',
      'ফিরায়ে দিব না, আমি ফিরায়ে দিব না।',
    ],
    versesEn: [
      'I won\'t let you go, I won\'t let you go.',
      'I hold you with both hands, both hands,',
      'I will keep you seated here, in my song.',
      'Outside in the stormy night,',
      'standing in the darkness at my door,',
      'I will not turn you away, I will not.',
    ],
    quiz: [
      {
        id: 'jete-nahi-dibo-1',
        prompt: 'What does যেতে mean?',
        promptBn: 'যেতে শব্দের অর্থ কী?',
        options: ['To go', 'To come', 'To stay', 'To sing'],
        correct: 0,
        explanation: 'যেতে (jete) = to go. যেতে নাহি দিব = I won\'t let (you) go.',
      },
      {
        id: 'jete-nahi-dibo-2',
        prompt: 'What does ঝড় mean?',
        promptBn: 'ঝড় শব্দের ইংরেজি অর্থ কী?',
        options: ['Storm', 'Rain', 'Wind', 'Thunder'],
        correct: 0,
        explanation: 'ঝড় (jhor) = storm. "ঝড়ের রাতে" = on a stormy night.',
      },
      {
        id: 'jete-nahi-dibo-3',
        prompt: 'What does পদ্য mean in Bengali literature?',
        promptBn: 'পদ্য শব্দের অর্থ কী?',
        options: ['Poetry/verse', 'Prose', 'Drama', 'Novel'],
        correct: 0,
        explanation: 'পদ্য (poddo) = poetry or verse. The opposite is গদ্য (goddo) = prose.',
      },
    ],
  },

  // ─── 7. কান্ডারী হুঁশিয়ার ───────────────────────────
  {
    id: 'kandari-hushiar',
    bengaliName: 'কান্ডারী হুঁশিয়ার',
    englishName: 'Wake Up, Helmsman',
    icon: '⚓',
    tags: ['নজরুল', 'Revolutionary'],
    poet: 'Kazi Nazrul Islam',
    poetBn: 'কাজী নজরুল ইসলাম',
    year: '1922',
    descBn: 'কান্ডারী হুঁশিয়ার কাজী নজরুল ইসলামের একটি শক্তিশালী কবিতা। এতে জাতির কান্ডারী (নেতা)-কে সতর্ক হওয়ার আহ্বান জানানো হয়েছে। সাম্প্রদায়িকতা ও অন্যায়ের বিরুদ্ধে সচেতনতার বার্তা বহন করে এই কবিতা।',
    descEn: 'Kandari Hushiar (Wake Up, Helmsman) is a powerful poem by Kazi Nazrul Islam calling on the helmsman (leader) of the nation to be alert. It warns against communalism and injustice, urging unity and vigilance.',
    versesBn: [
      'দুর্গম গিরি কান্তার-মরু দুস্তর পারাবার',
      'লঙ্ঘিতে হবে রাত্রি নিশীথে যাত্রীরা হুঁশিয়ার!',
      'কান্ডারী! তব সম্মুখে ঐ পলাশীর প্রান্তর',
      'বাংলার বুকে শেলী-এর মতো জাগিয়া উঠিল কে?',
    ],
    versesEn: [
      'Treacherous mountains, burning deserts, impassable seas,',
      'must be crossed — travelers, be alert in the dead of night!',
      'Helmsman! Before you lies the field of Palashi,',
      'Who has risen in the heart of Bengal like Shelley?',
    ],
    quiz: [
      {
        id: 'kandari-hushiar-1',
        prompt: 'What does কান্ডারী mean?',
        promptBn: 'কান্ডারী শব্দের অর্থ কী?',
        options: ['Helmsman/leader', 'Soldier', 'Teacher', 'Sailor'],
        correct: 0,
        explanation: 'কান্ডারী (kandari) = helmsman or steersman. It metaphorically means the leader of a nation.',
      },
      {
        id: 'kandari-hushiar-2',
        prompt: 'What does হুঁশিয়ার mean?',
        promptBn: 'হুঁশিয়ার শব্দের ইংরেজি অর্থ কী?',
        options: ['Alert/beware', 'Brave', 'Happy', 'Quiet'],
        correct: 0,
        explanation: 'হুঁশিয়ার (hushiar) = alert, beware, be careful. "কান্ডারী হুঁশিয়ার" = helmsman, be alert!',
      },
      {
        id: 'kandari-hushiar-3',
        prompt: 'What does দুর্গম mean?',
        promptBn: 'দুর্গম শব্দের অর্থ কী?',
        options: ['Impassable/difficult', 'Easy', 'Beautiful', 'Distant'],
        correct: 0,
        explanation: 'দুর্গম (durgom) = impassable or difficult to traverse. দুর্গম গিরি = treacherous mountains.',
      },
    ],
  },

  // ─── 8. ছাড়পত্র ─────────────────────────────────────
  {
    id: 'chharpotra',
    bengaliName: 'ছাড়পত্র',
    englishName: 'A Release',
    icon: '🔥',
    tags: ['তরুণ', 'Revolutionary'],
    poet: 'Sukanta Bhattacharya',
    poetBn: 'সুকান্ত ভট্টাচার্য',
    year: '1947',
    descBn: 'ছাড়পত্র সুকান্ত ভট্টাচার্যের বিখ্যাত কবিতা। মাত্র ২১ বছর বয়সে মারা যাওয়া এই তরুণ কবি তাঁর কবিতায় অন্যায়ের বিরুদ্ধে তীব্র প্রতিবাদ করেছেন। এই কবিতায় তিনি নতুন প্রজন্মের কাছে পৃথিবী হস্তান্তরের কথা বলেছেন।',
    descEn: 'Chharpotra (A Release) is a famous poem by Sukanta Bhattacharya, who died at just 21. Known as the "poet of youth," he wrote fiercely against injustice. This poem speaks of handing over the world to a new generation — making it livable before the transfer.',
    versesBn: [
      'এ বিশ্বকে এ শিশুর বাসযোগ্য করে যাব আমি —',
      'নবজাতকের কাছে এ আমার দৃঢ় অঙ্গীকার।',
      'সাত-কোটি সন্তানের হে মুগ্ধ জননী,',
      'রেখো মা দামাল ছেলের দুর্নাম ইতিহাসে।',
    ],
    versesEn: [
      'I shall make this world livable for this child —',
      'this is my firm promise to the newborn.',
      'O enchanted mother of seventy million children,',
      'keep, Mother, the wild son\'s infamy in history.',
    ],
    quiz: [
      {
        id: 'chharpotra-1',
        prompt: 'What does বিশ্ব mean?',
        promptBn: 'বিশ্ব শব্দের ইংরেজি অর্থ কী?',
        options: ['World', 'Country', 'City', 'Village'],
        correct: 0,
        explanation: 'বিশ্ব (bishwo) = world. "এ বিশ্বকে" = this world.',
      },
      {
        id: 'chharpotra-2',
        prompt: 'What does শিশু mean?',
        promptBn: 'শিশু শব্দের অর্থ কী?',
        options: ['Child', 'Youth', 'Elder', 'Woman'],
        correct: 0,
        explanation: 'শিশু (shishu) = child. "এ শিশুর বাসযোগ্য" = livable for this child.',
      },
      {
        id: 'chharpotra-3',
        prompt: 'What does অঙ্গীকার mean?',
        promptBn: 'অঙ্গীকার শব্দের ইংরেজি অর্থ কী?',
        options: ['Promise/pledge', 'Request', 'Wish', 'Command'],
        correct: 0,
        explanation: 'অঙ্গীকার (ongikar) = promise or pledge. "দৃঢ় অঙ্গীকার" = firm promise.',
      },
    ],
  },

  // ─── 9. স্বাধীনতা তুমি ───────────────────────────────
  {
    id: 'shadhinota-tumi',
    bengaliName: 'স্বাধীনতা তুমি',
    englishName: 'Freedom, You Are',
    icon: '🕊️',
    tags: ['দেশাত্মবোধক', 'Modern'],
    poet: 'Shamsur Rahman',
    poetBn: 'শামসুর রাহমান',
    year: '1987',
    descBn: 'স্বাধীনতা তুমি শামসুর রাহমানের অন্যতম বিখ্যাত কবিতা। স্বাধীনতাকে বিভিন্ন রূপকে সংজ্ঞায়িত করা হয়েছে — পিতার মুখ, মায়ের আঁচল, বোনের হাসি। বাংলাদেশের স্বাধীনতা দিবসে এই কবিতা নিয়মিত পাঠ করা হয়।',
    descEn: 'Shadhinota Tumi (Freedom, You Are) is one of the most beloved poems in Bangladeshi literature by Shamsur Rahman. It defines freedom through vivid, personal metaphors — a father\'s face, a mother\'s sari, a sister\'s smile. It is recited every Independence Day in Bangladesh.',
    versesBn: [
      'স্বাধীনতা তুমি — রবিঠাকুরের অজর কবিতা,',
      'অবিনাশী গান।',
      'স্বাধীনতা তুমি — পিতার কোমল জায়নামাজের',
      'উদার জমিন।',
      'স্বাধীনতা তুমি — মায়ের কপালে তিলক রেখা,',
      'উঠোনে ছড়ানো রোদের সোনালি বিকেল।',
    ],
    versesEn: [
      'Freedom, you are — Tagore\'s ageless poetry,',
      'indestructible song.',
      'Freedom, you are — the generous ground of',
      'my father\'s soft prayer mat.',
      'Freedom, you are — the tilak mark on mother\'s forehead,',
      'the golden afternoon of sunlight scattered in the courtyard.',
    ],
    quiz: [
      {
        id: 'shadhinota-tumi-1',
        prompt: 'What does স্বাধীনতা mean?',
        promptBn: 'স্বাধীনতা শব্দের ইংরেজি অর্থ কী?',
        options: ['Freedom/independence', 'Peace', 'Love', 'Unity'],
        correct: 0,
        explanation: 'স্বাধীনতা (shadhinota) = freedom or independence. স্বাধীন (shadhin) = free.',
      },
      {
        id: 'shadhinota-tumi-2',
        prompt: 'What does অজর mean?',
        promptBn: 'অজর শব্দের অর্থ কী?',
        options: ['Ageless/immortal', 'Beautiful', 'Ancient', 'Forgotten'],
        correct: 0,
        explanation: 'অজর (ojor) = ageless or immortal. "অজর কবিতা" = ageless poetry.',
      },
      {
        id: 'shadhinota-tumi-3',
        prompt: 'What does কবিতা mean?',
        promptBn: 'কবিতা শব্দের ইংরেজি অর্থ কী?',
        options: ['Poem', 'Story', 'Song', 'Letter'],
        correct: 0,
        explanation: 'কবিতা (kobita) = poem. কবি (kobi) = poet, কবিতা (kobita) = poem.',
      },
    ],
  },

  // ─── 10. আমার পূর্ব বাংলা ────────────────────────────
  {
    id: 'amar-purbo-bangla',
    bengaliName: 'আমার পূর্ব বাংলা',
    englishName: 'My East Bengal',
    icon: '🌅',
    tags: ['দেশাত্মবোধক', 'Modern'],
    poet: 'Al Mahmud',
    poetBn: 'আল মাহমুদ',
    year: '1963',
    descBn: 'আমার পূর্ব বাংলা আল মাহমুদের একটি বিখ্যাত দেশাত্মবোধক কবিতা। পূর্ব বাংলার (বর্তমান বাংলাদেশ) প্রকৃতি, মানুষ ও সংস্কৃতির প্রতি গভীর ভালোবাসা এই কবিতায় প্রকাশিত।',
    descEn: 'Amar Purbo Bangla (My East Bengal) is a famous patriotic poem by Al Mahmud, one of the most important modern Bengali poets. It expresses deep affection for East Bengal (now Bangladesh) — its nature, people, and culture.',
    versesBn: [
      'আমার পূর্ব বাংলা, তুমি কি আমার?',
      'তোমার সবুজ মাঠ, তোমার ধানের ক্ষেত,',
      'তোমার নদীর জল, তোমার আকাশের নীল,',
      'সব কিছু আমার প্রাণের ভেতর।',
    ],
    versesEn: [
      'My East Bengal, are you mine?',
      'Your green fields, your paddy lands,',
      'Your river waters, your blue skies,',
      'Everything lives within my soul.',
    ],
    quiz: [
      {
        id: 'amar-purbo-bangla-1',
        prompt: 'What does পূর্ব mean?',
        promptBn: 'পূর্ব শব্দের ইংরেজি অর্থ কী?',
        options: ['East', 'West', 'North', 'South'],
        correct: 0,
        explanation: 'পূর্ব (purbo) = east. পূর্ব বাংলা = East Bengal (now Bangladesh).',
      },
      {
        id: 'amar-purbo-bangla-2',
        prompt: 'What does সবুজ mean?',
        promptBn: 'সবুজ শব্দের অর্থ কী?',
        options: ['Green', 'Blue', 'Yellow', 'Red'],
        correct: 0,
        explanation: 'সবুজ (shobuj) = green. "সবুজ মাঠ" = green fields.',
      },
      {
        id: 'amar-purbo-bangla-3',
        prompt: 'What does প্রাণ mean?',
        promptBn: 'প্রাণ শব্দের ইংরেজি অর্থ কী?',
        options: ['Life/soul', 'Heart', 'Mind', 'Body'],
        correct: 0,
        explanation: 'প্রাণ (pran) = life or soul. "আমার প্রাণের ভেতর" = within my soul.',
      },
    ],
  },
];

export { POETRY };
