/* ── proverbs.js — Bengali proverbs & idioms data + quiz questions ── */

const PROVERBS = [
  // ─── 1. জ্ঞান ও শিক্ষা ───────────────────────────────
  {
    id: 'wisdom-learning',
    bengaliName: 'জ্ঞান ও শিক্ষা',
    englishName: 'Wisdom & Learning',
    icon: '📚',
    tags: ['জ্ঞান', 'Education'],
    descBn: 'বাংলায় জ্ঞান ও শিক্ষা সম্পর্কে অনেক প্রবাদ আছে। এগুলো শিক্ষার গুরুত্ব, জ্ঞান অর্জনের মূল্য এবং বিদ্যার শক্তি সম্পর্কে শিক্ষা দেয়।',
    descEn: 'Bengali culture has many proverbs about wisdom and learning. These sayings emphasize the importance of education, the value of acquiring knowledge, and the power of wisdom.',
    proverbsBn: [
      'অল্প বিদ্যা ভয়ঙ্করী।',
      'বিদ্যাই শ্রেষ্ঠ ধন।',
      'না জানলে শেখো, না বুঝলে জিজ্ঞেস করো।',
      'গাছ তোমায় ছায়া দেবে, বই তোমায় জ্ঞান দেবে।',
      'শিক্ষা জাতির মেরুদণ্ড।',
    ],
    proverbsEn: [
      'A little knowledge is a dangerous thing.',
      'Knowledge is the greatest wealth.',
      'If you don\'t know, learn; if you don\'t understand, ask.',
      'A tree gives you shade, a book gives you knowledge.',
      'Education is the backbone of a nation.',
    ],
    quiz: [
      {
        id: 'wisdom-learning-1',
        prompt: 'What does বিদ্যা mean?',
        promptBn: 'বিদ্যা শব্দের ইংরেজি অর্থ কী?',
        options: ['Knowledge/education', 'Wealth', 'Power', 'Wisdom'],
        correct: 0,
        explanation: 'বিদ্যা (bidya) = knowledge or education. "বিদ্যাই শ্রেষ্ঠ ধন" = knowledge is the greatest wealth.',
      },
      {
        id: 'wisdom-learning-2',
        prompt: 'What does ভয়ঙ্করী mean in "অল্প বিদ্যা ভয়ঙ্করী"?',
        promptBn: '"অল্প বিদ্যা ভয়ঙ্করী"-তে ভয়ঙ্করী শব্দের অর্থ কী?',
        options: ['Dangerous', 'Beautiful', 'Useful', 'Powerful'],
        correct: 0,
        explanation: 'ভয়ঙ্করী (bhoyongkori) = dangerous. অল্প (a little) + বিদ্যা (knowledge) = dangerous.',
      },
      {
        id: 'wisdom-learning-3',
        prompt: 'What does শিক্ষা mean?',
        promptBn: 'শিক্ষা শব্দের ইংরেজি অর্থ কী?',
        options: ['Education', 'Money', 'Food', 'Shelter'],
        correct: 0,
        explanation: 'শিক্ষা (shikkha) = education. "শিক্ষা জাতির মেরুদণ্ড" = education is the backbone of a nation.',
      },
    ],
  },

  // ─── 2. কর্ম ও পরিশ্রম ──────────────────────────────
  {
    id: 'work-effort',
    bengaliName: 'কর্ম ও পরিশ্রম',
    englishName: 'Work & Effort',
    icon: '💪',
    tags: ['পরিশ্রম', 'Diligence'],
    descBn: 'পরিশ্রম ও কর্মনিষ্ঠা সম্পর্কে বাংলা প্রবাদগুলো কঠোর পরিশ্রমের মূল্য এবং অলসতার বিপদ সম্পর্কে শিক্ষা দেয়।',
    descEn: 'Bengali proverbs about work and effort teach the value of hard work and the dangers of laziness. They encourage persistence and diligence.',
    proverbsBn: [
      'পরিশ্রম সৌভাগ্যের প্রসূতি।',
      'আলসের অমাবস্যা।',
      'করিতে পারি না কাজ, সকলি অবেলায়।',
      'একবার না পারিলে দেখ শতবার।',
      'চেষ্টা করলে কেষ্টা মেলে।',
    ],
    proverbsEn: [
      'Hard work is the mother of good fortune.',
      'For the lazy, it\'s always a dark night (no-moon day).',
      'Can\'t get work done — it\'s always the wrong time.',
      'If you don\'t succeed once, try a hundred times.',
      'If you try, you\'ll find God (success comes with effort).',
    ],
    quiz: [
      {
        id: 'work-effort-1',
        prompt: 'What does পরিশ্রম mean?',
        promptBn: 'পরিশ্রম শব্দের ইংরেজি অর্থ কী?',
        options: ['Hard work', 'Rest', 'Luck', 'Sleep'],
        correct: 0,
        explanation: 'পরিশ্রম (porishrom) = hard work or labor. "পরিশ্রম সৌভাগ্যের প্রসূতি" = hard work is the mother of fortune.',
      },
      {
        id: 'work-effort-2',
        prompt: 'What does সৌভাগ্য mean?',
        promptBn: 'সৌভাগ্য শব্দের অর্থ কী?',
        options: ['Good fortune', 'Misfortune', 'Wealth', 'Health'],
        correct: 0,
        explanation: 'সৌভাগ্য (shoubhagyo) = good fortune or luck.',
      },
      {
        id: 'work-effort-3',
        prompt: 'What does চেষ্টা mean?',
        promptBn: 'চেষ্টা শব্দের ইংরেজি অর্থ কী?',
        options: ['Effort/try', 'Wish', 'Dream', 'Prayer'],
        correct: 0,
        explanation: 'চেষ্টা (cheshta) = effort or attempt. "চেষ্টা করলে কেষ্টা মেলে" = effort brings success.',
      },
    ],
  },

  // ─── 3. বন্ধুত্ব ও সম্পর্ক ──────────────────────────
  {
    id: 'friendship-relationships',
    bengaliName: 'বন্ধুত্ব ও সম্পর্ক',
    englishName: 'Friendship & Relationships',
    icon: '🤝',
    tags: ['সম্পর্ক', 'Social'],
    descBn: 'বন্ধুত্ব ও সম্পর্ক নিয়ে বাংলা প্রবাদগুলো মানুষের পারস্পরিক সম্পর্কের গুরুত্ব, বিশ্বস্ততা এবং সামাজিক বন্ধনের কথা বলে।',
    descEn: 'Bengali proverbs about friendship and relationships speak about the importance of human bonds, loyalty, and the nature of social connections.',
    proverbsBn: [
      'সৎ সঙ্গে স্বর্গবাস, অসৎ সঙ্গে সর্বনাশ।',
      'দূরের মানুষ কাছে এলে ভালো লাগে।',
      'আপন ভালো পাগলেও বোঝে।',
      'চেনা বামুনের পৈতা লাগে না।',
      'রক্তের চেয়ে বন্ধুত্ব গাঢ়।',
    ],
    proverbsEn: [
      'Good company leads to heaven, bad company to ruin.',
      'Distant people feel pleasant when they come close.',
      'Even a fool understands their own good.',
      'A familiar priest needs no introduction.',
      'Friendship is thicker than blood.',
    ],
    quiz: [
      {
        id: 'friendship-relationships-1',
        prompt: 'What does সঙ্গ mean in "সৎ সঙ্গে স্বর্গবাস"?',
        promptBn: '"সৎ সঙ্গে স্বর্গবাস"-এ সঙ্গ শব্দের অর্থ কী?',
        options: ['Company/association', 'Place', 'Road', 'Home'],
        correct: 0,
        explanation: 'সঙ্গ (shongo) = company or association. সৎ সঙ্গ = good company.',
      },
      {
        id: 'friendship-relationships-2',
        prompt: 'What does বন্ধুত্ব mean?',
        promptBn: 'বন্ধুত্ব শব্দের ইংরেজি অর্থ কী?',
        options: ['Friendship', 'Enmity', 'Brotherhood', 'Partnership'],
        correct: 0,
        explanation: 'বন্ধুত্ব (bondhutto) = friendship. বন্ধু (friend) → বন্ধুত্ব (friendship).',
      },
      {
        id: 'friendship-relationships-3',
        prompt: 'What does সর্বনাশ mean?',
        promptBn: 'সর্বনাশ শব্দের অর্থ কী?',
        options: ['Ruin/destruction', 'Happiness', 'Success', 'Peace'],
        correct: 0,
        explanation: 'সর্বনাশ (shorbonash) = ruin or total destruction. সর্ব (all) + নাশ (destruction).',
      },
    ],
  },

  // ─── 4. সময় ও ধৈর্য ─────────────────────────────────
  {
    id: 'time-patience',
    bengaliName: 'সময় ও ধৈর্য',
    englishName: 'Time & Patience',
    icon: '⏳',
    tags: ['সময়', 'Patience'],
    descBn: 'সময় ও ধৈর্যের গুরুত্ব সম্পর্কে বাংলায় অনেক প্রবাদ আছে। এগুলো সময়ের মূল্য এবং ধৈর্যের ফলাফল সম্পর্কে শিক্ষা দেয়।',
    descEn: 'Bengali proverbs about time and patience teach the value of time, the rewards of patience, and the importance of acting at the right moment.',
    proverbsBn: [
      'সময় ও স্রোত কারো জন্য অপেক্ষা করে না।',
      'ধৈর্য ধরো, ফল পাবে।',
      'সময়ের এক ফোঁড়, অসময়ের দশ ফোঁড়।',
      'আজকের কাজ কালের জন্য ফেলো না।',
      'ধীরে ধীরে বটগাছ হয়।',
    ],
    proverbsEn: [
      'Time and tide wait for no one.',
      'Be patient, and you will be rewarded.',
      'A stitch in time saves nine.',
      'Don\'t put off today\'s work for tomorrow.',
      'Slowly, slowly, a banyan tree grows.',
    ],
    quiz: [
      {
        id: 'time-patience-1',
        prompt: 'What does সময় mean?',
        promptBn: 'সময় শব্দের ইংরেজি অর্থ কী?',
        options: ['Time', 'Space', 'Speed', 'Moment'],
        correct: 0,
        explanation: 'সময় (shomoy) = time. "সময় কারো জন্য অপেক্ষা করে না" = time waits for no one.',
      },
      {
        id: 'time-patience-2',
        prompt: 'What does ধৈর্য mean?',
        promptBn: 'ধৈর্য শব্দের অর্থ কী?',
        options: ['Patience', 'Courage', 'Anger', 'Speed'],
        correct: 0,
        explanation: 'ধৈর্য (dhoirjo) = patience. "ধৈর্য ধরো" = be patient / have patience.',
      },
      {
        id: 'time-patience-3',
        prompt: 'What does ফল mean in "ফল পাবে"?',
        promptBn: '"ফল পাবে"-তে ফল শব্দের অর্থ কী?',
        options: ['Result/reward', 'Fruit', 'Flower', 'Gift'],
        correct: 0,
        explanation: 'ফল (fol) = result or fruit. Here it means reward: "ফল পাবে" = you will get the reward.',
      },
    ],
  },

  // ─── 5. টাকাপয়সা ও সম্পদ ────────────────────────────
  {
    id: 'money-wealth',
    bengaliName: 'টাকাপয়সা ও সম্পদ',
    englishName: 'Money & Wealth',
    icon: '💰',
    tags: ['অর্থ', 'Finance'],
    descBn: 'টাকাপয়সা ও সম্পদ নিয়ে বাংলা প্রবাদগুলো অর্থের সঠিক ব্যবহার, মিতব্যয়িতা এবং লোভের বিপদ সম্পর্কে শিক্ষা দেয়।',
    descEn: 'Bengali proverbs about money and wealth teach about the proper use of money, frugality, and the dangers of greed.',
    proverbsBn: [
      'পয়সা পয়সা করে, লাখ টাকা হয়।',
      'অভাবে স্বভাব নষ্ট।',
      'লোভে পাপ, পাপে মৃত্যু।',
      'টাকায় টাকা আনে।',
      'পুকুর চুরি করতে পারবে, কিন্তু পানি লুকাতে পারবে না।',
    ],
    proverbsEn: [
      'Penny by penny, a fortune is made.',
      'Poverty corrupts character.',
      'Greed leads to sin, sin leads to death.',
      'Money begets money.',
      'You can steal a pond, but you can\'t hide the water.',
    ],
    quiz: [
      {
        id: 'money-wealth-1',
        prompt: 'What does টাকা mean?',
        promptBn: 'টাকা শব্দের ইংরেজি অর্থ কী?',
        options: ['Money', 'Coin', 'Gold', 'Bank'],
        correct: 0,
        explanation: 'টাকা (taka) = money. It is also the currency unit of Bangladesh.',
      },
      {
        id: 'money-wealth-2',
        prompt: 'What does লোভ mean?',
        promptBn: 'লোভ শব্দের অর্থ কী?',
        options: ['Greed', 'Love', 'Fear', 'Anger'],
        correct: 0,
        explanation: 'লোভ (lobh) = greed. "লোভে পাপ" = greed leads to sin.',
      },
      {
        id: 'money-wealth-3',
        prompt: 'What does অভাব mean?',
        promptBn: 'অভাব শব্দের ইংরেজি অর্থ কী?',
        options: ['Poverty/lack', 'Abundance', 'Wealth', 'Comfort'],
        correct: 0,
        explanation: 'অভাব (obhab) = poverty or lack. "অভাবে স্বভাব নষ্ট" = poverty corrupts character.',
      },
    ],
  },

  // ─── 6. প্রকৃতি ও আবহাওয়া ──────────────────────────
  {
    id: 'nature-weather',
    bengaliName: 'প্রকৃতি ও আবহাওয়া',
    englishName: 'Nature & Weather',
    icon: '🌦️',
    tags: ['প্রকৃতি', 'Weather'],
    descBn: 'বাংলাদেশ ষড়ঋতুর দেশ। প্রকৃতি ও আবহাওয়া নিয়ে অনেক প্রবাদ আছে যা কৃষিজীবী মানুষের দীর্ঘ অভিজ্ঞতা থেকে এসেছে।',
    descEn: 'Bangladesh is a land of six seasons. Many proverbs about nature and weather come from the long experience of agricultural people who depend on the climate for their livelihood.',
    proverbsBn: [
      'আষাঢ়ে গর্জন, শ্রাবণে বর্ষণ।',
      'নদীর একূল ভাঙে, ওকূল গড়ে।',
      'চৈত্রে বৃষ্টি, বোশেখে ফাঁকা।',
      'বিশ্বাস হলে ভাসাও, না হলে আশ্বাস।',
      'পানির নিচে মাটি, মাটির নিচে পানি।',
    ],
    proverbsEn: [
      'Thunder in Asharh, rain in Shraban (seasons dictate weather).',
      'The river erodes one bank and builds the other.',
      'Rain in Choitro, dry in Boishakh.',
      'Trust and you float; otherwise, just reassurance.',
      'Water beneath soil, soil beneath water.',
    ],
    quiz: [
      {
        id: 'nature-weather-1',
        prompt: 'What does প্রকৃতি mean?',
        promptBn: 'প্রকৃতি শব্দের ইংরেজি অর্থ কী?',
        options: ['Nature', 'Weather', 'Season', 'Environment'],
        correct: 0,
        explanation: 'প্রকৃতি (prokriti) = nature. বাংলাদেশের প্রকৃতি অসাধারণ।',
      },
      {
        id: 'nature-weather-2',
        prompt: 'What does নদী mean?',
        promptBn: 'নদী শব্দের অর্থ কী?',
        options: ['River', 'Sea', 'Lake', 'Pond'],
        correct: 0,
        explanation: 'নদী (nodi) = river. Bangladesh is known as "নদীমাতৃক দেশ" (land of rivers).',
      },
      {
        id: 'nature-weather-3',
        prompt: 'What does বৃষ্টি mean?',
        promptBn: 'বৃষ্টি শব্দের ইংরেজি অর্থ কী?',
        options: ['Rain', 'Snow', 'Wind', 'Cloud'],
        correct: 0,
        explanation: 'বৃষ্টি (brishti) = rain. বর্ষণ (borshon) also means rainfall.',
      },
    ],
  },

  // ─── 7. খাদ্য ও স্বাস্থ্য ───────────────────────────
  {
    id: 'food-health',
    bengaliName: 'খাদ্য ও স্বাস্থ্য',
    englishName: 'Food & Health',
    icon: '🍚',
    tags: ['স্বাস্থ্য', 'Food'],
    descBn: 'খাদ্য ও স্বাস্থ্য নিয়ে বাংলা প্রবাদগুলো সুস্থ থাকার উপায়, পরিমিত আহার এবং জীবনযাপনের নিয়ম সম্পর্কে শিক্ষা দেয়।',
    descEn: 'Bengali proverbs about food and health teach about staying healthy, eating in moderation, and the rules of daily living.',
    proverbsBn: [
      'মাছে ভাতে বাঙালি।',
      'স্বাস্থ্যই সম্পদ।',
      'যত খাবে ভাত, তত বাড়বে শক্তি — কথাটা সত্যি নয়!',
      'রোগের চেয়ে প্রতিরোধ ভালো।',
      'অতি ভোজনে রোগ, পরিমিত ভোজনে আরোগ্য।',
    ],
    proverbsEn: [
      'Bengalis live on fish and rice.',
      'Health is wealth.',
      'The more rice you eat, the stronger you get — not true!',
      'Prevention is better than cure.',
      'Overeating brings disease, moderation brings health.',
    ],
    quiz: [
      {
        id: 'food-health-1',
        prompt: 'What does স্বাস্থ্য mean?',
        promptBn: 'স্বাস্থ্য শব্দের ইংরেজি অর্থ কী?',
        options: ['Health', 'Wealth', 'Strength', 'Food'],
        correct: 0,
        explanation: 'স্বাস্থ্য (shastho) = health. "স্বাস্থ্যই সম্পদ" = health is wealth.',
      },
      {
        id: 'food-health-2',
        prompt: 'What does মাছ mean?',
        promptBn: 'মাছ শব্দের অর্থ কী?',
        options: ['Fish', 'Meat', 'Rice', 'Vegetable'],
        correct: 0,
        explanation: 'মাছ (machh) = fish. "মাছে ভাতে বাঙালি" = Bengalis live on fish and rice.',
      },
      {
        id: 'food-health-3',
        prompt: 'What does রোগ mean?',
        promptBn: 'রোগ শব্দের ইংরেজি অর্থ কী?',
        options: ['Disease', 'Medicine', 'Doctor', 'Pain'],
        correct: 0,
        explanation: 'রোগ (rog) = disease or illness. প্রতিরোধ (protirodh) = prevention.',
      },
    ],
  },

  // ─── 8. সততা ও নৈতিকতা ──────────────────────────────
  {
    id: 'honesty-morality',
    bengaliName: 'সততা ও নৈতিকতা',
    englishName: 'Honesty & Morality',
    icon: '⚖️',
    tags: ['নীতি', 'Ethics'],
    descBn: 'সততা ও নৈতিকতা নিয়ে বাংলা প্রবাদগুলো সত্যবাদিতা, ন্যায়পরায়ণতা এবং চরিত্রের গুরুত্ব সম্পর্কে শিক্ষা দেয়।',
    descEn: 'Bengali proverbs about honesty and morality teach about truthfulness, justice, and the importance of good character.',
    proverbsBn: [
      'সততাই সর্বোৎকৃষ্ট পন্থা।',
      'পাপের ধন প্রায়শ্চিত্তে যায়।',
      'চোরা না শোনে ধর্মের কাহিনি।',
      'মিথ্যার পা নেই — দৌড়াতে পারে না।',
      'ন্যায়ের পথ কঠিন, কিন্তু সঠিক।',
    ],
    proverbsEn: [
      'Honesty is the best policy.',
      'Ill-gotten wealth goes in penance.',
      'A thief never listens to moral tales.',
      'A lie has no legs — it cannot run.',
      'The path of justice is hard, but right.',
    ],
    quiz: [
      {
        id: 'honesty-morality-1',
        prompt: 'What does সততা mean?',
        promptBn: 'সততা শব্দের ইংরেজি অর্থ কী?',
        options: ['Honesty', 'Bravery', 'Kindness', 'Wisdom'],
        correct: 0,
        explanation: 'সততা (shotota) = honesty. "সততাই সর্বোৎকৃষ্ট পন্থা" = honesty is the best policy.',
      },
      {
        id: 'honesty-morality-2',
        prompt: 'What does মিথ্যা mean?',
        promptBn: 'মিথ্যা শব্দের অর্থ কী?',
        options: ['Lie/falsehood', 'Truth', 'Story', 'Rumor'],
        correct: 0,
        explanation: 'মিথ্যা (mittha) = lie or falsehood. The opposite is সত্য (shotto) = truth.',
      },
      {
        id: 'honesty-morality-3',
        prompt: 'What does ন্যায় mean?',
        promptBn: 'ন্যায় শব্দের ইংরেজি অর্থ কী?',
        options: ['Justice', 'Law', 'Punishment', 'Reward'],
        correct: 0,
        explanation: 'ন্যায় (nyay) = justice. "ন্যায়ের পথ" = the path of justice.',
      },
    ],
  },

  // ─── 9. পরিবার ও ঘর ─────────────────────────────────
  {
    id: 'family-home',
    bengaliName: 'পরিবার ও ঘর',
    englishName: 'Family & Home',
    icon: '🏠',
    tags: ['পরিবার', 'Family'],
    descBn: 'পরিবার ও ঘর নিয়ে বাংলা প্রবাদগুলো পারিবারিক বন্ধন, ঘরের গুরুত্ব এবং পরিবারের সদস্যদের মধ্যে সম্পর্কের কথা বলে।',
    descEn: 'Bengali proverbs about family and home speak about family bonds, the importance of home, and relationships between family members.',
    proverbsBn: [
      'ঘরের খেয়ে বনের মোষ তাড়ানো।',
      'মা-বাবার দোয়া সন্তানের শ্রেষ্ঠ সম্পদ।',
      'নিজের ঘর পরের ঘরের চেয়ে ভালো।',
      'ঘরের শত্রু বিভীষণ।',
      'রক্ত পানি হয় না।',
    ],
    proverbsEn: [
      'Eating at home while chasing wild buffalo (meddling in others\' affairs).',
      'Parents\' blessings are a child\'s greatest treasure.',
      'One\'s own home is better than another\'s.',
      'The enemy within is the most dangerous (Bibhishana = a family traitor).',
      'Blood doesn\'t turn to water (family bonds endure).',
    ],
    quiz: [
      {
        id: 'family-home-1',
        prompt: 'What does পরিবার mean?',
        promptBn: 'পরিবার শব্দের ইংরেজি অর্থ কী?',
        options: ['Family', 'House', 'Village', 'Neighbor'],
        correct: 0,
        explanation: 'পরিবার (poribar) = family. বাংলা সংস্কৃতিতে পরিবার অত্যন্ত গুরুত্বপূর্ণ।',
      },
      {
        id: 'family-home-2',
        prompt: 'What does ঘর mean?',
        promptBn: 'ঘর শব্দের অর্থ কী?',
        options: ['Home/house', 'Room', 'Village', 'Garden'],
        correct: 0,
        explanation: 'ঘর (ghor) = home or house. "নিজের ঘর পরের ঘরের চেয়ে ভালো" = one\'s own home is best.',
      },
      {
        id: 'family-home-3',
        prompt: 'What does সন্তান mean?',
        promptBn: 'সন্তান শব্দের ইংরেজি অর্থ কী?',
        options: ['Child/offspring', 'Parent', 'Sibling', 'Spouse'],
        correct: 0,
        explanation: 'সন্তান (shontan) = child or offspring.',
      },
    ],
  },

  // ─── 10. সাহস ও সংকল্প ──────────────────────────────
  {
    id: 'courage-determination',
    bengaliName: 'সাহস ও সংকল্প',
    englishName: 'Courage & Determination',
    icon: '🦁',
    tags: ['সাহস', 'Determination'],
    descBn: 'সাহস ও সংকল্প নিয়ে বাংলা প্রবাদগুলো সাহসিকতা, দৃঢ়তা এবং ভয়কে জয় করার প্রেরণা দেয়।',
    descEn: 'Bengali proverbs about courage and determination inspire bravery, firmness, and overcoming fear.',
    proverbsBn: [
      'ভয়কে জয় করাই সবচেয়ে বড় জয়।',
      'যে ভয় পায়, সে হার মানে।',
      'সাহসী হও, সফল হবে।',
      'একবার লড়ে হারলে, আবার লড়ো।',
      'পথ কঠিন বলে কেউ থামে না।',
    ],
    proverbsEn: [
      'Conquering fear is the greatest victory.',
      'He who fears has already lost.',
      'Be brave, and you will succeed.',
      'If you fight and lose once, fight again.',
      'No one stops because the path is hard.',
    ],
    quiz: [
      {
        id: 'courage-determination-1',
        prompt: 'What does সাহস mean?',
        promptBn: 'সাহস শব্দের ইংরেজি অর্থ কী?',
        options: ['Courage', 'Fear', 'Strength', 'Speed'],
        correct: 0,
        explanation: 'সাহস (shahosh) = courage or bravery.',
      },
      {
        id: 'courage-determination-2',
        prompt: 'What does ভয় mean?',
        promptBn: 'ভয় শব্দের অর্থ কী?',
        options: ['Fear', 'Courage', 'Anger', 'Joy'],
        correct: 0,
        explanation: 'ভয় (bhoy) = fear. "ভয়কে জয় করা" = to conquer fear.',
      },
      {
        id: 'courage-determination-3',
        prompt: 'What does সংকল্প mean?',
        promptBn: 'সংকল্প শব্দের ইংরেজি অর্থ কী?',
        options: ['Determination/resolve', 'Dream', 'Wish', 'Promise'],
        correct: 0,
        explanation: 'সংকল্প (shonkolpo) = determination or resolve.',
      },
    ],
  },
];

export { PROVERBS };
