/* ── recipes.js — Bengali recipe data + quiz questions ──────────── */

const RECIPES = [
  // ─── 1. Aloo Posto ─────────────────────────────────────────────
  {
    id: 'aloo-posto',
    bengaliName: 'আলু পোস্তো',
    englishName: 'Potatoes in Poppy Seeds',
    icon: '🥔',
    tags: ['নিরামিষ', 'West Bengal'],
    descBn: 'আলু পোস্তো পশ্চিমবঙ্গের একটি জনপ্রিয় নিরামিষ পদ। সাদা পোস্ত বাটা ও সরিষার তেলে রান্না করা নরম আলুর এই পদটি সহজ কিন্তু অত্যন্ত সুস্বাদু। এটি সাধারণত ভাতের সাথে খাওয়া হয়।',
    descEn: 'Aloo Posto is a classic Bengali vegetarian dish from West Bengal. It features tender potato cubes cooked in a mild paste of white poppy seeds, typically tempered in mustard oil. With minimal spices, this simple recipe relies on technique and ingredients to make a comforting everyday meal.',
    ingredientsBn: [
      '৫০০ গ্রাম আলু (খোসা ছাড়িয়ে কিউব করে কাটা)',
      '২৫ গ্রাম সাদা পোস্ত',
      '১ চা চামচ কালোজিরা',
      '২–৩টি কাঁচা লঙ্কা (চেরা)',
      '১টি শুকনো লাল লঙ্কা',
      '২ টেবিল চামচ সরিষার তেল',
      '৫ মি.লি. (১ চা চামচ) হলুদ গুঁড়ো',
      '৫ গ্রাম লবণ (স্বাদমতো)',
      '১০০ মি.লি. পানি',
    ],
    ingredientsEn: [
      '500 g potatoes (peeled and diced)',
      '25 g white poppy seeds (posto dana)',
      '1 teaspoon nigella seeds (kalonji)',
      '2–3 green chilies (slit)',
      '1 red chili (whole)',
      '2 tablespoons mustard oil',
      '5 ml (1 tsp) turmeric powder',
      '5 g salt (adjust to taste)',
      '100 ml water (as needed)',
    ],
    stepsBn: [
      'পোস্ত ও ১টি কাঁচা লঙ্কা সামান্য পানি দিয়ে মিহি করে বেটে নিন।',
      'কড়াইয়ে সরিষার তেল গরম করে কালোজিরা ও শুকনো লাল লঙ্কা ফোড়ন দিন।',
      'আলু, হলুদ ও লবণ দিয়ে ভালোভাবে নেড়ে নিন।',
      'পোস্ত বাটা ও পানি যোগ করে ঢেকে অল্প আঁচে রান্না করুন।',
      'আলু সেদ্ধ হলে নামিয়ে ভাতের সাথে পরিবেশন করুন।',
    ],
    stepsEn: [
      'Grind the poppy seeds with 1 green chili into a smooth paste, adding a little water if needed.',
      'Heat mustard oil in a pan. Add nigella seeds and the whole red chili; stir until fragrant.',
      'Add the diced potatoes, turmeric, and salt. Stir well to coat the potatoes with oil and spices.',
      'Add the poppy-seed paste and 100 ml water. Mix and cover the pan. Cook on low heat until the potatoes are tender.',
      'Check seasoning, then remove from heat. Serve hot with rice or flatbreads.',
    ],
    quiz: [
      {
        id: 'aloo-posto-1',
        prompt: 'What does আলু mean?',
        promptBn: 'আলু শব্দের ইংরেজি অর্থ কী?',
        options: ['Potato', 'Rice', 'Lentil', 'Onion'],
        correct: 0,
        explanation: 'আলু (aloo) means potato — the main ingredient in আলু পোস্তো!',
      },
      {
        id: 'aloo-posto-2',
        prompt: 'What does বাটা mean in "পোস্ত বাটা"?',
        promptBn: '"পোস্ত বাটা"-তে বাটা শব্দের অর্থ কী?',
        options: ['Ground/paste', 'Fried', 'Boiled', 'Sliced'],
        correct: 0,
        explanation: 'বাটা (bata) means ground into a paste. পোস্ত বাটা = ground poppy seed paste.',
      },
      {
        id: 'aloo-posto-3',
        prompt: 'Which oil is traditionally used in আলু পোস্তো?',
        promptBn: 'আলু পোস্তোতে ঐতিহ্যগতভাবে কোন তেল ব্যবহার করা হয়?',
        options: ['Mustard oil', 'Olive oil', 'Coconut oil', 'Sunflower oil'],
        correct: 0,
        explanation: 'সরিষার তেল (sorsher tel) = mustard oil, the signature cooking fat of Bengali cuisine.',
      },
    ],
  },

  // ─── 2. Shukto ─────────────────────────────────────────────────
  {
    id: 'shukto',
    bengaliName: 'শুকতো',
    englishName: 'Mixed Vegetable Curry',
    icon: '🥬',
    tags: ['নিরামিষ', 'West Bengal'],
    descBn: 'শুকতো বাঙালির ঐতিহ্যবাহী মিশ্র সবজির পদ। এতে করলা, আলু, বেগুন, কাঁচা কলা ইত্যাদি সবজি ব্যবহার করা হয়।',
    descEn: 'Shukto is a traditional Bengali mixed-vegetable curry, often served as the first course of a meal. It combines assorted vegetables cooked in a lightly spiced sauce flavored with mustard oil and panch phoron (Bengali five-spice mix).',
    ingredientsBn: [
      'মিশ্র সবজি (প্রতিটি প্রায় ১০০ গ্রাম)',
      '২ টেবিল চামচ সরিষার তেল',
      '১টি তেজপাতা',
      '১ চা চামচ জিরা',
      '১ চা চামচ মৌরি',
      '½ চা চামচ কালোজিরা',
      '½ চা চামচ মেথি',
      '½ কাপ কোরানো নারকেল',
      '১ টেবিল চামচ পোস্ত',
      '১ টেবিল চামচ সরিষা',
      '১ চা চামচ হলুদ',
      '১ চা চামচ চিনি',
      '৫ গ্রাম লবণ',
      '৩০০ মি.লি. পানি',
    ],
    ingredientsEn: [
      'Mixed vegetables (each ~100 g): bitter gourd, eggplant, potato, etc.',
      '2 tablespoons mustard oil',
      '1 bay leaf',
      '1 teaspoon whole cumin seeds',
      '1 teaspoon fennel seeds',
      '½ teaspoon nigella seeds',
      '½ teaspoon fenugreek seeds (panch phoron spices)',
      '½ cup grated coconut',
      '1 tablespoon poppy seeds',
      '1 tablespoon mustard seeds',
      '1 teaspoon turmeric powder',
      '1 teaspoon sugar (or jaggery)',
      '5 g salt (to taste)',
      '300 ml water',
    ],
    stepsBn: [
      'সবজি সমান আকারে কেটে নিন।',
      'নারকেল, পোস্ত ও সরিষা বেটে পেস্ট তৈরি করুন।',
      'তেলে তেজপাতা ও সব মশলা ফোড়ন দিন।',
      'সবজি দিয়ে নেড়ে হলুদ, লবণ ও চিনি দিন।',
      'বাটা মশলা ও পানি যোগ করে ঢেকে দিন।',
      'সবজি সেদ্ধ হলে পরিবেশন করুন।',
    ],
    stepsEn: [
      'Wash and cut all vegetables into similar-sized pieces.',
      'Grind coconut, poppy seeds, and mustard seeds with a little water into a smooth paste.',
      'Heat mustard oil in a pan. Add the bay leaf and all the whole panch phoron spices; sauté briefly.',
      'Add the vegetables and stir for a few minutes.',
      'Sprinkle turmeric, salt, and sugar; mix. Add the ground paste and water. Stir well.',
      'Cover and simmer on low heat until the vegetables are fully cooked. Serve hot with rice.',
    ],
    quiz: [
      {
        id: 'shukto-1',
        prompt: 'What does সবজি mean?',
        promptBn: 'সবজি শব্দের ইংরেজি অর্থ কী?',
        options: ['Vegetables', 'Meat', 'Spices', 'Fish'],
        correct: 0,
        explanation: 'সবজি (shobji) means vegetables. শুকতো is a mixed vegetable (মিশ্র সবজি) curry.',
      },
      {
        id: 'shukto-2',
        prompt: 'What does ফোড়ন mean in Bengali cooking?',
        promptBn: 'রান্নায় ফোড়ন বলতে কী বোঝায়?',
        options: ['Tempering spices in hot oil', 'Boiling in water', 'Grinding to paste', 'Baking in an oven'],
        correct: 0,
        explanation: 'ফোড়ন (phoron) = tempering — blooming whole spices in hot oil to release their flavor.',
      },
      {
        id: 'shukto-3',
        prompt: 'What does নারকেল mean?',
        promptBn: 'নারকেল শব্দের ইংরেজি অর্থ কী?',
        options: ['Coconut', 'Almond', 'Peanut', 'Cashew'],
        correct: 0,
        explanation: 'নারকেল (narkel) = coconut. Grated coconut is ground into the paste for শুকতো.',
      },
    ],
  },

  // ─── 3. Kosha Mangsho ──────────────────────────────────────────
  {
    id: 'kosha-mangsho',
    bengaliName: 'কষা মাংস',
    englishName: 'Slow-Cooked Mutton',
    icon: '🍖',
    tags: ['আমিষ', 'West Bengal'],
    descBn: 'কষা মাংস একটি জনপ্রিয় বাঙালি মাটনের পদ। ধীরে রান্না করার ফলে মাংস নরম ও ঝোল ঘন হয়।',
    descEn: 'Kosha Mangsho is a beloved Bengali mutton curry, known for its rich, dark gravy and tender meat. The term "kosha" refers to the slow-braising technique that caramelizes onions and spices.',
    ingredientsBn: [
      '৫০০ গ্রাম খাসির মাংস',
      '২ টেবিল চামচ সরিষার তেল',
      '২টি বড় পেঁয়াজ (কুচি)',
      '১ টেবিল চামচ আদা বাটা',
      '১ টেবিল চামচ রসুন বাটা',
      '১টি কাঁচা লঙ্কা',
      '১০০ গ্রাম টক দই',
      '½ চা চামচ হলুদ',
      '১ চা চামচ জিরা গুঁড়ো',
      '১ চা চামচ ধনে গুঁড়ো',
      '১ চা চামচ লাল লঙ্কা গুঁড়ো',
      '১ চা চামচ গরম মশলা',
      '৫ গ্রাম লবণ',
      '২ টেবিল চামচ ঘি',
    ],
    ingredientsEn: [
      '500 g goat meat (mutton), cut into pieces',
      '2 tablespoons mustard oil',
      '2 large onions (finely sliced)',
      '1 tablespoon ginger paste',
      '1 tablespoon garlic paste',
      '1 green chili (slit)',
      '100 g plain yogurt',
      '½ teaspoon turmeric powder',
      '1 teaspoon cumin powder',
      '1 teaspoon coriander powder',
      '1 teaspoon red chili powder',
      '1 teaspoon garam masala powder',
      '5 g salt (to taste)',
      '2 tablespoons ghee (clarified butter)',
    ],
    stepsBn: [
      'মাংস দই ও মশলা দিয়ে ১–২ ঘণ্টা মেরিনেট করুন।',
      'তেলে পেঁয়াজ বাদামী হওয়া পর্যন্ত ভাজুন।',
      'আদা-রসুন বাটা দিন।',
      'মাংস দিয়ে ভালোভাবে কষান।',
      'সামান্য পানি দিয়ে ঢেকে অল্প আঁচে ১–১.৫ ঘণ্টা রান্না করুন।',
      'শেষে গরম মশলা দিয়ে পরিবেশন করুন।',
    ],
    stepsEn: [
      'Marinate the meat with yogurt, turmeric, cumin, coriander, red chili powder, and a pinch of salt for 1–2 hours.',
      'Heat mustard oil and ghee in a deep pot. Sauté sliced onions slowly until deep brown and caramelized.',
      'Add ginger-garlic paste and green chili; cook for 2–3 minutes until the raw smell disappears.',
      'Add the marinated mutton and brown it on all sides.',
      'Sprinkle salt, pour in a little water. Cover and simmer on very low heat for 1–1.5 hours until tender.',
      'Stir in garam masala, adjust seasoning, and serve hot with rice, paratha, or luchi.',
    ],
    quiz: [
      {
        id: 'kosha-mangsho-1',
        prompt: 'What does মাংস mean?',
        promptBn: 'মাংস শব্দের ইংরেজি অর্থ কী?',
        options: ['Meat', 'Fish', 'Rice', 'Bread'],
        correct: 0,
        explanation: 'মাংস (mangsho) = meat. কষা মাংস literally means "braised meat."',
      },
      {
        id: 'kosha-mangsho-2',
        prompt: 'What does কষানো mean as a cooking technique?',
        promptBn: 'রান্নার পদ্ধতি হিসেবে কষানো-র অর্থ কী?',
        options: ['Slow braising/reducing', 'Deep frying', 'Steaming', 'Baking'],
        correct: 0,
        explanation: 'কষানো (koshano) = slow braising on low heat until the gravy thickens and oils separate.',
      },
      {
        id: 'kosha-mangsho-3',
        prompt: 'What is দই in this recipe?',
        promptBn: 'এই রেসিপিতে দই কী?',
        options: ['Yogurt', 'Cream', 'Milk', 'Butter'],
        correct: 0,
        explanation: 'দই (doi) = yogurt. The mutton is marinated in টক দই (sour yogurt) before cooking.',
      },
    ],
  },

  // ─── 4. Sandesh ─────────────────────────────────────────────────
  {
    id: 'sandesh',
    bengaliName: 'সন্দেশ',
    englishName: 'Bengali Cheese Fudge',
    icon: '🍬',
    tags: ['মিষ্টি', 'West Bengal'],
    descBn: 'সন্দেশ ছানা ও চিনি দিয়ে তৈরি একটি বিখ্যাত বাঙালি মিষ্টি।',
    descEn: 'Sandesh is a popular Bengali sweet made with fresh chhena (cottage cheese) and sugar. It is often flavored with cardamom or saffron and shaped into decorative forms.',
    ingredientsBn: [
      '২৫০ গ্রাম ছানা',
      '৫০ গ্রাম চিনি গুঁড়ো',
      '¼ চা চামচ এলাচ গুঁড়ো',
      'সামান্য জাফরান (ঐচ্ছিক)',
      '১ চা চামচ দুধ (প্রয়োজনে)',
    ],
    ingredientsEn: [
      '250 g fresh chhena (cottage cheese)',
      '50 g powdered sugar (adjust to taste)',
      '¼ teaspoon cardamom powder',
      'A pinch of saffron strands (optional)',
      '1 teaspoon milk (if needed to bind)',
    ],
    stepsBn: [
      'ছানা ভালোভাবে মেখে নিন।',
      'নন-স্টিক প্যানে অল্প আঁচে নেড়ে গরম করুন।',
      'চিনি দিয়ে মিশ্রণটি ডো-এর মতো হলে নামান।',
      'এলাচ মিশিয়ে আকার দিন।',
      'ঠান্ডা হলে পরিবেশন করুন।',
    ],
    stepsEn: [
      'Crumble or knead the chhena until it is smooth and free of lumps.',
      'Place the chhena in a non-stick pan over low heat and gently cook, stirring constantly.',
      'Add the sugar and continue stirring until the mixture becomes dough-like.',
      'Mix in the cardamom powder (and saffron if using). Shape into small discs or desired shapes.',
      'Let the Sandesh cool and set. Serve at room temperature or chilled.',
    ],
    quiz: [
      {
        id: 'sandesh-1',
        prompt: 'What is ছানা?',
        promptBn: 'ছানা কী?',
        options: ['Fresh cottage cheese', 'Flour', 'Cream', 'Yogurt'],
        correct: 0,
        explanation: 'ছানা (chhena) = fresh cottage cheese made by curdling milk. It is the base of many Bengali sweets.',
      },
      {
        id: 'sandesh-2',
        prompt: 'What does মেখে নেওয়া mean?',
        promptBn: 'মেখে নেওয়া বলতে কী বোঝায়?',
        options: ['To knead', 'To fry', 'To boil', 'To slice'],
        correct: 0,
        explanation: 'মেখে নেওয়া (mekhe neowa) = to knead. The ছানা is kneaded smooth before cooking.',
      },
      {
        id: 'sandesh-3',
        prompt: 'What is এলাচ?',
        promptBn: 'এলাচ কী?',
        options: ['Cardamom', 'Cinnamon', 'Clove', 'Nutmeg'],
        correct: 0,
        explanation: 'এলাচ (elach) = cardamom. It adds a warm, aromatic flavor to সন্দেশ.',
      },
    ],
  },

  // ─── 5. Mishti Doi ──────────────────────────────────────────────
  {
    id: 'mishti-doi',
    bengaliName: 'মিষ্টি দই',
    englishName: 'Sweet Fermented Yogurt',
    icon: '🍯',
    tags: ['মিষ্টি', 'Bangladesh'],
    descBn: 'মিষ্টি দই বাংলাদেশে খুব জনপ্রিয়।',
    descEn: 'Mishti Doi is a traditional sweet yogurt from Bengal (especially Bangladesh). It is made by fermenting thickened milk sweetened with jaggery and is set in clay pots.',
    ingredientsBn: [
      '৫০০ মি.লি. দুধ',
      '৫০ গ্রাম খেজুরের গুড়',
      '২ টেবিল চামচ টক দই',
      '¼ চা চামচ এলাচ (ঐচ্ছিক)',
    ],
    ingredientsEn: [
      '500 ml whole milk',
      '50 g palm jaggery (date palm sugar, "nolen gur")',
      '2 tablespoons plain yogurt (for starter culture)',
      '¼ teaspoon cardamom powder (optional)',
    ],
    stepsBn: [
      'দুধ জ্বাল দিয়ে কমিয়ে নিন।',
      'হালকা গরম হলে গুড় মিশান।',
      'দই মিশিয়ে পাত্রে ঢালুন।',
      '৬–১২ ঘণ্টা গরম স্থানে রেখে জমতে দিন।',
      'ফ্রিজে রেখে ঠান্ডা পরিবেশন করুন।',
    ],
    stepsEn: [
      'Boil the milk and reduce it by about one-third, stirring to prevent burning.',
      'Remove from heat and let cool until warm. Dissolve the jaggery into the warm milk.',
      'Mix in the yogurt starter until fully incorporated.',
      'Pour into a clean pot or clay bowl. Keep in a warm place for 6–12 hours until set.',
      'Once set, refrigerate. Serve the Mishti Doi cold as a dessert.',
    ],
    quiz: [
      {
        id: 'mishti-doi-1',
        prompt: 'What does গুড় mean?',
        promptBn: 'গুড় শব্দের ইংরেজি অর্থ কী?',
        options: ['Jaggery (unrefined sugar)', 'Honey', 'White sugar', 'Syrup'],
        correct: 0,
        explanation: 'গুড় (gur) = jaggery, an unrefined sugar. খেজুরের গুড় = date palm jaggery, giving মিষ্টি দই its distinctive caramel flavor.',
      },
      {
        id: 'mishti-doi-2',
        prompt: 'What does জ্বাল দেওয়া mean?',
        promptBn: 'জ্বাল দেওয়া মানে কী?',
        options: ['To boil/simmer', 'To fry', 'To freeze', 'To grind'],
        correct: 0,
        explanation: 'জ্বাল দেওয়া (jhal deowa) = to boil or simmer. The milk is boiled down to thicken it.',
      },
      {
        id: 'mishti-doi-3',
        prompt: 'What is দুধ?',
        promptBn: 'দুধ কী?',
        options: ['Milk', 'Water', 'Cream', 'Oil'],
        correct: 0,
        explanation: 'দুধ (dudh) = milk. It is the primary ingredient in মিষ্টি দই.',
      },
    ],
  },

  // ─── 6. Shorshe Ilish ──────────────────────────────────────────
  {
    id: 'shorshe-ilish',
    bengaliName: 'সরষে ইলিশ',
    englishName: 'Hilsa Fish in Mustard',
    icon: '🐟',
    tags: ['আমিষ', 'Bangladesh'],
    descBn: 'সরিষা বাটা দিয়ে রান্না করা ইলিশ বাংলাদেশের ঐতিহ্যবাহী পদ।',
    descEn: 'Shorshe Ilish is a classic Bengali fish curry from Bangladesh, featuring hilsa (ilish) fish cooked in a mustard sauce with mustard oil and green chilies.',
    ingredientsBn: [
      '৪ টুকরা ইলিশ (প্রায় ২০০ গ্রাম করে)',
      '৪ টেবিল চামচ সরিষা বাটা',
      '৩ টেবিল চামচ সরিষার তেল',
      '২–৩টি কাঁচা লঙ্কা',
      '½ চা চামচ হলুদ',
      '৫ গ্রাম লবণ',
      '১০০ মি.লি. পানি',
    ],
    ingredientsEn: [
      '4 pieces hilsa fish (ilish), about 200 g each',
      '4 tablespoons mustard seeds (ground to a paste)',
      '3 tablespoons mustard oil',
      '2–3 green chilies',
      '½ teaspoon turmeric powder',
      '5 g salt (or to taste)',
      '100 ml water',
    ],
    stepsBn: [
      'সরিষা ও কাঁচা লঙ্কা বেটে নিন।',
      'তেলে মাছ হালকা ভেজে তুলুন।',
      'সরিষা বাটা ও মশলা দিয়ে পানি দিন।',
      'মাছ দিয়ে ঢেকে ৭–১০ মিনিট রান্না করুন।',
      'ভাতের সাথে পরিবেশন করুন।',
    ],
    stepsEn: [
      'Grind the mustard seeds with 2 green chilies into a fine paste.',
      'Heat mustard oil in a pan. Fry the fish pieces gently on both sides until lightly seared. Set aside.',
      'In the same oil, add the mustard paste. Stir for a minute.',
      'Add turmeric, salt, and water. Return the fish to the pan. Cover and cook on low heat for 7–10 minutes.',
      'Garnish with remaining green chilies. Serve hot with rice.',
    ],
    quiz: [
      {
        id: 'shorshe-ilish-1',
        prompt: 'What does ইলিশ mean?',
        promptBn: 'ইলিশ শব্দের ইংরেজি অর্থ কী?',
        options: ['Hilsa fish', 'Prawn', 'Catfish', 'Salmon'],
        correct: 0,
        explanation: 'ইলিশ (ilish) = hilsa, a prized silver fish of Bengal, often called the "king of fish."',
      },
      {
        id: 'shorshe-ilish-2',
        prompt: 'What does ভেজে তোলা mean?',
        promptBn: 'ভেজে তোলা মানে কী?',
        options: ['To fry and remove', 'To boil and strain', 'To marinate', 'To steam'],
        correct: 0,
        explanation: 'ভেজে তোলা (bheje tola) = to fry and remove from the pan. The fish is lightly fried before being added to the sauce.',
      },
      {
        id: 'shorshe-ilish-3',
        prompt: 'What is সরিষা?',
        promptBn: 'সরিষা কী?',
        options: ['Mustard', 'Cumin', 'Turmeric', 'Chili'],
        correct: 0,
        explanation: 'সরিষা (shorshey) = mustard. সরষে ইলিশ is named for the সরিষা বাটা (mustard paste) that defines the dish.',
      },
    ],
  },

  // ─── 7. Chingri Malai Curry ────────────────────────────────────
  {
    id: 'chingri-malai',
    bengaliName: 'চিংড়ি মালাই কারি',
    englishName: 'Prawn Coconut Curry',
    icon: '🦐',
    tags: ['আমিষ', 'Bengali'],
    descBn: 'নারকেল দুধে রান্না করা একটি উৎসবের পদ।',
    descEn: 'Chingri Malai Curry is a festive Bengali prawn curry cooked in creamy coconut milk. Large prawns are simmered in a mildly spiced coconut-milk sauce for a rich yet subtle flavor.',
    ingredientsBn: [
      '৩০০ গ্রাম বড় চিংড়ি',
      '২ টেবিল চামচ সরিষার তেল',
      '১টি বড় পেঁয়াজ',
      '১ টেবিল চামচ আদা বাটা',
      '১ টেবিল চামচ রসুন বাটা',
      '২০০ মি.লি. নারকেল দুধ',
      '½ চা চামচ হলুদ',
      '৫ গ্রাম লবণ',
      '১ চা চামচ চিনি',
    ],
    ingredientsEn: [
      '300 g large prawns (cleaned and deveined)',
      '2 tablespoons mustard oil',
      '1 large onion (sliced)',
      '1 tablespoon ginger paste',
      '1 tablespoon garlic paste',
      '200 ml coconut milk',
      '½ teaspoon turmeric powder',
      '5 g salt (to taste)',
      '1 teaspoon sugar',
    ],
    stepsBn: [
      'তেলে পেঁয়াজ ভাজুন।',
      'আদা-রসুন দিয়ে নেড়ে চিংড়ি দিন।',
      'নারকেল দুধ ও মশলা দিয়ে ৩–৫ মিনিট রান্না করুন।',
      'গরম পরিবেশন করুন।',
    ],
    stepsEn: [
      'Heat mustard oil in a pan. Sauté the sliced onion until soft.',
      'Add ginger-garlic paste and green chili; cook for 1–2 minutes. Add the prawns and stir.',
      'Pour in the coconut milk and water. Add turmeric, salt, and sugar. Simmer for 3–5 minutes.',
      'Adjust salt. Serve Chingri Malai Curry hot with rice.',
    ],
    quiz: [
      {
        id: 'chingri-malai-1',
        prompt: 'What does চিংড়ি mean?',
        promptBn: 'চিংড়ি শব্দের ইংরেজি অর্থ কী?',
        options: ['Prawn/shrimp', 'Fish', 'Crab', 'Lobster'],
        correct: 0,
        explanation: 'চিংড়ি (chingri) = prawn or shrimp, the star protein in this coconut curry.',
      },
      {
        id: 'chingri-malai-2',
        prompt: 'What does পেঁয়াজ ভাজা mean?',
        promptBn: 'পেঁয়াজ ভাজা মানে কী?',
        options: ['Frying onions', 'Boiling onions', 'Slicing onions', 'Grinding onions'],
        correct: 0,
        explanation: 'ভাজা (bhaja) = to fry. পেঁয়াজ ভাজা = frying onions, the first step in many Bengali curries.',
      },
      {
        id: 'chingri-malai-3',
        prompt: 'What liquid gives this curry its creamy base?',
        promptBn: 'কোন তরল এই তরকারির ক্রিমি ভিত্তি তৈরি করে?',
        options: ['Coconut milk', 'Milk', 'Water', 'Broth'],
        correct: 0,
        explanation: 'নারকেল দুধ (narkel dudh) = coconut milk. "মালাই" in the name refers to this creamy coconut sauce.',
      },
    ],
  },

  // ─── 8. Dhokar Dalna ───────────────────────────────────────────
  {
    id: 'dhokar-dalna',
    bengaliName: 'ঢোকা দালনা',
    englishName: 'Lentil Cake Curry',
    icon: '🫘',
    tags: ['নিরামিষ', 'Bangladesh'],
    descBn: 'চানা ডাল দিয়ে তৈরি ভাজা ঢোকা মশলাদার ঝোলে রান্না করা হয়।',
    descEn: 'Dhokar Dalna is a traditional Bengali vegetarian curry made with fried lentil cakes in a spiced gravy. The diamond-shaped cakes (dhoka), made from ground chana dal, are simmered in a rich curry.',
    ingredientsBn: [
      '২০০ গ্রাম চানা ডাল',
      '৩টি কাঁচা লঙ্কা',
      '½ কাপ নারকেল কোরানো',
      '২ টেবিল চামচ সরিষার তেল',
      '½ চা চামচ জিরা',
      '১ চা চামচ আদা বাটা',
      '১ চা চামচ হলুদ',
      '৫ গ্রাম লবণ',
      '৫০০ মি.লি. পানি',
    ],
    ingredientsEn: [
      '200 g chana dal (split chickpeas)',
      '3 green chilies',
      '½ cup grated coconut',
      '2 tablespoons mustard oil',
      '½ teaspoon cumin seeds',
      '1 teaspoon ginger paste',
      '1 teaspoon turmeric powder',
      '5 g salt',
      '500 ml water (for gravy)',
    ],
    stepsBn: [
      'ডাল ভিজিয়ে বেটে নিন।',
      'আকার দিয়ে ভেজে নিন।',
      'ফোড়ন দিয়ে ঝোল তৈরি করুন।',
      'ঢোকা দিয়ে ৫–৭ মিনিট রান্না করুন।',
      'ভাতের সাথে পরিবেশন করুন।',
    ],
    stepsEn: [
      'Soak chana dal for 2 hours. Grind coarsely with green chilies, adding a little water.',
      'Shape into small flat diamond-shaped cakes. Fry until golden brown.',
      'In the same oil, add cumin seeds and spices; sauté. Pour in water and bring to a simmer.',
      'Add fried dhokas and grated coconut. Cover and cook for 5–7 minutes.',
      'Adjust salt. Serve hot with rice.',
    ],
    quiz: [
      {
        id: 'dhokar-dalna-1',
        prompt: 'What does ডাল mean?',
        promptBn: 'ডাল শব্দের ইংরেজি অর্থ কী?',
        options: ['Lentil', 'Rice', 'Wheat', 'Corn'],
        correct: 0,
        explanation: 'ডাল (dal) = lentil. চানা ডাল = split chickpea lentil, used to make the fried cakes.',
      },
      {
        id: 'dhokar-dalna-2',
        prompt: 'What does ভেজে নেওয়া mean?',
        promptBn: 'ভেজে নেওয়া মানে কী?',
        options: ['To fry', 'To soak', 'To boil', 'To bake'],
        correct: 0,
        explanation: 'ভেজে নেওয়া (bheje neowa) = to fry. The lentil cakes are fried until golden before adding to the curry.',
      },
      {
        id: 'dhokar-dalna-3',
        prompt: 'What does ঝোল mean?',
        promptBn: 'ঝোল মানে কী?',
        options: ['Gravy/broth', 'Dry spice mix', 'Salad', 'Pickle'],
        correct: 0,
        explanation: 'ঝোল (jhol) = gravy or thin broth/curry. The fried ঢোকা are simmered in a spiced ঝোল.',
      },
    ],
  },

  // ─── 9. Panta Bhat ─────────────────────────────────────────────
  {
    id: 'panta-bhat',
    bengaliName: 'পান্তা ভাত',
    englishName: 'Fermented Rice',
    icon: '🍚',
    tags: ['নিরামিষ', 'Bangladesh'],
    descBn: 'পান্তা ভাত গরমকালে খুব জনপ্রিয়।',
    descEn: 'Panta Bhat is a traditional fermented rice dish popular in Bangladesh and rural Bengal. It is simply cooked rice soaked overnight in water, allowing natural fermentation. The resulting sour, chilled rice is refreshing and nutritious.',
    ingredientsBn: [
      '২০০ গ্রাম রান্না করা ভাত',
      'পানি (ডুবানোর জন্য)',
      'লবণ',
      '১–২টি কাঁচা লঙ্কা',
    ],
    ingredientsEn: [
      '200 g cooked rice (preferably parboiled rice)',
      'Water (enough to cover the rice)',
      'Salt (to taste)',
      '1–2 green chilies (chopped)',
    ],
    stepsBn: [
      'ভাত পানি দিয়ে রাতভর ভিজিয়ে রাখুন।',
      'সকালে পানি ঝরিয়ে লবণ ও লঙ্কা মিশিয়ে পরিবেশন করুন।',
    ],
    stepsEn: [
      'Take leftover cooked rice. Place in a bowl and cover completely with water. Leave at room temperature overnight (8–12 hours) to ferment.',
      'Before eating, drain most of the water. Mix in salt and chopped green chilies. Serve cold with sliced onion, lemon, or fried fish on the side.',
    ],
    quiz: [
      {
        id: 'panta-bhat-1',
        prompt: 'What does ভাত mean?',
        promptBn: 'ভাত শব্দের ইংরেজি অর্থ কী?',
        options: ['Cooked rice', 'Bread', 'Noodles', 'Porridge'],
        correct: 0,
        explanation: 'ভাত (bhat) = cooked rice. It is the staple food of Bengal.',
      },
      {
        id: 'panta-bhat-2',
        prompt: 'What does ভিজিয়ে রাখা mean?',
        promptBn: 'ভিজিয়ে রাখা মানে কী?',
        options: ['To soak/leave soaking', 'To fry', 'To bake', 'To grind'],
        correct: 0,
        explanation: 'ভিজিয়ে রাখা (bhijiye rakha) = to soak/leave soaking. The rice ferments overnight in water.',
      },
      {
        id: 'panta-bhat-3',
        prompt: 'What does লবণ mean?',
        promptBn: 'লবণ শব্দের ইংরেজি অর্থ কী?',
        options: ['Salt', 'Sugar', 'Pepper', 'Vinegar'],
        correct: 0,
        explanation: 'লবণ (lobon) = salt. It is mixed in before serving পান্তা ভাত.',
      },
    ],
  },

  // ─── 10. Rasgulla ──────────────────────────────────────────────
  {
    id: 'rasgulla',
    bengaliName: 'রসগোল্লা',
    englishName: 'Spongy Cheese Balls in Syrup',
    icon: '🧁',
    tags: ['মিষ্টি', 'Bengali'],
    descBn: 'রসগোল্লা একটি বিখ্যাত বাঙালি মিষ্টি।',
    descEn: 'Rasgulla (rosogolla) is a famous Bengali sweet dumpling made from fresh chhena (cottage cheese) cooked in light sugar syrup. The soft white balls absorb the sweet syrup and become light and spongy.',
    ingredientsBn: [
      '২৫০ গ্রাম ছানা',
      '১ লিটার পানি',
      '২৫০ গ্রাম চিনি',
      '¼ চা চামচ এলাচ',
      '১ চা চামচ গোলাপ জল (ঐচ্ছিক)',
    ],
    ingredientsEn: [
      '250 g fresh chhena (paneer)',
      '1 liter water',
      '250 g sugar',
      '¼ teaspoon cardamom powder',
      '1 teaspoon rose water (optional)',
    ],
    stepsBn: [
      'ছানা মেখে বল তৈরি করুন।',
      'চিনি ও পানি ফুটিয়ে সিরা বানান।',
      'বলগুলো দিয়ে ৮–১০ মিনিট ফুটান।',
      'সিরায় ভিজিয়ে ঠান্ডা পরিবেশন করুন।',
    ],
    stepsEn: [
      'Knead the chhena into a smooth dough. Divide into small balls and roll them smooth.',
      'In a large pot, bring water and sugar to a boil to make syrup.',
      'Carefully add the chhena balls, cover, and cook on medium heat for 8–10 minutes. They will expand.',
      'Add cardamom powder and rose water. Let the rasgullas soak in syrup. Serve chilled.',
    ],
    quiz: [
      {
        id: 'rasgulla-1',
        prompt: 'What does চিনি mean?',
        promptBn: 'চিনি শব্দের ইংরেজি অর্থ কী?',
        options: ['Sugar', 'Salt', 'Flour', 'Honey'],
        correct: 0,
        explanation: 'চিনি (chini) = sugar. The সিরা (syrup) for রসগোল্লা is made from চিনি and water.',
      },
      {
        id: 'rasgulla-2',
        prompt: 'What does ফোটানো/ফুটানো mean?',
        promptBn: 'ফোটানো/ফুটানো মানে কী?',
        options: ['To boil', 'To fry', 'To bake', 'To freeze'],
        correct: 0,
        explanation: 'ফোটানো (photano) = to boil. The ছানা balls are boiled in sugar syrup until they expand.',
      },
      {
        id: 'rasgulla-3',
        prompt: 'What is সিরা in this recipe?',
        promptBn: 'এই রেসিপিতে সিরা কী?',
        options: ['Sugar syrup', 'Milk', 'Honey glaze', 'Coconut milk'],
        correct: 0,
        explanation: 'সিরা (shira) = sugar syrup. রসগোল্লা literally means "juice balls" — balls soaked in sweet সিরা.',
      },
    ],
  },
];

export { RECIPES };
