/* ── sports.js — Bengali sports data + quiz questions ──────────── */

const SPORTS = [
  // ─── 1. ক্রিকেট ──────────────────────────────────────
  {
    id: 'cricket',
    bengaliName: 'ক্রিকেট',
    englishName: 'Cricket',
    icon: '🏏',
    tags: ['জনপ্রিয়', 'Team Sport'],
    descBn: 'ক্রিকেট বাংলাদেশের সবচেয়ে জনপ্রিয় খেলা। বাংলাদেশ ২০০০ সালে টেস্ট মর্যাদা পায় এবং ২০১৫ সালে বিশ্বকাপে কোয়ার্টার ফাইনালে পৌঁছায়। বাংলাদেশি ক্রিকেট দল "টাইগার্স" নামে পরিচিত।',
    descEn: 'Cricket is the most popular sport in Bangladesh. The national team gained Test status in 2000 and reached the Cricket World Cup quarter-finals in 2015. Known as the "Tigers," the team has become a competitive force in world cricket.',
    factsBn: [
      'বাংলাদেশ ক্রিকেট দলকে "টাইগার্স" বলা হয়।',
      '২০০০ সালে বাংলাদেশ ICC-র দশম টেস্ট দেশ হয়।',
      'শেরেবাংলা স্টেডিয়াম ঢাকায় অবস্থিত।',
      'বাংলাদেশ ২০১১ সালে বিশ্বকাপের যৌথ আয়োজক ছিল।',
    ],
    factsEn: [
      'The Bangladesh cricket team is called the "Tigers."',
      'Bangladesh became the 10th ICC Test nation in 2000.',
      'Shere Bangla Stadium is located in Dhaka.',
      'Bangladesh co-hosted the 2011 Cricket World Cup.',
    ],
    quiz: [
      {
        id: 'cricket-1',
        prompt: 'What does খেলা mean?',
        promptBn: 'খেলা শব্দের ইংরেজি অর্থ কী?',
        options: ['Game/sport', 'Dance', 'Song', 'Fight'],
        correct: 0,
        explanation: 'খেলা (khela) = game or sport. ক্রিকেট একটি জনপ্রিয় খেলা।',
      },
      {
        id: 'cricket-2',
        prompt: 'What does দল mean in sports?',
        promptBn: 'খেলাধুলায় দল শব্দের অর্থ কী?',
        options: ['Team', 'Player', 'Coach', 'Stadium'],
        correct: 0,
        explanation: 'দল (dol) = team or group. বাংলাদেশ দল = Bangladesh team.',
      },
      {
        id: 'cricket-3',
        prompt: 'When did Bangladesh gain Test cricket status?',
        promptBn: 'বাংলাদেশ কখন টেস্ট ক্রিকেট মর্যাদা পায়?',
        options: ['2000', '1995', '2005', '2010'],
        correct: 0,
        explanation: 'Bangladesh became the 10th ICC Test nation in 2000 (২০০০ সাল)।',
      },
    ],
  },

  // ─── 2. কাবাডি ────────────────────────────────────────
  {
    id: 'kabaddi',
    bengaliName: 'কাবাডি',
    englishName: 'Kabaddi',
    icon: '🤼',
    tags: ['ঐতিহ্যবাহী', 'Contact Sport'],
    descBn: 'কাবাডি দক্ষিণ এশিয়ার একটি প্রাচীন যোগাযোগমূলক খেলা। খেলোয়াড়কে একদমে "কাবাডি কাবাডি" বলতে বলতে প্রতিপক্ষের মাঠে গিয়ে স্পর্শ করে ফিরে আসতে হয়। বাংলাদেশে এটি জাতীয় খেলা।',
    descEn: 'Kabaddi is an ancient contact sport from South Asia. A raider must enter the opponent\'s half, tag defenders, and return — all while chanting "kabaddi." It is the national sport of Bangladesh and is played widely across rural Bengal.',
    factsBn: [
      'কাবাডি বাংলাদেশের জাতীয় খেলা।',
      'এক রেইডার প্রতিপক্ষ দলে ঢুকে স্পর্শ করে ফেরত আসে।',
      'খেলার সময় "কাবাডি কাবাডি" বলতে হয়।',
      'এশিয়ান গেমসে কাবাডি অন্তর্ভুক্ত।',
    ],
    factsEn: [
      'Kabaddi is the national sport of Bangladesh.',
      'A raider enters the opponent\'s side, tags defenders, and returns.',
      'The raider must chant "kabaddi" continuously.',
      'Kabaddi is included in the Asian Games.',
    ],
    quiz: [
      {
        id: 'kabaddi-1',
        prompt: 'What does জাতীয় খেলা mean?',
        promptBn: 'জাতীয় খেলা-র অর্থ কী?',
        options: ['National sport', 'Popular sport', 'Traditional sport', 'Indoor sport'],
        correct: 0,
        explanation: 'জাতীয় (jatiyo) = national, খেলা (khela) = sport. জাতীয় খেলা = national sport.',
      },
      {
        id: 'kabaddi-2',
        prompt: 'What must the raider chant during kabaddi?',
        promptBn: 'কাবাডি খেলায় রেইডারকে কী বলতে হয়?',
        options: ['"Kabaddi kabaddi"', '"Ha-du-du"', '"Ready ready"', '"Go go go"'],
        correct: 0,
        explanation: 'The raider must continuously chant "কাবাডি কাবাডি" in one breath during the raid.',
      },
      {
        id: 'kabaddi-3',
        prompt: 'What does প্রতিপক্ষ mean?',
        promptBn: 'প্রতিপক্ষ শব্দের অর্থ কী?',
        options: ['Opponent', 'Teammate', 'Referee', 'Coach'],
        correct: 0,
        explanation: 'প্রতিপক্ষ (protipokho) = opponent or rival.',
      },
    ],
  },

  // ─── 3. ফুটবল ────────────────────────────────────────
  {
    id: 'football',
    bengaliName: 'ফুটবল',
    englishName: 'Football',
    icon: '⚽',
    tags: ['জনপ্রিয়', 'Team Sport'],
    descBn: 'ফুটবল বাংলায় অত্যন্ত জনপ্রিয় একটি খেলা। কলকাতার মোহনবাগান ও ইস্টবেঙ্গল ক্লাবের প্রতিদ্বন্দ্বিতা বিশ্বের প্রাচীনতম ফুটবল ডার্বিগুলোর একটি। ১৯১১ সালে মোহনবাগান আইএফএ শিল্ড জিতে ইতিহাস সৃষ্টি করে।',
    descEn: 'Football is hugely popular in Bengal. The Mohun Bagan vs East Bengal rivalry is one of the oldest football derbies in the world. In 1911, Mohun Bagan made history by becoming the first Indian team to win the IFA Shield, defeating the British East York Regiment.',
    factsBn: [
      '১৯১১ সালে মোহনবাগান IFA শিল্ড জেতে — প্রথম ভারতীয় দল।',
      'কলকাতা ডার্বি বিশ্বের প্রাচীনতম ফুটবল ডার্বিগুলোর একটি।',
      'বাংলাদেশের ফুটবল লিগের নাম বাংলাদেশ প্রিমিয়ার লিগ।',
      'ফুটবল খেলায় ১১ জন খেলোয়াড় থাকে প্রতি দলে।',
    ],
    factsEn: [
      'In 1911, Mohun Bagan won the IFA Shield — the first Indian team to do so.',
      'The Kolkata Derby is one of the oldest football derbies in the world.',
      'Bangladesh\'s football league is called the Bangladesh Premier League.',
      'Football has 11 players per team.',
    ],
    quiz: [
      {
        id: 'football-1',
        prompt: 'What does জয় mean in sports?',
        promptBn: 'খেলাধুলায় জয় শব্দের অর্থ কী?',
        options: ['Victory/win', 'Defeat', 'Draw', 'Goal'],
        correct: 0,
        explanation: 'জয় (joy) = victory or win. "মোহনবাগান জয় পেল" = Mohun Bagan won.',
      },
      {
        id: 'football-2',
        prompt: 'What does হার mean in sports?',
        promptBn: 'খেলাধুলায় হার শব্দের অর্থ কী?',
        options: ['Defeat/loss', 'Victory', 'Draw', 'Score'],
        correct: 0,
        explanation: 'হার (har) = defeat or loss. The opposite of জয় (victory).',
      },
      {
        id: 'football-3',
        prompt: 'What does খেলোয়াড় mean?',
        promptBn: 'খেলোয়াড় শব্দের ইংরেজি অর্থ কী?',
        options: ['Player', 'Coach', 'Referee', 'Fan'],
        correct: 0,
        explanation: 'খেলোয়াড় (kheloar) = player. খেলা (game) → খেলোয়াড় (one who plays).',
      },
    ],
  },

  // ─── 4. হকি ───────────────────────────────────────────
  {
    id: 'hockey',
    bengaliName: 'হকি',
    englishName: 'Hockey',
    icon: '🏑',
    tags: ['ক্ষেত্র খেলা', 'Team Sport'],
    descBn: 'হকি দক্ষিণ এশিয়ায় একটি জনপ্রিয় খেলা। ভারতীয় উপমহাদেশে মাঠ হকি দীর্ঘকাল ধরে খেলা হয়ে আসছে। বাংলাদেশে হকি ফেডারেশন সক্রিয়ভাবে কাজ করে।',
    descEn: 'Hockey has a long tradition in the Indian subcontinent. Field hockey has been played across Bengal for decades, with Bangladesh maintaining an active hockey federation and participating in international tournaments.',
    factsBn: [
      'হকি স্টিক দিয়ে বল মারা হয়।',
      'প্রতি দলে ১১ জন খেলোয়াড় থাকে।',
      'ভারত ৮ বার অলিম্পিক হকি স্বর্ণপদক জিতেছে।',
      'বাংলাদেশ হকি ফেডারেশন জাতীয় পর্যায়ে টুর্নামেন্ট আয়োজন করে।',
    ],
    factsEn: [
      'Hockey is played with a stick and ball.',
      'Each team has 11 players.',
      'India has won 8 Olympic gold medals in hockey.',
      'The Bangladesh Hockey Federation organizes national tournaments.',
    ],
    quiz: [
      {
        id: 'hockey-1',
        prompt: 'What does মাঠ mean?',
        promptBn: 'মাঠ শব্দের ইংরেজি অর্থ কী?',
        options: ['Field/ground', 'Stadium', 'Court', 'Pool'],
        correct: 0,
        explanation: 'মাঠ (math) = field or ground. মাঠ হকি = field hockey.',
      },
      {
        id: 'hockey-2',
        prompt: 'What does স্বর্ণপদক mean?',
        promptBn: 'স্বর্ণপদক শব্দের অর্থ কী?',
        options: ['Gold medal', 'Silver medal', 'Trophy', 'Prize money'],
        correct: 0,
        explanation: 'স্বর্ণপদক (shornopadok) = gold medal. স্বর্ণ (gold) + পদক (medal).',
      },
      {
        id: 'hockey-3',
        prompt: 'What does টুর্নামেন্ট mean?',
        promptBn: 'টুর্নামেন্ট শব্দের অর্থ কী?',
        options: ['Tournament', 'Practice', 'Season', 'League'],
        correct: 0,
        explanation: 'টুর্নামেন্ট (tournament) is a borrowed English word used in Bengali for competitive events.',
      },
    ],
  },

  // ─── 5. হা-ডু-ডু ──────────────────────────────────────
  {
    id: 'ha-du-du',
    bengaliName: 'হা-ডু-ডু',
    englishName: 'Ha-du-du',
    icon: '🏃',
    tags: ['ঐতিহ্যবাহী', 'Folk Game'],
    descBn: 'হা-ডু-ডু বাংলার প্রাচীন ঐতিহ্যবাহী খেলা এবং কাবাডির আদি রূপ। গ্রামবাংলায় এই খেলা শতাব্দীর পর শতাব্দী ধরে খেলা হচ্ছে। খেলোয়াড় "হা-ডু-ডু" বলতে বলতে প্রতিপক্ষকে ছুঁয়ে ফিরে আসে।',
    descEn: 'Ha-du-du is the traditional Bengali form of kabaddi, played in rural Bengal for centuries. The name comes from the chant "ha-du-du" that the raider repeats while entering the opponent\'s territory. It is considered the origin of modern kabaddi.',
    factsBn: [
      'হা-ডু-ডু কাবাডির আদি রূপ।',
      'গ্রামবাংলায় এই খেলা শত শত বছর ধরে চলে আসছে।',
      'কোনো বিশেষ মাঠ বা সরঞ্জামের প্রয়োজন হয় না।',
      'দুই দলে ভাগ হয়ে খেলা হয়।',
    ],
    factsEn: [
      'Ha-du-du is the original form of kabaddi.',
      'It has been played in rural Bengal for hundreds of years.',
      'No special field or equipment is needed.',
      'It is played between two teams.',
    ],
    quiz: [
      {
        id: 'ha-du-du-1',
        prompt: 'What does ঐতিহ্যবাহী mean?',
        promptBn: 'ঐতিহ্যবাহী শব্দের অর্থ কী?',
        options: ['Traditional', 'Modern', 'Popular', 'Foreign'],
        correct: 0,
        explanation: 'ঐতিহ্যবাহী (oitihyobahi) = traditional. ঐতিহ্য (heritage) + বাহী (carrying).',
      },
      {
        id: 'ha-du-du-2',
        prompt: 'What does গ্রাম mean?',
        promptBn: 'গ্রাম শব্দের ইংরেজি অর্থ কী?',
        options: ['Village', 'City', 'Town', 'Country'],
        correct: 0,
        explanation: 'গ্রাম (gram) = village. গ্রামবাংলা = rural Bengal.',
      },
      {
        id: 'ha-du-du-3',
        prompt: 'What is ha-du-du considered the origin of?',
        promptBn: 'হা-ডু-ডু কোন খেলার আদি রূপ?',
        options: ['Kabaddi', 'Football', 'Wrestling', 'Cricket'],
        correct: 0,
        explanation: 'হা-ডু-ডু is considered the traditional form of modern কাবাডি (kabaddi).',
      },
    ],
  },

  // ─── 6. সাকিব আল হাসান ───────────────────────────────
  {
    id: 'shakib-al-hasan',
    bengaliName: 'সাকিব আল হাসান',
    englishName: 'Shakib Al Hasan',
    icon: '⭐',
    tags: ['ক্রিকেটার', 'All-rounder'],
    descBn: 'সাকিব আল হাসান বাংলাদেশের সর্বকালের সেরা ক্রিকেটার এবং বিশ্বের অন্যতম সেরা অলরাউন্ডার। তিনি ICC-র ১ নম্বর অলরাউন্ডার হয়েছেন। ব্যাটিং ও বোলিং দুটোতেই সমান দক্ষ।',
    descEn: 'Shakib Al Hasan is the greatest Bangladeshi cricketer of all time and one of the world\'s best all-rounders. He has been ranked the No. 1 all-rounder by the ICC, excelling in both batting and bowling across all formats.',
    factsBn: [
      'সাকিব ICC ১ নম্বর অলরাউন্ডার হয়েছেন।',
      'তিনি বাংলাদেশের সর্বোচ্চ উইকেট শিকারী।',
      'ব্যাটিং ও বোলিং দুটোতেই সমান পারদর্শী।',
      'টেস্ট, ওডিআই ও টি-টোয়েন্টি — তিন ফরম্যাটেই সফল।',
    ],
    factsEn: [
      'Shakib became ICC No. 1 all-rounder.',
      'He is Bangladesh\'s highest wicket-taker.',
      'Equally skilled in both batting and bowling.',
      'Successful in all three formats: Test, ODI, and T20.',
    ],
    quiz: [
      {
        id: 'shakib-al-hasan-1',
        prompt: 'What does অলরাউন্ডার mean in cricket?',
        promptBn: 'ক্রিকেটে অলরাউন্ডার-এর অর্থ কী?',
        options: ['All-rounder (bats & bowls)', 'Batsman only', 'Bowler only', 'Wicketkeeper'],
        correct: 0,
        explanation: 'অলরাউন্ডার (all-rounder) = a player skilled in both batting and bowling.',
      },
      {
        id: 'shakib-al-hasan-2',
        prompt: 'What does সেরা mean?',
        promptBn: 'সেরা শব্দের ইংরেজি অর্থ কী?',
        options: ['Best/greatest', 'Worst', 'Average', 'First'],
        correct: 0,
        explanation: 'সেরা (shera) = best or greatest. "সর্বকালের সেরা" = greatest of all time.',
      },
      {
        id: 'shakib-al-hasan-3',
        prompt: 'What does উইকেট mean in cricket?',
        promptBn: 'ক্রিকেটে উইকেট শব্দের অর্থ কী?',
        options: ['Wicket (stumps/dismissal)', 'Ball', 'Run', 'Boundary'],
        correct: 0,
        explanation: 'উইকেট (wicket) = the stumps or a batsman\'s dismissal. "উইকেট শিকারী" = wicket-taker.',
      },
    ],
  },

  // ─── 7. নৌকাবাইচ ─────────────────────────────────────
  {
    id: 'nouka-baich',
    bengaliName: 'নৌকাবাইচ',
    englishName: 'Boat Racing',
    icon: '🚣',
    tags: ['উৎসব', 'Traditional'],
    descBn: 'নৌকাবাইচ বাংলাদেশের একটি ঐতিহ্যবাহী খেলা ও উৎসব। বর্ষাকালে নদীতে রঙিন নৌকা দিয়ে দৌড় প্রতিযোগিতা হয়। হাজার হাজার দর্শক নদীর দুই পাড়ে জড়ো হয়। এটি বাংলার জলজ সংস্কৃতির অবিচ্ছেদ্য অংশ।',
    descEn: 'Nouka Baich (boat racing) is a traditional Bengali sport and festival. During the monsoon season, colorful boats race along rivers while thousands gather on the banks to watch. It is an integral part of Bengal\'s riverine culture.',
    factsBn: [
      'বর্ষাকালে নদীতে নৌকাবাইচ অনুষ্ঠিত হয়।',
      'প্রতিটি নৌকায় অনেক বৈঠাওয়ালা থাকে।',
      'হাজার হাজার দর্শক নদীর তীরে জমায়েত হয়।',
      'নৌকাগুলো রঙিন নকশায় সাজানো থাকে।',
    ],
    factsEn: [
      'Boat races are held on rivers during the monsoon season.',
      'Each boat has many rowers.',
      'Thousands of spectators gather on the riverbanks.',
      'The boats are decorated with colorful designs.',
    ],
    quiz: [
      {
        id: 'nouka-baich-1',
        prompt: 'What does নৌকা mean?',
        promptBn: 'নৌকা শব্দের ইংরেজি অর্থ কী?',
        options: ['Boat', 'Ship', 'Raft', 'Canoe'],
        correct: 0,
        explanation: 'নৌকা (nouka) = boat. নৌকাবাইচ = boat race.',
      },
      {
        id: 'nouka-baich-2',
        prompt: 'What does বর্ষাকাল mean?',
        promptBn: 'বর্ষাকাল শব্দের অর্থ কী?',
        options: ['Monsoon/rainy season', 'Summer', 'Winter', 'Spring'],
        correct: 0,
        explanation: 'বর্ষাকাল (borshakaal) = monsoon or rainy season. বর্ষা (rain) + কাল (period).',
      },
      {
        id: 'nouka-baich-3',
        prompt: 'What does দর্শক mean?',
        promptBn: 'দর্শক শব্দের ইংরেজি অর্থ কী?',
        options: ['Spectator/viewer', 'Player', 'Judge', 'Organizer'],
        correct: 0,
        explanation: 'দর্শক (dorshok) = spectator or viewer. দর্শন (seeing) → দর্শক (one who sees).',
      },
    ],
  },

  // ─── 8. বাডমিন্টন ────────────────────────────────────
  {
    id: 'badminton',
    bengaliName: 'বাডমিন্টন',
    englishName: 'Badminton',
    icon: '🏸',
    tags: ['ক্রমবর্ধমান', 'Racquet Sport'],
    descBn: 'বাডমিন্টন বাংলাদেশে ক্রমবর্ধমান জনপ্রিয় একটি খেলা। শহর ও গ্রাম উভয় জায়গায় খেলা হয়। বাংলাদেশ বাডমিন্টন ফেডারেশন আন্তর্জাতিক প্রতিযোগিতায় অংশগ্রহণ করে।',
    descEn: 'Badminton is a growing sport in Bangladesh, played in both urban and rural areas. The Bangladesh Badminton Federation participates in international competitions, and the sport is gaining popularity among young people.',
    factsBn: [
      'বাডমিন্টন র‌্যাকেট ও শাটলকক দিয়ে খেলা হয়।',
      'একক ও দ্বৈত — দুই ধরনের ম্যাচ হয়।',
      'নেটের উপর দিয়ে শাটলকক আদান-প্রদান হয়।',
      'বাংলাদেশে এই খেলার জনপ্রিয়তা বাড়ছে।',
    ],
    factsEn: [
      'Badminton is played with a racquet and shuttlecock.',
      'There are singles and doubles matches.',
      'The shuttlecock is exchanged over a net.',
      'The sport is growing in popularity in Bangladesh.',
    ],
    quiz: [
      {
        id: 'badminton-1',
        prompt: 'What does একক mean in sports?',
        promptBn: 'খেলাধুলায় একক শব্দের অর্থ কী?',
        options: ['Singles', 'Doubles', 'Team', 'Mixed'],
        correct: 0,
        explanation: 'একক (ekok) = singles (one person per side). দ্বৈত (dwoito) = doubles.',
      },
      {
        id: 'badminton-2',
        prompt: 'What does জনপ্রিয় mean?',
        promptBn: 'জনপ্রিয় শব্দের ইংরেজি অর্থ কী?',
        options: ['Popular', 'Famous', 'Traditional', 'Expensive'],
        correct: 0,
        explanation: 'জনপ্রিয় (jonopriyo) = popular. জন (people) + প্রিয় (dear) = dear to people.',
      },
      {
        id: 'badminton-3',
        prompt: 'What does প্রতিযোগিতা mean?',
        promptBn: 'প্রতিযোগিতা শব্দের অর্থ কী?',
        options: ['Competition', 'Practice', 'Training', 'Exhibition'],
        correct: 0,
        explanation: 'প্রতিযোগিতা (protijogita) = competition or contest.',
      },
    ],
  },

  // ─── 9. দাবা ──────────────────────────────────────────
  {
    id: 'chess',
    bengaliName: 'দাবা',
    englishName: 'Chess',
    icon: '♟️',
    tags: ['মেধা', 'Board Game'],
    descBn: 'দাবা একটি প্রাচীন বুদ্ধিভিত্তিক খেলা। নিয়াজ মোর্শেদ ১৯৮৭ সালে দক্ষিণ এশিয়ার প্রথম গ্র্যান্ডমাস্টার হন। বাংলাদেশে দাবার জনপ্রিয়তা ক্রমশ বাড়ছে এবং অনেক তরুণ খেলোয়াড় আন্তর্জাতিক পর্যায়ে খেলছে।',
    descEn: 'Chess is an ancient strategy game. Niaz Murshed became the first South Asian Grandmaster in 1987, a landmark achievement for Bangladeshi chess. The game is growing in popularity with many young players competing internationally.',
    factsBn: [
      'নিয়াজ মোর্শেদ দক্ষিণ এশিয়ার প্রথম গ্র্যান্ডমাস্টার (১৯৮৭)।',
      'দাবায় ৬৪ ঘরের বোর্ড ব্যবহার হয়।',
      'রাজা, রানী, হাতি, ঘোড়া, নৌকা ও সৈন্য — ছয় ধরনের ঘুঁটি।',
      'দাবা বুদ্ধিভিত্তিক খেলা হিসেবে পরিচিত।',
    ],
    factsEn: [
      'Niaz Murshed became South Asia\'s first Grandmaster (1987).',
      'Chess uses a board with 64 squares.',
      'King, queen, bishop, knight, rook, and pawn — six types of pieces.',
      'Chess is known as a game of intellect.',
    ],
    quiz: [
      {
        id: 'chess-1',
        prompt: 'What does বুদ্ধি mean?',
        promptBn: 'বুদ্ধি শব্দের ইংরেজি অর্থ কী?',
        options: ['Intelligence/intellect', 'Strength', 'Speed', 'Luck'],
        correct: 0,
        explanation: 'বুদ্ধি (buddhi) = intelligence or intellect. "বুদ্ধিভিত্তিক খেলা" = intellectual game.',
      },
      {
        id: 'chess-2',
        prompt: 'Who was the first South Asian chess Grandmaster?',
        promptBn: 'দক্ষিণ এশিয়ার প্রথম দাবা গ্র্যান্ডমাস্টার কে?',
        options: ['Niaz Murshed', 'Viswanathan Anand', 'Shakib Al Hasan', 'Garry Kasparov'],
        correct: 0,
        explanation: 'নিয়াজ মোর্শেদ (Niaz Murshed) from Bangladesh became South Asia\'s first Grandmaster in 1987.',
      },
      {
        id: 'chess-3',
        prompt: 'What does রাজা mean in chess?',
        promptBn: 'দাবায় রাজা কোন ঘুঁটি?',
        options: ['King', 'Queen', 'Bishop', 'Knight'],
        correct: 0,
        explanation: 'রাজা (raja) = king. In chess, protecting the রাজা is the main objective.',
      },
    ],
  },

  // ─── 10. ষাঁড়ের দৌড় ─────────────────────────────────
  {
    id: 'bull-racing',
    bengaliName: 'ষাঁড়ের দৌড়',
    englishName: 'Bull Racing',
    icon: '🐂',
    tags: ['গ্রামীণ', 'Traditional'],
    descBn: 'ষাঁড়ের দৌড় বাংলার গ্রামীণ ঐতিহ্যের অংশ। ফসল কাটার পর মাঠে ষাঁড়ের দৌড় প্রতিযোগিতা অনুষ্ঠিত হয়। এটি গ্রামীণ উৎসবের একটি প্রিয় আকর্ষণ এবং বাংলার কৃষি সংস্কৃতির প্রতীক।',
    descEn: 'Bull racing is part of rural Bengali tradition. After the harvest, bull racing competitions are held in the fields. It is a beloved attraction at village festivals and a symbol of Bengal\'s agricultural culture.',
    factsBn: [
      'ফসল কাটার পর গ্রামে ষাঁড়ের দৌড় হয়।',
      'এটি গ্রামীণ উৎসবের একটি প্রিয় আকর্ষণ।',
      'ষাঁড়গুলোকে বিশেষভাবে প্রশিক্ষণ দেওয়া হয়।',
      'এই খেলা বাংলার কৃষি সংস্কৃতির প্রতীক।',
    ],
    factsEn: [
      'Bull races are held in villages after the harvest.',
      'It is a beloved attraction at rural festivals.',
      'The bulls are specially trained for racing.',
      'This sport symbolizes Bengal\'s agricultural culture.',
    ],
    quiz: [
      {
        id: 'bull-racing-1',
        prompt: 'What does ষাঁড় mean?',
        promptBn: 'ষাঁড় শব্দের ইংরেজি অর্থ কী?',
        options: ['Bull', 'Cow', 'Horse', 'Goat'],
        correct: 0,
        explanation: 'ষাঁড় (shar) = bull. ষাঁড়ের দৌড় = bull racing.',
      },
      {
        id: 'bull-racing-2',
        prompt: 'What does ফসল mean?',
        promptBn: 'ফসল শব্দের অর্থ কী?',
        options: ['Harvest/crop', 'Field', 'Seed', 'Fertilizer'],
        correct: 0,
        explanation: 'ফসল (foshol) = harvest or crop. "ফসল কাটার পর" = after the harvest.',
      },
      {
        id: 'bull-racing-3',
        prompt: 'What does কৃষি mean?',
        promptBn: 'কৃষি শব্দের ইংরেজি অর্থ কী?',
        options: ['Agriculture', 'Industry', 'Commerce', 'Education'],
        correct: 0,
        explanation: 'কৃষি (krishi) = agriculture. "কৃষি সংস্কৃতি" = agricultural culture.',
      },
    ],
  },
];

export { SPORTS };
