/* ── travel.js — Bengali travel destinations data + quiz questions ──────────── */

const TRAVEL = [
  // ─── 1. সুন্দরবন ──────────────────────────────────────
  {
    id: 'sundarbans',
    bengaliName: 'সুন্দরবন',
    englishName: 'Sundarbans',
    icon: '🌿',
    tags: ['প্রকৃতি', 'Nature'],
    descBn: 'সুন্দরবন পৃথিবীর বৃহত্তম ম্যানগ্রোভ বন এবং ইউনেস্কো বিশ্ব ঐতিহ্যবাহী স্থান। এটি বাংলাদেশ ও ভারতের পশ্চিমবঙ্গের মধ্যে অবস্থিত। রয়্যাল বেঙ্গল টাইগারের আবাসস্থল হিসেবে সুন্দরবন বিশ্বব্যাপী পরিচিত।',
    descEn: 'The Sundarbans is the largest mangrove forest in the world and a UNESCO World Heritage Site. It spans the border between Bangladesh and West Bengal, India. The Sundarbans is globally renowned as the home of the Royal Bengal Tiger.',
    highlightsBn: [
      'পৃথিবীর বৃহত্তম ম্যানগ্রোভ বন।',
      'রয়্যাল বেঙ্গল টাইগারের প্রধান আবাসস্থল।',
      'ইউনেস্কো বিশ্ব ঐতিহ্যবাহী স্থান হিসেবে স্বীকৃত।',
      'বিচিত্র জীববৈচিত্র্যে সমৃদ্ধ — হরিণ, কুমির, ডলফিন ও নানা পাখি।',
    ],
    highlightsEn: [
      'The largest mangrove forest in the world.',
      'Primary habitat of the Royal Bengal Tiger.',
      'Recognized as a UNESCO World Heritage Site.',
      'Rich biodiversity — deer, crocodiles, dolphins, and diverse bird species.',
    ],
    quiz: [
      {
        id: 'sundarbans-1',
        prompt: 'What does বন mean in Bengali?',
        promptBn: 'বন শব্দের ইংরেজি অর্থ কী?',
        options: ['Forest', 'River', 'Mountain', 'Desert'],
        correct: 0,
        explanation: 'বন (bon) = forest. সুন্দরবন = beautiful forest (সুন্দর + বন).',
      },
      {
        id: 'sundarbans-2',
        prompt: 'What does আবাসস্থল mean?',
        promptBn: 'আবাসস্থল শব্দের অর্থ কী?',
        options: ['Habitat/dwelling place', 'Hunting ground', 'Playground', 'Marketplace'],
        correct: 0,
        explanation: 'আবাসস্থল (abassthal) = habitat or dwelling place. আবাস (dwelling) + স্থল (place).',
      },
      {
        id: 'sundarbans-3',
        prompt: 'What does জীববৈচিত্র্য mean?',
        promptBn: 'জীববৈচিত্র্য শব্দের ইংরেজি অর্থ কী?',
        options: ['Biodiversity', 'Ecosystem', 'Wildlife', 'Environment'],
        correct: 0,
        explanation: 'জীববৈচিত্র্য (jiboboichitro) = biodiversity. জীব (life) + বৈচিত্র্য (diversity).',
      },
    ],
  },

  // ─── 2. কক্সবাজার ─────────────────────────────────────
  {
    id: 'coxs-bazar',
    bengaliName: 'কক্সবাজার',
    englishName: "Cox's Bazar",
    icon: '🏖️',
    tags: ['সমুদ্র সৈকত', 'Beach'],
    descBn: 'কক্সবাজার পৃথিবীর দীর্ঘতম প্রাকৃতিক সমুদ্র সৈকত, যার দৈর্ঘ্য প্রায় ১২০ কিলোমিটার। এটি বাংলাদেশের সবচেয়ে জনপ্রিয় পর্যটন কেন্দ্র। এখানে হিমছড়ি, ইনানী বিচ এবং মহেশখালী দ্বীপ বিখ্যাত দর্শনীয় স্থান।',
    descEn: "Cox's Bazar boasts the longest natural sea beach in the world, stretching approximately 120 kilometers. It is the most popular tourist destination in Bangladesh. Nearby attractions include Himchari, Inani Beach, and Moheshkhali Island.",
    highlightsBn: [
      'পৃথিবীর দীর্ঘতম প্রাকৃতিক সমুদ্র সৈকত (১২০ কিমি)।',
      'বাংলাদেশের সবচেয়ে জনপ্রিয় পর্যটন কেন্দ্র।',
      'হিমছড়ি জলপ্রপাত ও ইনানী বিচ কাছাকাছি অবস্থিত।',
      'সূর্যাস্তের অপরূপ দৃশ্য উপভোগ করা যায়।',
    ],
    highlightsEn: [
      'The longest natural sea beach in the world (120 km).',
      'The most popular tourist destination in Bangladesh.',
      'Himchari waterfall and Inani Beach are nearby attractions.',
      'Offers breathtaking sunset views.',
    ],
    quiz: [
      {
        id: 'coxs-bazar-1',
        prompt: 'What does সমুদ্র সৈকত mean?',
        promptBn: 'সমুদ্র সৈকত শব্দের ইংরেজি অর্থ কী?',
        options: ['Sea beach', 'River bank', 'Lake shore', 'Mountain peak'],
        correct: 0,
        explanation: 'সমুদ্র সৈকত (somudro shoikot) = sea beach. সমুদ্র (sea) + সৈকত (shore).',
      },
      {
        id: 'coxs-bazar-2',
        prompt: 'What does পর্যটন mean?',
        promptBn: 'পর্যটন শব্দের অর্থ কী?',
        options: ['Tourism', 'Agriculture', 'Commerce', 'Education'],
        correct: 0,
        explanation: 'পর্যটন (porjoton) = tourism. পর্যটন কেন্দ্র = tourist center.',
      },
      {
        id: 'coxs-bazar-3',
        prompt: 'What does সূর্যাস্ত mean?',
        promptBn: 'সূর্যাস্ত শব্দের ইংরেজি অর্থ কী?',
        options: ['Sunset', 'Sunrise', 'Moonrise', 'Eclipse'],
        correct: 0,
        explanation: 'সূর্যাস্ত (surjasto) = sunset. সূর্য (sun) + অস্ত (setting).',
      },
    ],
  },

  // ─── 3. শান্তিনিকেতন ─────────────────────────────────
  {
    id: 'shantiniketan',
    bengaliName: 'শান্তিনিকেতন',
    englishName: 'Shantiniketan',
    icon: '🏫',
    tags: ['সংস্কৃতি', 'Culture'],
    descBn: 'শান্তিনিকেতন পশ্চিমবঙ্গের বীরভূম জেলায় অবস্থিত রবীন্দ্রনাথ ঠাকুরের প্রতিষ্ঠিত বিশ্বভারতী বিশ্ববিদ্যালয়ের কেন্দ্র। এটি বাংলা সাহিত্য, শিল্পকলা ও সংস্কৃতির তীর্থস্থান। রবীন্দ্রনাথের আদর্শে খোলা আকাশের নিচে শিক্ষাদানের রীতি এখানে আজও বিদ্যমান।',
    descEn: 'Shantiniketan, located in the Birbhum district of West Bengal, is home to Visva-Bharati University founded by Rabindranath Tagore. It is a pilgrimage site for Bengali literature, art, and culture. The tradition of open-air education, inspired by Tagore\'s ideals, continues to this day.',
    highlightsBn: [
      'রবীন্দ্রনাথ ঠাকুর কর্তৃক প্রতিষ্ঠিত বিশ্বভারতী বিশ্ববিদ্যালয়।',
      'খোলা আকাশের নিচে পাঠদানের ঐতিহ্য।',
      'পৌষমেলা ও বসন্ত উৎসব বিশ্বখ্যাত।',
      'বাংলা শিল্পকলা ও সাহিত্যের প্রাণকেন্দ্র।',
    ],
    highlightsEn: [
      'Home to Visva-Bharati University founded by Rabindranath Tagore.',
      'Tradition of open-air education under the sky.',
      'The Poush Mela and Basanta Utsav festivals are world-famous.',
      'A vibrant center of Bengali art and literature.',
    ],
    quiz: [
      {
        id: 'shantiniketan-1',
        prompt: 'What does শান্তি mean in Bengali?',
        promptBn: 'শান্তি শব্দের ইংরেজি অর্থ কী?',
        options: ['Peace', 'War', 'Happiness', 'Knowledge'],
        correct: 0,
        explanation: 'শান্তি (shanti) = peace. শান্তিনিকেতন = abode of peace (শান্তি + নিকেতন).',
      },
      {
        id: 'shantiniketan-2',
        prompt: 'What does শিল্পকলা mean?',
        promptBn: 'শিল্পকলা শব্দের অর্থ কী?',
        options: ['Art', 'Science', 'Music', 'Dance'],
        correct: 0,
        explanation: 'শিল্পকলা (shilpokola) = art. শিল্প (craft) + কলা (art form).',
      },
      {
        id: 'shantiniketan-3',
        prompt: 'What does বিশ্ববিদ্যালয় mean?',
        promptBn: 'বিশ্ববিদ্যালয় শব্দের ইংরেজি অর্থ কী?',
        options: ['University', 'School', 'College', 'Library'],
        correct: 0,
        explanation: 'বিশ্ববিদ্যালয় (bishwobiddaloy) = university. বিশ্ব (world) + বিদ্যালয় (place of learning).',
      },
    ],
  },

  // ─── 4. সিলেট ─────────────────────────────────────────
  {
    id: 'sylhet',
    bengaliName: 'সিলেট',
    englishName: 'Sylhet',
    icon: '🍃',
    tags: ['চা বাগান', 'Tea Gardens'],
    descBn: 'সিলেট বাংলাদেশের উত্তর-পূর্বাঞ্চলে অবস্থিত একটি প্রাকৃতিক সৌন্দর্যের শহর। এটি চা বাগান, হাওর ও সবুজ পাহাড়ের জন্য বিখ্যাত। জাফলং, রাতারগুল জলাবন ও শ্রীমঙ্গলের চা বাগান সিলেটের প্রধান আকর্ষণ।',
    descEn: 'Sylhet is a city of natural beauty located in northeastern Bangladesh. It is famous for its tea gardens, haors (wetlands), and lush green hills. Jaflong, Ratargul Swamp Forest, and the tea gardens of Sreemangal are its main attractions.',
    highlightsBn: [
      'বাংলাদেশের চা রাজধানী — বিস্তীর্ণ চা বাগানের জন্য বিখ্যাত।',
      'জাফলং-এর স্বচ্ছ নদী ও পাথরের সৌন্দর্য।',
      'রাতারগুল — বাংলাদেশের একমাত্র জলাবন (সোয়াম্প ফরেস্ট)।',
      'হাওর অঞ্চলের অপরূপ প্রাকৃতিক দৃশ্য।',
    ],
    highlightsEn: [
      'The tea capital of Bangladesh — famous for its vast tea gardens.',
      'Jaflong offers crystal-clear rivers and stunning stone landscapes.',
      'Ratargul — the only swamp forest in Bangladesh.',
      'Breathtaking natural scenery of the haor wetlands.',
    ],
    quiz: [
      {
        id: 'sylhet-1',
        prompt: 'What does চা বাগান mean?',
        promptBn: 'চা বাগান শব্দের ইংরেজি অর্থ কী?',
        options: ['Tea garden', 'Flower garden', 'Rice field', 'Fruit orchard'],
        correct: 0,
        explanation: 'চা বাগান (cha bagan) = tea garden. চা (tea) + বাগান (garden).',
      },
      {
        id: 'sylhet-2',
        prompt: 'What does সৌন্দর্য mean?',
        promptBn: 'সৌন্দর্য শব্দের অর্থ কী?',
        options: ['Beauty', 'Danger', 'Mystery', 'Silence'],
        correct: 0,
        explanation: 'সৌন্দর্য (shoundorjo) = beauty. প্রাকৃতিক সৌন্দর্য = natural beauty.',
      },
      {
        id: 'sylhet-3',
        prompt: 'What does জলাবন mean?',
        promptBn: 'জলাবন শব্দের ইংরেজি অর্থ কী?',
        options: ['Swamp forest', 'Rainforest', 'Mangrove forest', 'Pine forest'],
        correct: 0,
        explanation: 'জলাবন (jolbon) = swamp forest. জলা (swamp/wetland) + বন (forest).',
      },
    ],
  },

  // ─── 5. রাঙামাটি ──────────────────────────────────────
  {
    id: 'rangamati',
    bengaliName: 'রাঙামাটি',
    englishName: 'Rangamati',
    icon: '⛰️',
    tags: ['পাহাড়', 'Hills'],
    descBn: 'রাঙামাটি বাংলাদেশের পার্বত্য চট্টগ্রামে অবস্থিত একটি মনোরম পাহাড়ি জেলা। কাপ্তাই হ্রদ, ঝুলন্ত সেতু ও আদিবাসী সংস্কৃতি এখানকার প্রধান আকর্ষণ। চাকমা, মারমা ও ত্রিপুরাসহ বিভিন্ন আদিবাসী জনগোষ্ঠী এখানে বসবাস করে।',
    descEn: 'Rangamati is a picturesque hill district in the Chittagong Hill Tracts of Bangladesh. Kaptai Lake, the hanging bridge, and indigenous culture are its main attractions. Various indigenous communities including Chakma, Marma, and Tripura reside here.',
    highlightsBn: [
      'কাপ্তাই হ্রদ — বাংলাদেশের বৃহত্তম কৃত্রিম হ্রদ।',
      'ঝুলন্ত সেতু — রাঙামাটির বিখ্যাত পর্যটন আকর্ষণ।',
      'বৈচিত্র্যময় আদিবাসী সংস্কৃতি ও ঐতিহ্য।',
      'সবুজ পাহাড় ও নদীর অপরূপ প্রাকৃতিক সৌন্দর্য।',
    ],
    highlightsEn: [
      'Kaptai Lake — the largest artificial lake in Bangladesh.',
      'The hanging bridge — a famous tourist attraction of Rangamati.',
      'Diverse indigenous culture and traditions.',
      'Stunning natural beauty of green hills and rivers.',
    ],
    quiz: [
      {
        id: 'rangamati-1',
        prompt: 'What does পাহাড় mean?',
        promptBn: 'পাহাড় শব্দের ইংরেজি অর্থ কী?',
        options: ['Hill/mountain', 'Valley', 'River', 'Plain'],
        correct: 0,
        explanation: 'পাহাড় (pahar) = hill or mountain. পার্বত্য (hilly) comes from the same root পর্বত.',
      },
      {
        id: 'rangamati-2',
        prompt: 'What does হ্রদ mean?',
        promptBn: 'হ্রদ শব্দের অর্থ কী?',
        options: ['Lake', 'River', 'Ocean', 'Pond'],
        correct: 0,
        explanation: 'হ্রদ (hrod) = lake. কাপ্তাই হ্রদ = Kaptai Lake.',
      },
      {
        id: 'rangamati-3',
        prompt: 'What does আদিবাসী mean?',
        promptBn: 'আদিবাসী শব্দের ইংরেজি অর্থ কী?',
        options: ['Indigenous/tribal', 'Foreign', 'Urban', 'Nomadic'],
        correct: 0,
        explanation: 'আদিবাসী (adibashi) = indigenous or tribal. আদি (original) + বাসী (resident).',
      },
    ],
  },

  // ─── 6. পাহাড়পুর ──────────────────────────────────────
  {
    id: 'paharpur',
    bengaliName: 'পাহাড়পুর',
    englishName: 'Paharpur',
    icon: '🏛️',
    tags: ['প্রত্নতত্ত্ব', 'Archaeology'],
    descBn: 'পাহাড়পুর বাংলাদেশের নওগাঁ জেলায় অবস্থিত একটি প্রাচীন বৌদ্ধ বিহার। সোমপুর মহাবিহার নামে পরিচিত এই স্থানটি অষ্টম শতাব্দীতে পাল রাজবংশের আমলে নির্মিত। এটি দক্ষিণ এশিয়ার বৃহত্তম বৌদ্ধ বিহার এবং ইউনেস্কো বিশ্ব ঐতিহ্যবাহী স্থান।',
    descEn: 'Paharpur, located in the Naogaon district of Bangladesh, is an ancient Buddhist monastery. Known as Somapura Mahavihara, it was built during the Pala dynasty in the 8th century. It is the largest Buddhist monastery in South Asia and a UNESCO World Heritage Site.',
    highlightsBn: [
      'সোমপুর মহাবিহার — দক্ষিণ এশিয়ার বৃহত্তম বৌদ্ধ বিহার।',
      'অষ্টম শতাব্দীতে পাল রাজবংশের আমলে নির্মিত।',
      'ইউনেস্কো বিশ্ব ঐতিহ্যবাহী স্থান হিসেবে স্বীকৃত।',
      'প্রাচীন পোড়ামাটির ফলক ও ভাস্কর্য সংরক্ষিত আছে।',
    ],
    highlightsEn: [
      'Somapura Mahavihara — the largest Buddhist monastery in South Asia.',
      'Built during the Pala dynasty in the 8th century.',
      'Recognized as a UNESCO World Heritage Site.',
      'Ancient terracotta plaques and sculptures are preserved here.',
    ],
    quiz: [
      {
        id: 'paharpur-1',
        prompt: 'What does বিহার mean in this context?',
        promptBn: 'এই প্রসঙ্গে বিহার শব্দের অর্থ কী?',
        options: ['Monastery', 'Temple', 'Palace', 'Fortress'],
        correct: 0,
        explanation: 'বিহার (bihar) = monastery. সোমপুর মহাবিহার = Somapura great monastery.',
      },
      {
        id: 'paharpur-2',
        prompt: 'What does প্রাচীন mean?',
        promptBn: 'প্রাচীন শব্দের ইংরেজি অর্থ কী?',
        options: ['Ancient', 'Modern', 'Medieval', 'Recent'],
        correct: 0,
        explanation: 'প্রাচীন (prachin) = ancient. প্রাচীন বৌদ্ধ বিহার = ancient Buddhist monastery.',
      },
      {
        id: 'paharpur-3',
        prompt: 'What does ভাস্কর্য mean?',
        promptBn: 'ভাস্কর্য শব্দের অর্থ কী?',
        options: ['Sculpture', 'Painting', 'Carving', 'Mosaic'],
        correct: 0,
        explanation: 'ভাস্কর্য (bhashkorjo) = sculpture. পাহাড়পুরে প্রাচীন ভাস্কর্য সংরক্ষিত আছে।',
      },
    ],
  },

  // ─── 7. ষাট গম্বুজ মসজিদ ─────────────────────────────
  {
    id: 'sixty-dome-mosque',
    bengaliName: 'ষাট গম্বুজ মসজিদ',
    englishName: 'Sixty Dome Mosque',
    icon: '🕌',
    tags: ['স্থাপত্য', 'Architecture'],
    descBn: 'ষাট গম্বুজ মসজিদ বাংলাদেশের বাগেরহাটে অবস্থিত একটি মধ্যযুগীয় মসজিদ। পঞ্চদশ শতাব্দীতে খান জাহান আলী এটি নির্মাণ করেন। এটি বাংলাদেশের সবচেয়ে চিত্তাকর্ষক প্রাচীন স্থাপত্যগুলোর একটি এবং ইউনেস্কো বিশ্ব ঐতিহ্যবাহী স্থান।',
    descEn: 'The Sixty Dome Mosque is a medieval mosque located in Bagerhat, Bangladesh. It was built by Khan Jahan Ali in the 15th century. It is one of the most impressive ancient architectural monuments in Bangladesh and a UNESCO World Heritage Site.',
    highlightsBn: [
      'পঞ্চদশ শতাব্দীতে খান জাহান আলী কর্তৃক নির্মিত।',
      'আসলে ৭৭টি গম্বুজ রয়েছে — নাম "ষাট গম্বুজ" হলেও।',
      'ইউনেস্কো বিশ্ব ঐতিহ্যবাহী স্থান।',
      'মধ্যযুগীয় বাংলার স্থাপত্যশৈলীর অনন্য নিদর্শন।',
    ],
    highlightsEn: [
      'Built by Khan Jahan Ali in the 15th century.',
      'Actually has 77 domes — despite the name "Sixty Dome."',
      'A UNESCO World Heritage Site.',
      'A unique example of medieval Bengali architectural style.',
    ],
    quiz: [
      {
        id: 'sixty-dome-mosque-1',
        prompt: 'What does গম্বুজ mean?',
        promptBn: 'গম্বুজ শব্দের ইংরেজি অর্থ কী?',
        options: ['Dome', 'Pillar', 'Arch', 'Tower'],
        correct: 0,
        explanation: 'গম্বুজ (gombuj) = dome. ষাট গম্বুজ = sixty domes.',
      },
      {
        id: 'sixty-dome-mosque-2',
        prompt: 'What does মসজিদ mean?',
        promptBn: 'মসজিদ শব্দের অর্থ কী?',
        options: ['Mosque', 'Temple', 'Church', 'Monastery'],
        correct: 0,
        explanation: 'মসজিদ (mosjid) = mosque. ষাট গম্বুজ মসজিদ = Sixty Dome Mosque.',
      },
      {
        id: 'sixty-dome-mosque-3',
        prompt: 'What does স্থাপত্য mean?',
        promptBn: 'স্থাপত্য শব্দের ইংরেজি অর্থ কী?',
        options: ['Architecture', 'Sculpture', 'Engineering', 'Painting'],
        correct: 0,
        explanation: 'স্থাপত্য (sthapatyo) = architecture. স্থাপত্যশৈলী = architectural style.',
      },
    ],
  },

  // ─── 8. দার্জিলিং ─────────────────────────────────────
  {
    id: 'darjeeling',
    bengaliName: 'দার্জিলিং',
    englishName: 'Darjeeling',
    icon: '🚂',
    tags: ['পাহাড়ি শহর', 'Hill Station'],
    descBn: 'দার্জিলিং পশ্চিমবঙ্গের উত্তরাঞ্চলে হিমালয়ের পাদদেশে অবস্থিত একটি বিখ্যাত পাহাড়ি শহর। এটি চা বাগান, টয় ট্রেন ও কাঞ্চনজঙ্ঘা পর্বতের দৃশ্যের জন্য বিশ্ববিখ্যাত। দার্জিলিং হিমালয়ান রেলওয়ে ইউনেস্কো বিশ্ব ঐতিহ্যবাহী স্থান।',
    descEn: 'Darjeeling is a famous hill station located at the foothills of the Himalayas in northern West Bengal. It is world-renowned for its tea gardens, the toy train, and views of Mount Kanchenjunga. The Darjeeling Himalayan Railway is a UNESCO World Heritage Site.',
    highlightsBn: [
      'বিশ্বখ্যাত দার্জিলিং চায়ের উৎপত্তিস্থল।',
      'টয় ট্রেন (দার্জিলিং হিমালয়ান রেলওয়ে) — ইউনেস্কো ঐতিহ্যবাহী স্থান।',
      'কাঞ্চনজঙ্ঘা পর্বতের অপূর্ব দৃশ্য।',
      'টাইগার হিলে সূর্যোদয় দেখা একটি অবিস্মরণীয় অভিজ্ঞতা।',
    ],
    highlightsEn: [
      'Birthplace of world-famous Darjeeling tea.',
      'The toy train (Darjeeling Himalayan Railway) — a UNESCO Heritage Site.',
      'Magnificent views of Mount Kanchenjunga.',
      'Watching sunrise from Tiger Hill is an unforgettable experience.',
    ],
    quiz: [
      {
        id: 'darjeeling-1',
        prompt: 'What does পর্বত mean?',
        promptBn: 'পর্বত শব্দের ইংরেজি অর্থ কী?',
        options: ['Mountain', 'Hill', 'Valley', 'Plateau'],
        correct: 0,
        explanation: 'পর্বত (porbot) = mountain. কাঞ্চনজঙ্ঘা পর্বত = Mount Kanchenjunga.',
      },
      {
        id: 'darjeeling-2',
        prompt: 'What does সূর্যোদয় mean?',
        promptBn: 'সূর্যোদয় শব্দের অর্থ কী?',
        options: ['Sunrise', 'Sunset', 'Moonrise', 'Dawn'],
        correct: 0,
        explanation: 'সূর্যোদয় (surjodoy) = sunrise. সূর্য (sun) + উদয় (rising).',
      },
      {
        id: 'darjeeling-3',
        prompt: 'What does অভিজ্ঞতা mean?',
        promptBn: 'অভিজ্ঞতা শব্দের ইংরেজি অর্থ কী?',
        options: ['Experience', 'Adventure', 'Journey', 'Memory'],
        correct: 0,
        explanation: 'অভিজ্ঞতা (obhiggota) = experience. অবিস্মরণীয় অভিজ্ঞতা = unforgettable experience.',
      },
    ],
  },

  // ─── 9. মহাস্থানগড় ───────────────────────────────────
  {
    id: 'mahasthangarh',
    bengaliName: 'মহাস্থানগড়',
    englishName: 'Mahasthangarh',
    icon: '🏰',
    tags: ['প্রত্নতাত্ত্বিক', 'Archaeological'],
    descBn: 'মহাস্থানগড় বাংলাদেশের বগুড়া জেলায় অবস্থিত দেশের প্রাচীনতম প্রত্নতাত্ত্বিক স্থান। প্রাচীন পুণ্ড্রবর্ধন নগরীর ধ্বংসাবশেষ এখানে পাওয়া গেছে, যার ইতিহাস তৃতীয় খ্রিস্টপূর্বাব্দ পর্যন্ত বিস্তৃত। এটি বাংলার সুদীর্ঘ সভ্যতার সাক্ষী।',
    descEn: 'Mahasthangarh, located in the Bogra district of Bangladesh, is the oldest archaeological site in the country. The ruins of the ancient city of Pundravardhana have been discovered here, dating back to the 3rd century BCE. It stands as a witness to Bengal\'s long civilization.',
    highlightsBn: [
      'বাংলাদেশের প্রাচীনতম প্রত্নতাত্ত্বিক স্থান।',
      'প্রাচীন পুণ্ড্রবর্ধন নগরীর ধ্বংসাবশেষ।',
      'তৃতীয় খ্রিস্টপূর্বাব্দের ইতিহাস বহন করে।',
      'গোবিন্দ ভিটা, বৈরাগীর ভিটা ও জিয়ৎ কুণ্ড দর্শনীয় স্থান।',
    ],
    highlightsEn: [
      'The oldest archaeological site in Bangladesh.',
      'Ruins of the ancient city of Pundravardhana.',
      'Carries a history dating back to the 3rd century BCE.',
      'Govinda Bhita, Bairagi Bhita, and Jiyat Kund are notable sites.',
    ],
    quiz: [
      {
        id: 'mahasthangarh-1',
        prompt: 'What does গড় mean?',
        promptBn: 'গড় শব্দের ইংরেজি অর্থ কী?',
        options: ['Fort/citadel', 'Village', 'River', 'Temple'],
        correct: 0,
        explanation: 'গড় (gorh) = fort or citadel. মহাস্থানগড় = great place fort (মহা + স্থান + গড়).',
      },
      {
        id: 'mahasthangarh-2',
        prompt: 'What does ধ্বংসাবশেষ mean?',
        promptBn: 'ধ্বংসাবশেষ শব্দের অর্থ কী?',
        options: ['Ruins/remains', 'Building', 'Monument', 'Treasure'],
        correct: 0,
        explanation: 'ধ্বংসাবশেষ (dhongshaboshesh) = ruins or remains. ধ্বংস (destruction) + অবশেষ (remnants).',
      },
      {
        id: 'mahasthangarh-3',
        prompt: 'What does সভ্যতা mean?',
        promptBn: 'সভ্যতা শব্দের ইংরেজি অর্থ কী?',
        options: ['Civilization', 'Society', 'Culture', 'History'],
        correct: 0,
        explanation: 'সভ্যতা (shobbhota) = civilization. বাংলার সুদীর্ঘ সভ্যতা = Bengal\'s long civilization.',
      },
    ],
  },

  // ─── 10. কুয়াকাটা ─────────────────────────────────────
  {
    id: 'kuakata',
    bengaliName: 'কুয়াকাটা',
    englishName: 'Kuakata',
    icon: '🌅',
    tags: ['সমুদ্র সৈকত', 'Beach'],
    descBn: 'কুয়াকাটা বাংলাদেশের পটুয়াখালী জেলায় অবস্থিত একটি অনন্য সমুদ্র সৈকত। এটি "সাগরকন্যা" নামে পরিচিত কারণ এখান থেকে একই স্থানে সূর্যোদয় ও সূর্যাস্ত দুটোই দেখা যায়। রাখাইন আদিবাসী সম্প্রদায়ের সংস্কৃতি এখানকার আরেকটি বিশেষ আকর্ষণ।',
    descEn: 'Kuakata is a unique sea beach located in the Patuakhali district of Bangladesh. Known as the "Daughter of the Sea," it is one of the rare places where both sunrise and sunset can be viewed from the same beach. The culture of the Rakhine indigenous community is another special attraction here.',
    highlightsBn: [
      '"সাগরকন্যা" — একই সৈকত থেকে সূর্যোদয় ও সূর্যাস্ত দেখা যায়।',
      'রাখাইন আদিবাসী সম্প্রদায়ের সমৃদ্ধ সংস্কৃতি।',
      'ঝাউবন ও লাল কাঁকড়ার সৈকত দর্শনীয়।',
      'শান্ত ও নির্জন পরিবেশে সমুদ্র উপভোগ করা যায়।',
    ],
    highlightsEn: [
      '"Daughter of the Sea" — both sunrise and sunset visible from the same beach.',
      'Rich culture of the Rakhine indigenous community.',
      'Casuarina forests and red crab beaches are scenic attractions.',
      'Enjoy the sea in a peaceful and serene environment.',
    ],
    quiz: [
      {
        id: 'kuakata-1',
        prompt: 'What does সাগর mean?',
        promptBn: 'সাগর শব্দের ইংরেজি অর্থ কী?',
        options: ['Sea/ocean', 'River', 'Lake', 'Pond'],
        correct: 0,
        explanation: 'সাগর (shagor) = sea or ocean. সাগরকন্যা = daughter of the sea.',
      },
      {
        id: 'kuakata-2',
        prompt: 'What does দিগন্ত mean?',
        promptBn: 'দিগন্ত শব্দের অর্থ কী?',
        options: ['Horizon', 'Shore', 'Tide', 'Wave'],
        correct: 0,
        explanation: 'দিগন্ত (digonto) = horizon. Kuakata is famous for its unobstructed দিগন্ত view.',
      },
      {
        id: 'kuakata-3',
        prompt: 'What does সম্প্রদায় mean?',
        promptBn: 'সম্প্রদায় শব্দের ইংরেজি অর্থ কী?',
        options: ['Community', 'Family', 'Nation', 'Tribe'],
        correct: 0,
        explanation: 'সম্প্রদায় (shomprodai) = community. রাখাইন সম্প্রদায় = Rakhine community.',
      },
    ],
  },
];

export { TRAVEL };
