// bengali/trivia.js — Trivia categories and questions

export const TRIVIA_CATEGORIES = [
  { id: 'symbols',   title: 'National Symbols', icon: '🇧🇩', desc: 'Flag, animals, flowers, and emblems' },
  { id: 'history',   title: 'History',           icon: '🏛️',  desc: 'Independence, language movement, key dates' },
  { id: 'language',  title: 'Language & Lit.',   icon: '📖',  desc: 'Tagore, Nazrul, Bengali language facts' },
  { id: 'festivals', title: 'Festivals',          icon: '🎉',  desc: 'Pohela Boishakh, Eid, Durga Puja, and more' },
  { id: 'food',      title: 'Food & Cuisine',    icon: '🍛',  desc: 'Roshogolla, hilsa, fuchka, and more' },
  { id: 'geography', title: 'Geography',          icon: '🗺️',  desc: 'Rivers, capital, borders, the Sundarbans' },
  { id: 'people',    title: 'People & Culture',  icon: '⭐',  desc: 'Famous Bengalis, traditions, dress' },
  { id: 'mixed',     title: 'Mixed Quiz',        icon: '🎲',  desc: 'Random questions from all categories' },
];

export const TRIVIA_QUESTIONS = [
  // ── SYMBOLS ─────────────────────────────────────────────
  {
    id: 'q-nat-animal',
    category: 'symbols',
    type: 'mc',
    prompt: 'What is the national animal of Bangladesh?',
    options: ['Asian Elephant', 'Royal Bengal Tiger', 'Lion', 'One-horned Rhino'],
    correct: 1,
    explanation: 'The Royal Bengal Tiger (বাঘ) lives in the Sundarbans mangrove forest shared by Bangladesh and India.',
  },
  {
    id: 'q-nat-fish',
    category: 'symbols',
    type: 'mc',
    prompt: 'Which fish is the national fish of Bangladesh?',
    options: ['Rohu (Rui)', 'Salmon', 'Ilish (Hilsa)', 'Trout'],
    correct: 2,
    explanation: 'The Ilish or Hilsa (ইলিশ) is Bangladesh\'s national fish and a beloved culinary icon.',
  },
  {
    id: 'q-nat-fruit',
    category: 'symbols',
    type: 'mc',
    prompt: 'What is the national fruit of Bangladesh?',
    options: ['Mango', 'Pineapple', 'Jackfruit', 'Banana'],
    correct: 2,
    explanation: 'Jackfruit (কাঁঠাল) is the national fruit of Bangladesh.',
  },
  {
    id: 'q-nat-flower',
    category: 'symbols',
    type: 'mc',
    prompt: 'The national flower of Bangladesh is:',
    options: ['Lotus', 'Rose', 'White water lily (Shapla)', 'Jasmine'],
    correct: 2,
    explanation: 'The Shapla (শাপলা), or white water lily, is Bangladesh\'s national flower and appears on the national emblem.',
  },
  {
    id: 'q-nat-bird',
    category: 'symbols',
    type: 'mc',
    prompt: "Which bird is Bangladesh's national bird?",
    options: ['Peacock', 'Oriental magpie robin (Doyel)', 'Eagle', 'Parrot'],
    correct: 1,
    explanation: 'The Oriental magpie robin (দোয়েল, Doyel) is Bangladesh\'s national bird.',
  },
  {
    id: 'q-nat-sport',
    category: 'symbols',
    type: 'mc',
    prompt: 'What is the national sport of Bangladesh?',
    options: ['Cricket', 'Football', 'Kabaddi (Ha-du-du)', 'Field Hockey'],
    correct: 2,
    explanation: 'Kabaddi (কাবাডি), also called Ha-du-du, is the national sport of Bangladesh.',
  },
  {
    id: 'q-nat-flag',
    category: 'symbols',
    type: 'mc',
    prompt: "Bangladesh's national flag features a red circle on what background color?",
    options: ['Blue', 'White', 'Green', 'Red'],
    correct: 2,
    explanation: 'The flag of Bangladesh shows a red circle (representing the rising sun and the blood of independence martyrs) on a green field (representing the land).',
  },
  {
    id: 'q-nat-emblem',
    category: 'symbols',
    type: 'mc',
    prompt: "Which of these does NOT appear on the national emblem of Bangladesh?",
    options: ['Shapla (water lily)', 'Rice sheaves', 'Jute leaves', 'Royal Bengal Tiger'],
    correct: 3,
    explanation: 'The national emblem shows a Shapla on water, flanked by rice sheaves and jute leaves, with four stars and a water lily at the top. The Royal Bengal Tiger does not appear on the emblem.',
  },
  {
    id: 'q-nat-religion',
    category: 'symbols',
    type: 'mc',
    prompt: 'Which religion is designated as the state religion of Bangladesh?',
    options: ['Hinduism', 'Buddhism', 'Islam', 'Christianity'],
    correct: 2,
    explanation: 'Islam is the state religion of Bangladesh, though the constitution also guarantees freedom of religion.',
  },
  {
    id: 'q-nat-anthem',
    category: 'symbols',
    type: 'mc',
    prompt: 'Who wrote the lyrics of the national anthem "Amar Shonar Bangla"?',
    options: ['Kazi Nazrul Islam', 'Rabindranath Tagore', 'Bankim Chandra Chatterjee', 'Fakir Lalon Shah'],
    correct: 1,
    explanation: '"আমার সোনার বাংলা" was written by Rabindranath Tagore (রবীন্দ্রনাথ ঠাকুর) in 1905.',
  },
  {
    id: 'q-nat-language',
    category: 'symbols',
    type: 'mc',
    prompt: 'What is the official language of Bangladesh?',
    options: ['Urdu', 'Hindi', 'Bengali (Bangla)', 'English'],
    correct: 2,
    explanation: 'Bengali (বাংলা), also called Bangla, is the official language of Bangladesh.',
  },
  // FIB variants for symbols
  {
    id: 'q-nat-animal-fib',
    category: 'symbols',
    type: 'fib',
    prompt: 'The national animal of Bangladesh is the Royal Bengal _____.',
    answer: ['Tiger', 'tiger'],
    explanation: 'The Royal Bengal Tiger (বাঘ) is Bangladesh\'s national animal.',
  },
  {
    id: 'q-nat-fruit-fib',
    category: 'symbols',
    type: 'fib',
    prompt: 'The national fruit of Bangladesh is _____.',
    answer: ['Jackfruit', 'jackfruit'],
    explanation: 'Jackfruit (কাঁঠাল) is the national fruit of Bangladesh.',
  },
  {
    id: 'q-nat-flower-fib',
    category: 'symbols',
    type: 'fib',
    prompt: 'The national flower of Bangladesh is the white water _____ (Shapla).',
    answer: ['Lily', 'lily'],
    explanation: 'The Shapla (শাপলা), or white water lily, is Bangladesh\'s national flower.',
  },

  // ── HISTORY ─────────────────────────────────────────────
  {
    id: 'q-hist-independence',
    category: 'history',
    type: 'mc',
    prompt: 'Bangladesh declared independence from which country in 1971?',
    options: ['India', 'West Pakistan (then Pakistan)', 'United Kingdom', 'Burma (Myanmar)'],
    correct: 1,
    explanation: 'Bangladesh declared independence from West Pakistan on 26 March 1971, following the Liberation War.',
  },
  {
    id: 'q-hist-ind-day',
    category: 'history',
    type: 'mc',
    prompt: "On which date is Bangladesh's Independence Day officially celebrated?",
    options: ['26 March', '26 January', '14 April', '16 December'],
    correct: 0,
    explanation: 'Independence Day (স্বাধীনতা দিবস) is celebrated on 26 March, the day independence was declared in 1971.',
  },
  {
    id: 'q-hist-victory',
    category: 'history',
    type: 'mc',
    prompt: 'Which date is Victory Day (Bijoy Dibosh) celebrated in Bangladesh?',
    options: ['26 March', '14 April', '16 December', '21 February'],
    correct: 2,
    explanation: 'Victory Day (বিজয় দিবস) is celebrated on 16 December, when Pakistani forces surrendered in 1971.',
  },
  {
    id: 'q-hist-language',
    category: 'history',
    type: 'mc',
    prompt: 'What significant event occurred on 21 February 1952 in Bangladesh?',
    options: ['Independence was declared', 'Language Movement protests — students died defending Bengali', 'The Liberation War ended', 'The constitution was signed'],
    correct: 1,
    explanation: 'On 21 February 1952, students were killed protesting for the right to use Bengali. This date is now International Mother Language Day.',
  },
  {
    id: 'q-hist-iml',
    category: 'history',
    type: 'mc',
    prompt: '21 February is observed internationally as:',
    options: ['World Peace Day', 'International Mother Language Day', 'UNESCO Education Day', 'World Heritage Day'],
    correct: 1,
    explanation: 'UNESCO declared 21 February as International Mother Language Day in 1999, inspired by Bangladesh\'s 1952 Language Movement.',
  },
  {
    id: 'q-hist-mujib',
    category: 'history',
    type: 'mc',
    prompt: 'Sheikh Mujibur Rahman is primarily known as:',
    options: ['First president of Pakistan', 'Father of the Nation of Bangladesh', 'Founder of the Bengali language', 'First Nobel laureate from Bangladesh'],
    correct: 1,
    explanation: 'Sheikh Mujibur Rahman (শেখ মুজিবুর রহমান) is known as the Father of the Nation of Bangladesh and led the independence movement.',
  },
  // FIB for history
  {
    id: 'q-hist-year-fib',
    category: 'history',
    type: 'fib',
    prompt: 'Bangladesh declared independence in the year _____.',
    answer: ['1971'],
    explanation: 'Bangladesh declared independence from Pakistan on 26 March 1971.',
  },

  // ── LANGUAGE & LITERATURE ────────────────────────────────
  {
    id: 'q-lang-tagore-nobel',
    category: 'language',
    type: 'mc',
    prompt: 'Rabindranath Tagore won the Nobel Prize in which category in 1913?',
    options: ['Peace', 'Literature', 'Physics', 'Economics'],
    correct: 1,
    explanation: 'Rabindranath Tagore (রবীন্দ্রনাথ ঠাকুর) won the Nobel Prize in Literature in 1913 for his collection Gitanjali, becoming the first Asian Nobel laureate.',
  },
  {
    id: 'q-lang-nat-poet',
    category: 'language',
    type: 'mc',
    prompt: 'Who is known as the national poet of Bangladesh?',
    options: ['Rabindranath Tagore', 'Kazi Nazrul Islam', 'Jibanananda Das', 'Humayun Ahmed'],
    correct: 1,
    explanation: 'Kazi Nazrul Islam (কাজী নজরুল ইসলাম) is the national poet of Bangladesh, celebrated for revolutionary poems and songs.',
  },
  {
    id: 'q-lang-script',
    category: 'language',
    type: 'mc',
    prompt: 'Bengali is written using which script?',
    options: ['Devanagari', 'Arabic', 'Bengali script (Bengali-Assamese)', 'Latin'],
    correct: 2,
    explanation: 'Bengali is written in the Bengali script (বাংলা লিপি), also called the Bengali-Assamese script.',
  },
  {
    id: 'q-lang-speakers',
    category: 'language',
    type: 'mc',
    prompt: 'By number of native speakers, Bengali is approximately which most-spoken language in the world?',
    options: ['5th', '7th', '15th', '20th'],
    correct: 1,
    explanation: 'Bengali is spoken by around 230 million people and is roughly the 7th most-spoken language by native speakers worldwide.',
  },
  {
    id: 'q-lang-tagore-anthem',
    category: 'language',
    type: 'mc',
    prompt: 'Rabindranath Tagore also wrote the national anthem of which other country besides Bangladesh?',
    options: ['India', 'Sri Lanka', 'Nepal', 'Pakistan'],
    correct: 0,
    explanation: 'Tagore wrote both "Amar Shonar Bangla" (Bangladesh\'s anthem) and "Jana Gana Mana" (India\'s anthem).',
  },
  {
    id: 'q-lang-satyajit',
    category: 'language',
    type: 'mc',
    prompt: 'Satyajit Ray, the legendary Bengali filmmaker, is best known for which film trilogy?',
    options: ['Pather Panchali trilogy (Apu Trilogy)', 'Mughal trilogy', 'Partition trilogy', 'Tagore trilogy'],
    correct: 0,
    explanation: 'Satyajit Ray (সত্যজিৎ রায়) is celebrated for the Apu Trilogy (Pather Panchali, Aparajito, Apur Sansar).',
  },
  // FIB for language
  {
    id: 'q-lang-tagore-fib',
    category: 'language',
    type: 'fib',
    prompt: 'The national anthem of Bangladesh was written by Rabindranath _____.',
    answer: ['Tagore', 'tagore'],
    explanation: 'Rabindranath Tagore (রবীন্দ্রনাথ ঠাকুর) wrote "Amar Shonar Bangla" in 1905.',
  },

  // ── FESTIVALS ─────────────────────────────────────────────
  {
    id: 'q-fest-boishakh',
    category: 'festivals',
    type: 'mc',
    prompt: 'What is the name of the Bengali New Year festival, celebrated on 14 April?',
    options: ['Pohela Boishakh', 'Diwali', 'Eid-ul-Adha', 'Vaisakhi'],
    correct: 0,
    explanation: 'Pohela Boishakh (পহেলা বৈশাখ) is the Bengali New Year, celebrated on 14 April (1st day of the Bengali month Boishakh).',
  },
  {
    id: 'q-fest-mangal',
    category: 'festivals',
    type: 'mc',
    prompt: 'The UNESCO-recognized Mangal Shobhajatra procession is associated with which festival?',
    options: ['Pohela Boishakh', 'Eid-ul-Fitr', 'Durga Puja', 'Christmas'],
    correct: 0,
    explanation: 'Mangal Shobhajatra (মঙ্গল শোভাযাত্রা) is a colorful parade held on Pohela Boishakh, recognized by UNESCO as Intangible Cultural Heritage.',
  },
  {
    id: 'q-fest-durga',
    category: 'festivals',
    type: 'mc',
    prompt: 'Durga Puja in Bangladesh is a major festival of which community?',
    options: ['Muslim', 'Hindu', 'Christian', 'Buddhist'],
    correct: 1,
    explanation: 'Durga Puja (দুর্গাপূজা) is the most important festival for the Hindu community in Bangladesh.',
  },
  {
    id: 'q-fest-eid',
    category: 'festivals',
    type: 'mc',
    prompt: 'Eid-ul-Fitr marks the end of which Islamic month of fasting?',
    options: ['Muharram', 'Rajab', 'Ramadan', 'Dhul Hijja'],
    correct: 2,
    explanation: 'Eid-ul-Fitr (ঈদুল ফিতর) celebrates the end of Ramadan, the holy month of fasting in Islam.',
  },
  {
    id: 'q-fest-eid-adha',
    category: 'festivals',
    type: 'mc',
    prompt: 'Eid-ul-Adha commemorates which event in Islamic tradition?',
    options: ["The Prophet's birthday", "Ibrahim's willingness to sacrifice his son", 'The end of Ramadan', "The night journey of the Prophet"],
    correct: 1,
    explanation: "Eid-ul-Adha (ঈদুল আযহা) or the Festival of Sacrifice commemorates Prophet Ibrahim's willingness to sacrifice his son as an act of obedience.",
  },
  // FIB for festivals
  {
    id: 'q-fest-boishakh-fib',
    category: 'festivals',
    type: 'fib',
    prompt: 'The Bengali New Year celebration is called Pohela _____.',
    answer: ['Boishakh', 'boishakh'],
    explanation: 'Pohela Boishakh (পহেলা বৈশাখ) is the Bengali New Year, celebrated on 14 April.',
  },

  // ── FOOD & CUISINE ────────────────────────────────────────
  {
    id: 'q-food-hilsa',
    category: 'food',
    type: 'mc',
    prompt: 'The Ilish fish is often called "the king of fish." How is it typically prepared in Bangladesh?',
    options: ['Deep fried only', 'Steamed in mustard paste (Shorshe Ilish) or with vegetables', 'Only dried and salted', 'Served raw as sashimi'],
    correct: 1,
    explanation: 'Ilish (ইলিশ) is most famously prepared as Shorshe Ilish — steamed or cooked in mustard sauce — and is a beloved national dish.',
  },
  {
    id: 'q-food-roshogolla',
    category: 'food',
    type: 'mc',
    prompt: 'Roshogolla (Rasgulla) is made from which main ingredient?',
    options: ['Rice and milk', 'Cottage cheese (chenna) balls in sugar syrup', 'Lentils and jaggery', 'Fruits and cream'],
    correct: 1,
    explanation: 'Roshogolla (রসগোল্লা) is a famous Bengali sweet made from soft chenna (fresh cheese) balls soaked in light sugar syrup.',
  },
  {
    id: 'q-food-fuchka',
    category: 'food',
    type: 'mc',
    prompt: '"Fuchka" (also called phuchka) is a popular street snack similar to which North Indian dish?',
    options: ['Samosa', 'Dosa', 'Pani Puri (Golgappa)', 'Pakora'],
    correct: 2,
    explanation: 'Fuchka (ফুচকা) is a crispy hollow puri filled with spiced chickpeas and tamarind water — similar to pani puri.',
  },
  {
    id: 'q-food-panta',
    category: 'food',
    type: 'mc',
    prompt: 'Panta bhat, traditionally eaten on Pohela Boishakh, is made from:',
    options: ['Spiced yogurt', 'Fermented rice soaked in water', 'Lentil soup', 'Pickled vegetables'],
    correct: 1,
    explanation: 'Panta bhat (পান্তা ভাত) is fermented rice soaked in water overnight, traditionally eaten on Bengali New Year with hilsa and chilis.',
  },
  {
    id: 'q-food-mishti-doi',
    category: 'food',
    type: 'mc',
    prompt: 'Mishti doi is a popular Bengali sweet made from:',
    options: ['Fried dough', 'Sweetened, fermented yogurt', 'Steamed rice cake', 'Deep-fried chickpeas'],
    correct: 1,
    explanation: 'Mishti doi (মিষ্টি দই) is a sweet fermented yogurt — a staple Bengali dessert, especially from Bogra.',
  },
  // FIB for food
  {
    id: 'q-food-hilsa-fib',
    category: 'food',
    type: 'fib',
    prompt: 'The national fish of Bangladesh, prized for its rich flavor, is called _____ (or Hilsa).',
    answer: ['Ilish', 'ilish', 'Hilsa', 'hilsa'],
    explanation: 'Ilish (ইলিশ), known as Hilsa in English, is Bangladesh\'s national fish.',
  },

  // ── GEOGRAPHY ─────────────────────────────────────────────
  {
    id: 'q-geo-capital',
    category: 'geography',
    type: 'mc',
    prompt: 'What is the capital city of Bangladesh?',
    options: ['Kolkata', 'Karachi', 'Dhaka', 'Yangon'],
    correct: 2,
    explanation: 'Dhaka (ঢাকা) is the capital and largest city of Bangladesh.',
  },
  {
    id: 'q-geo-border',
    category: 'geography',
    type: 'mc',
    prompt: 'Bangladesh shares its land border mainly with which country?',
    options: ['India', 'Nepal', 'Pakistan', 'Bhutan'],
    correct: 0,
    explanation: 'Bangladesh is almost entirely surrounded by India, sharing about 4,000 km of border. It also shares a small border with Myanmar to the southeast.',
  },
  {
    id: 'q-geo-south',
    category: 'geography',
    type: 'mc',
    prompt: 'Which body of water lies to the south of Bangladesh?',
    options: ['Arabian Sea', 'Bay of Bengal', 'Indian Ocean', 'Pacific Ocean'],
    correct: 1,
    explanation: 'The Bay of Bengal (বঙ্গোপসাগর) forms the southern coast of Bangladesh and is a major waterway for trade and fishing.',
  },
  {
    id: 'q-geo-sundarbans',
    category: 'geography',
    type: 'mc',
    prompt: 'The Sundarbans is the world\'s largest:',
    options: ['Coral reef', 'Mangrove forest', 'Sand delta', 'Rain forest'],
    correct: 1,
    explanation: 'The Sundarbans (সুন্দরবন) is the world\'s largest mangrove forest, shared by Bangladesh and India, and a UNESCO World Heritage Site.',
  },
  {
    id: 'q-geo-rivers',
    category: 'geography',
    type: 'mc',
    prompt: 'Bangladesh is often called the "Land of Rivers." Approximately how many rivers flow through it?',
    options: ['Over 100', 'Over 230', 'Over 700', 'Over 1,500'],
    correct: 2,
    explanation: 'Bangladesh has over 700 rivers, forming one of the world\'s most extensive river systems.',
  },
  {
    id: 'q-geo-no-river',
    category: 'geography',
    type: 'mc',
    prompt: 'Which of these rivers does NOT flow through Bangladesh?',
    options: ['Ganges (Ganga)', 'Brahmaputra', 'Thames', 'Meghna'],
    correct: 2,
    explanation: 'The Thames flows through London. Bangladesh\'s major rivers include the Ganges (Padma), Brahmaputra (Jamuna), and Meghna.',
  },
  {
    id: 'q-geo-districts',
    category: 'geography',
    type: 'mc',
    prompt: 'Bangladesh is administratively divided into how many districts?',
    options: ['32', '48', '64', '80'],
    correct: 2,
    explanation: 'Bangladesh is divided into 64 districts (জেলা), organized under 8 administrative divisions.',
  },
  // FIB for geography
  {
    id: 'q-geo-capital-fib',
    category: 'geography',
    type: 'fib',
    prompt: 'The capital and largest city of Bangladesh is _____.',
    answer: ['Dhaka', 'dhaka'],
    explanation: 'Dhaka (ঢাকা) is the capital of Bangladesh and one of the most densely populated cities in the world.',
  },
  {
    id: 'q-geo-sundarbans-fib',
    category: 'geography',
    type: 'fib',
    prompt: 'The _____ is the world\'s largest mangrove forest, shared by Bangladesh and India.',
    answer: ['Sundarbans', 'sundarbans'],
    explanation: 'The Sundarbans (সুন্দরবন) is a UNESCO World Heritage Site and home to the Royal Bengal Tiger.',
  },

  // ── PEOPLE & CULTURE ─────────────────────────────────────
  {
    id: 'q-ppl-yunus',
    category: 'people',
    type: 'mc',
    prompt: 'Who won the Nobel Peace Prize in 2006 for pioneering microcredit?',
    options: ['Muhammad Yunus', 'Amartya Sen', 'Desmond Tutu', 'Nelson Mandela'],
    correct: 0,
    explanation: 'Muhammad Yunus (মুহাম্মদ ইউনূস), founder of Grameen Bank, won the Nobel Peace Prize in 2006 for developing microcredit for the poor.',
  },
  {
    id: 'q-ppl-sari',
    category: 'people',
    type: 'mc',
    prompt: 'Traditional Bengali women often wear a _____ as part of their national dress.',
    options: ['Kimono', 'Sari', 'Kilt', 'Dirndl'],
    correct: 1,
    explanation: 'The sari (শাড়ি) is the traditional garment for Bengali women; the lungi (লুঙ্গি) is common for men.',
  },
  {
    id: 'q-ppl-baul',
    category: 'people',
    type: 'mc',
    prompt: 'Baul musicians are known for which type of music?',
    options: ['Classical Hindustani raga', 'Mystical folk songs of Bengal', 'Qawwali devotional music', 'Western classical symphonies'],
    correct: 1,
    explanation: 'Bauls (বাউল) are wandering mystic folk musicians of Bengal who sing philosophical songs about the human soul and the divine, recognized by UNESCO.',
  },
  {
    id: 'q-ppl-currency',
    category: 'people',
    type: 'mc',
    prompt: 'What is the currency of Bangladesh?',
    options: ['Taka', 'Rupee', 'Dollar', 'Kyat'],
    correct: 0,
    explanation: 'The Taka (টাকা, ৳) is the currency of Bangladesh.',
  },
  {
    id: 'q-ppl-garment',
    category: 'people',
    type: 'mc',
    prompt: 'Which industry is a major driver of the Bangladesh economy?',
    options: ['Oil and gas', 'Ready-made garments (textiles)', 'Automobile manufacturing', 'Gold mining'],
    correct: 1,
    explanation: "Bangladesh's ready-made garment (RMG) industry is one of the world's largest, making the country a top exporter of clothing.",
  },
];
